# Capstone — mirrors your deployed research paper

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

# Capstone — Search Intelligence Research

## Full-Warehouse Content Decline Prioritization

This capstone investigates whether observable content and SEO performance signals can be used to prioritize pages for earlier human review when they show evidence of declining search performance.

The analysis uses the full pseudonymized FlyRank internship warehouse release and follows a reproducible feature-engineering, modeling, validation, and recommendation workflow.

The objective is decision support: produce a ranked queue that helps content teams decide which pages deserve attention first. The analysis does not attempt to automate content decisions, establish causation, or claim that the observed relationships guarantee future performance.

In [ ]:
from huggingface_hub import login
import getpass

HF_TOKEN = getpass.getpass("Enter your Hugging Face READ token (hf_...): ")
login(token=HF_TOKEN)

print("Hugging Face authentication completed.")

Enter your Hugging Face READ token (hf_...): ··········
Hugging Face authentication completed.

In [ ]:
print("\nTesting warehouse access...")

for name in TABLES:
    try:
        con.execute(
            f"SELECT 1 FROM {name} LIMIT 1"
        ).fetchone()

        print(f"{name:20s} OK")

    except Exception as e:
        print(f"{name:20s} ERROR")
        print(e)

Testing warehouse access...
dim_clients          OK
dim_content          OK
fact_daily           OK
fact_daily_sample    OK
fact_query_90d       OK

In [ ]:
print("\nTesting warehouse access...")

for name in TABLES:
    try:
        con.execute(
            f"SELECT 1 FROM {name} LIMIT 1"
        ).fetchone()

        print(f"{name:20s} OK")

    except Exception as e:
        print(f"{name:20s} ERROR")
        print(e)

Testing warehouse access...
dim_clients          OK
dim_content          OK
fact_daily           OK
fact_daily_sample    OK
fact_query_90d       OK

## Warehouse schema and available signals

Before constructing the final feature table, the analysis inspects the available fields in the warehouse. This prevents assumptions about column availability and ensures that every feature used by the final model is grounded in an actual field from the release.

In [ ]:
# Inspect the schemas of the tables relevant to the Capstone.

for table_name in ["dim_content", "fact_daily", "fact_query_90d"]:
    print("\n" + "=" * 80)
    print(f"{table_name}")
    print("=" * 80)

    schema = con.sql(
        f"DESCRIBE SELECT * FROM {TABLES[table_name]}"
    ).df()

    display(schema)

================================================================================
dim_content
================================================================================

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2              keyword_hash_id     VARCHAR  YES  None    None  None
3                  url_hash_id     VARCHAR  YES  None    None  None
4           keyword_char_count      BIGINT  YES  None    None  None
5          keyword_token_count      BIGINT  YES  None    None  None
6               url_char_count      BIGINT  YES  None    None  None
7         content_created_date        DATE  YES  None    None  None
8         content_updated_date        DATE  YES  None    None  None
9                 content_type     VARCHAR  YES  None    None  None
10               search_volume      BIGINT  YES  None    None  None
11                 competition      DOUBLE  YES  None    None  None
12           competition_level     VARCHAR  YES  None    None  None
13                         cpc      DOUBLE  YES  None    None  None
14                 main_intent     VARCHAR  YES  None    None  None
15                   backlinks      BIGINT  YES  None    None  None
16              category_count      BIGINT  YES  None    None  None
17        keyword_created_date        DATE  YES  None    None  None
18               provider_used     VARCHAR  YES  None    None  None
19                  model_used     VARCHAR  YES  None    None  None
20                  char_count      BIGINT  YES  None    None  None
21                  word_count      BIGINT  YES  None    None  None
22         last_optimized_date        DATE  YES  None    None  None
23  optimization_eligible_date        DATE  YES  None    None  None
24                is_published     BOOLEAN  YES  None    None  None
25                  is_deleted     BOOLEAN  YES  None    None  None

================================================================================
fact_daily
================================================================================

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

================================================================================
fact_query_90d
================================================================================

                      column_name column_type null   key default extra
0                  client_hash_id     VARCHAR  YES  None    None  None
1                 content_hash_id     VARCHAR  YES  None    None  None
2                   query_hash_id     VARCHAR  YES  None    None  None
3                query_char_count      BIGINT  YES  None    None  None
4               query_token_count      BIGINT  YES  None    None  None
5                    window_start        DATE  YES  None    None  None
6                      window_end        DATE  YES  None    None  None
7                 impressions_90d      BIGINT  YES  None    None  None
8                      clicks_90d      BIGINT  YES  None    None  None
9              impressions_last30      BIGINT  YES  None    None  None
10                  clicks_last30      BIGINT  YES  None    None  None
11             impressions_prev30      BIGINT  YES  None    None  None
12                  clicks_prev30      BIGINT  YES  None    None  None
13               avg_position_90d      DOUBLE  YES  None    None  None
14            avg_position_last30      DOUBLE  YES  None    None  None
15            avg_position_prev30      DOUBLE  YES  None    None  None
16  content_total_impressions_90d      BIGINT  YES  None    None  None
17    content_visible_query_count      BIGINT  YES  None    None  None
18               rare_query_count      BIGINT  YES  None    None  None
19         rare_impressions_share      DOUBLE  YES  None    None  None
20   anonymized_impressions_share      DOUBLE  YES  None    None  None

In [ ]:
# Look at a small number of records from each table.
# This is only schema/structure inspection; we are not loading the full tables.

for table_name in ["dim_content", "fact_daily", "fact_query_90d"]:
    print("\n" + "=" * 80)
    print(f"{table_name} — sample rows")
    print("=" * 80)

    sample = con.sql(
        f"SELECT * FROM {TABLES[table_name]} LIMIT 5"
    ).df()

    display(sample)

================================================================================
dim_content — sample rows
================================================================================

,client_hash_id,content_hash_id,keyword_hash_id,url_hash_id,keyword_char_count,keyword_token_count,url_char_count,content_created_date,content_updated_date,content_type,search_volume,competition,competition_level,cpc,main_intent,backlinks,category_count,keyword_created_date,provider_used,model_used,char_count,word_count,last_optimized_date,optimization_eligible_date,is_published,is_deleted
0,client_04660893ae39614a,content_004de9653278b5a4,keyword_e754999ab88dd9f2,url_d6091f18cf628794,22,4,108,2026-05-30,2026-07-01,keyword article,30,0.91,HIGH,0.98,transactional,16,3,2026-05-12,gemini-generate-content,gemini-3-flash-preview,15682,2555,NaT,NaT,True,False
1,client_04660893ae39614a,content_00dc5efae381b2ab,keyword_4329d7aede8e208b,url_3a66d2f2e36823ca,31,6,95,2026-06-12,2026-07-01,keyword article,10,0.00,LOW,0.00,commercial,0,4,2026-06-01,gemini-generate-content,gemini-3-flash-preview,15438,2430,NaT,NaT,True,False
2,client_04660893ae39614a,content_01410f2556c327ac,keyword_9b08047d3d2a0406,url_809eda7a7e20b3b2,22,5,82,2026-05-09,2026-07-01,keyword article,480,0.36,MEDIUM,0.62,informational,169,4,2026-05-06,gemini-generate-content,gemini-3-flash-preview,16576,2645,NaT,NaT,True,False
3,client_04660893ae39614a,content_019f27f634053ca7,keyword_e7cec7ab1804c1c2,url_5fb42bafc4399861,14,3,92,2026-06-15,2026-06-15,keyword article,0,0.00,LOW,0.00,transactional,0,4,2026-06-01,gemini-generate-content,gemini-3-flash-preview,15457,2522,NaT,NaT,True,False
4,client_04660893ae39614a,content_01efa71faea45dcc,keyword_56b0062a1d8b7524,url_ece0abc3e5fb75f9,24,6,98,2026-05-21,2026-06-01,keyword article,2400,0.70,HIGH,0.90,transactional,52,4,2026-05-12,gemini-generate-content,gemini-3-flash-preview,15776,2552,NaT,NaT,True,False

================================================================================
fact_daily — sample rows
================================================================================

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,gsc_avg_position,ga4_pageviews,ga4_sessions,ga4_users,ga4_engaged_sessions,ga4_total_engagement_sec,sessions_organic,sessions_direct,sessions_referral,sessions_social,sessions_paid,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115,3.833333,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-01
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358,71.600000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-01
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34,34.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-01
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140,23.333333,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-01
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89,17.800000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2025-01

================================================================================
fact_query_90d — sample rows
================================================================================

,client_hash_id,content_hash_id,query_hash_id,query_char_count,query_token_count,window_start,window_end,impressions_90d,clicks_90d,impressions_last30,clicks_last30,impressions_prev30,clicks_prev30,avg_position_90d,avg_position_last30,avg_position_prev30,content_total_impressions_90d,content_visible_query_count,rare_query_count,rare_impressions_share,anonymized_impressions_share
0,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_58b1b001f839d699,17,3,2026-04-02,2026-06-30,11,0,0,0,11,0,10.818182,NaN,10.818182,1466,14,32,0.043656,0.725102
1,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_922b8eca2a24cd34,34,7,2026-04-02,2026-06-30,13,0,0,0,1,0,1.769231,NaN,11.000000,1466,14,32,0.043656,0.725102
2,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,16,2,2026-04-02,2026-06-30,16,0,11,0,5,0,23.562500,24.272727,22.000000,1466,14,32,0.043656,0.725102
3,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_a032820b5467e996,24,4,2026-04-02,2026-06-30,55,0,1,0,1,0,2.200000,13.000000,0.000000,1466,14,32,0.043656,0.725102
4,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_ba1a2f131961c5da,18,3,2026-04-02,2026-06-30,14,0,0,0,0,0,3.428571,NaN,NaN,1466,14,32,0.043656,0.725102

## Client history and panel coverage

The warehouse is an unbalanced panel: clients do not necessarily have identical periods of available search data. Before defining the modeling window, client-level coverage is inspected so that the feature and outcome windows are supported by actual observations rather than assumed to be available for every client.

In [ ]:
client_history = con.sql(
    f"""
    SELECT
        client_hash_id,
        MIN(report_date) AS first_date,
        MAX(report_date) AS last_date,
        COUNT(DISTINCT report_date) AS observed_days
    FROM {TABLES['fact_daily']}
    GROUP BY client_hash_id
    ORDER BY first_date
    """
).df()

print(f"Clients represented in fact_daily: {len(client_history):,}")
display(client_history)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Clients represented in fact_daily: 70

             client_hash_id first_date  last_date  observed_days
0   client_ff644d8251367cbb 2025-01-27 2026-06-30            514
1   client_9958f0a7ae1df715 2025-01-27 2026-06-30            520
2   client_73cda7b4e4f265ea 2025-02-11 2026-06-30            505
3   client_fef1a8f436438636 2025-03-11 2026-06-30            477
4   client_62f4a7e64f5e0096 2025-06-07 2026-06-30            389
5   client_b10cb2997d0c7c86 2025-06-18 2026-06-30            378
6   client_65de48885f4ef01b 2025-06-21 2026-06-30            375
7   client_c182d11e4862a37d 2025-06-21 2026-06-30            375
8   client_3197e6291363b4db 2025-06-29 2026-06-30            367
9   client_625b6439094e23e4 2025-07-01 2026-06-30            252
10  client_a2eeb8899886adde 2025-07-06 2026-06-30            324
11  client_d211cb07b9059bab 2025-07-07 2026-06-30            340
12  client_def0955f7a377868 2025-07-17 2026-06-30            349
13  client_08d2847f24cf89c1 2025-07-21 2026-06-30            345
14  client_8ae2bfb5aa1ffa1e 2025-07-28 2026-06-30            338
15  client_8dbf3abdf07569e0 2025-07-29 2026-06-30            337
16  client_795153d5b7850ccf 2025-09-24 2026-06-30            280
17  client_23a62021009f63c4 2025-09-24 2026-06-30            280
18  client_2910fd937f0b4d9a 2025-09-24 2026-06-30            264
19  client_0e1acc6cd57b0eba 2025-09-24 2026-06-30            272
20  client_59256b0571e0c970 2025-09-24 2026-06-30            261
21  client_08a6a72ff48e62c0 2025-09-24 2026-06-30            280
22  client_4a18d1793d92fb84 2025-09-24 2026-06-30            195
23  client_599043c0ff13edea 2025-09-27 2026-06-30            256
24  client_3ffa76342f366962 2025-10-11 2026-06-30            248
25  client_e547b89c05043229 2025-10-13 2026-06-30            261
26  client_2094c6eb080311d5 2025-10-13 2026-06-30            261
27  client_ba65e80a1116ae41 2025-10-13 2026-06-30            261
28  client_400c21c81c8b46ef 2025-10-13 2026-06-30            261
29  client_19b89ee4fe3db6da 2025-10-13 2026-06-25            256
30  client_a1203ffecad62470 2025-10-20 2026-06-30            240
31  client_cd12bcfd98942aa1 2025-10-20 2026-06-27            250
32  client_a60a11451483af1c 2025-11-05 2026-06-29            237
33  client_764ae36a94e30a25 2025-11-05 2026-05-31            208
34  client_1d09b519bdde7c7a 2025-11-05 2026-02-24            112
35  client_f623b01661d4bfe4 2025-11-05 2026-06-25            233
36  client_835f9123c933bc01 2025-11-05 2026-02-24            112
37  client_2e65897d94f60220 2025-11-05 2026-02-24            112
38  client_861cdcccf8049915 2025-11-05 2026-02-23            111
39  client_770e8e5faa9cddfe 2025-11-05 2026-06-30            238
40  client_80ee5b7bd5f4eb89 2025-11-05 2026-06-30            238
41  client_0797ff3a1fc9a6a5 2025-11-05 2026-06-25            233
42  client_2c32078d69f2cbad 2025-11-05 2026-06-25            233
43  client_ccdd78843409c8c7 2026-02-12 2026-06-30            139
44  client_0fa64a184f18a4a0 2026-02-17 2026-06-30            134
45  client_9d54435aabd95a6c 2026-02-17 2026-06-30            134
46  client_1a730cb2640a1abf 2026-02-19 2026-06-30            132
47  client_2b4306c3ed003f01 2026-02-19 2026-06-30            132
48  client_20259bd6705d81d4 2026-02-19 2026-06-30            132
49  client_3f0ce4d44fe94f3d 2026-02-19 2026-06-30            132
50  client_157ffe4d4a595515 2026-02-19 2026-06-30            132
51  client_a80fca3f171ed1de 2026-02-19 2026-06-30            132
52  client_e5c2aa26a8598242 2026-02-19 2026-06-30            132
53  client_7eafe750768f0ac2 2026-02-26 2026-06-30            125
54  client_b77d0d5f08f05e64 2026-03-01 2026-06-30            122
55  client_86ebc2f12c01f586 2026-03-03 2026-06-30            120
56  client_f6f0cdf26d03d7bd 2026-03-19 2026-06-30            104
57  client_810019792c9b8efc 2026-03-20 2026-06-30            103
58  client_e00b29e582949543 2026-03-23 2026-06-30            100
59  client_8ddc46da5414ffd8 2026-04-02 2026-06-30             90
60  client_06d356715a8ff3b6 2026-04-02 2026-06-30             90
61  client_0b245132bb722950 2026-04-06 2026-06-30             86
62  client_9c26c096d6e57253 2026-04-16 2026-06-30             76
63  client_7de9989c909e91a5 2026-04-20 2026-06-30             72
64  client_c353557474475e51 2026-04-30 2026-06-30             52
65  client_1a8bf67cad4ee525 2026-05-09 2026-06-30             53
66  client_c7c2962f1c9c3089 2026-05-09 2026-06-30             53
67  client_04660893ae39614a 2026-05-22 2026-06-30             40
68  client_a22068e339bf95f5 2026-05-22 2026-06-30             40
69  client_aef6ffea193da149 2026-05-28 2026-06-30             34

## Monthly warehouse coverage

The monthly distribution is checked before selecting the Capstone observation and outcome windows. This confirms where sufficient historical data exists and helps avoid choosing a window that is supported by only a small portion of the panel.

In [ ]:
monthly_coverage = con.sql(
    f"""
    SELECT
        month,
        COUNT(*) AS rows,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content_items,
        MIN(report_date) AS min_date,
        MAX(report_date) AS max_date
    FROM {TABLES['fact_daily']}
    GROUP BY month
    ORDER BY month
    """
).df()

display(monthly_coverage)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

      month      rows  clients  content_items   min_date   max_date
0   2025-01      1297        2            476 2025-01-27 2025-01-31
1   2025-02     75985        3           5903 2025-02-01 2025-02-28
2   2025-03    167859        4          10374 2025-03-01 2025-03-31
3   2025-04    285114        4          13046 2025-04-01 2025-04-30
4   2025-05    349923        4          14887 2025-05-01 2025-05-31
5   2025-06    329201        9          16399 2025-06-01 2025-06-30
6   2025-07    469794       16          27945 2025-07-01 2025-07-31
7   2025-08    704962       15          37204 2025-08-01 2025-08-31
8   2025-09    845813       23          53127 2025-09-01 2025-09-30
9   2025-10   2165471       31         110339 2025-10-01 2025-10-31
10  2025-11   6793825       43         251384 2025-11-01 2025-11-30
11  2025-12   7752930       43         254621 2025-12-01 2025-12-31
12  2026-01   7890817       42         261984 2026-01-01 2026-01-31
13  2026-02   7355108       54         321546 2026-02-01 2026-02-28
14  2026-03   9841378       55         331437 2026-03-01 2026-03-31
15  2026-04  10424730       61         362172 2026-04-01 2026-04-30
16  2026-05  11687376       66         389153 2026-05-01 2026-05-31
17  2026-06  11694072       65         409205 2026-06-01 2026-06-30

## Search Console availability

Because the Capstone focuses on search-performance decline, the analysis verifies the availability of Search Console data before defining the usable modeling population. Rows without available GSC data should not silently be treated as zero search performance.

In [ ]:
gsc_availability = con.sql(
    f"""
    SELECT
        month,
        COUNT(*) AS total_rows,
        COUNT(*) FILTER (
            WHERE gsc_data_available IS TRUE
        ) AS gsc_available_rows,
        COUNT(*) FILTER (
            WHERE gsc_data_available IS FALSE
        ) AS gsc_unavailable_rows
    FROM {TABLES['fact_daily']}
    GROUP BY month
    ORDER BY month
    """
).df()

gsc_availability["gsc_available_pct"] = (
    gsc_availability["gsc_available_rows"]
    / gsc_availability["total_rows"]
    * 100
)

display(gsc_availability)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,month,total_rows,gsc_available_rows,gsc_unavailable_rows,gsc_available_pct
0,2025-01,1297,1297,0,100.000000
1,2025-02,75985,75985,0,100.000000
2,2025-03,167859,167859,0,100.000000
3,2025-04,285114,285114,0,100.000000
4,2025-05,349923,349923,0,100.000000
5,2025-06,329201,329201,0,100.000000
6,2025-07,469794,469794,0,100.000000
7,2025-08,704962,704962,0,100.000000
8,2025-09,845813,845813,0,100.000000
9,2025-10,2165471,1187654,977817,54.845066
10,2025-11,6793825,1681368,5112457,24.748474
11,2025-12,7752930,2087675,5665255,26.927562
12,2026-01,7890817,2397143,5487924,30.378895
13,2026-02,7355108,2621783,4641069,35.645744
14,2026-03,9841378,3611061,6230317,36.692636
15,2026-04,10424730,3901060,6523670,37.421209
16,2026-05,11687376,4373422,7313954,37.420050
17,2026-06,11694072,3878937,7815135,33.170114

In [ ]:
# Content-level history and GSC availability audit

content_history = con.sql(f"""
    SELECT
        client_hash_id,
        content_hash_id,
        MIN(report_date) AS first_date,
        MAX(report_date) AS last_date,
        COUNT(*) AS observed_rows,

        SUM(
            CASE
                WHEN gsc_data_available THEN 1
                ELSE 0
            END
        ) AS gsc_available_days,

        SUM(
            CASE
                WHEN NOT gsc_data_available THEN 1
                ELSE 0
            END
        ) AS gsc_unavailable_days,

        SUM(
            CASE
                WHEN gsc_data_available
                     AND gsc_impressions IS NOT NULL
                THEN gsc_impressions
                ELSE 0
            END
        ) AS total_gsc_impressions,

        SUM(
            CASE
                WHEN gsc_data_available
                     AND gsc_clicks IS NOT NULL
                THEN gsc_clicks
                ELSE 0
            END
        ) AS total_gsc_clicks

    FROM {TABLES['fact_daily']}

    GROUP BY
        client_hash_id,
        content_hash_id
""").df()

print(f"Content-client histories: {len(content_history):,}")

print("\nHistory length distribution:")
print(
    content_history["observed_rows"]
    .describe()
    .to_string()
)

print("\nGSC availability:")
content_history["gsc_available_pct"] = (
    content_history["gsc_available_days"]
    / content_history["observed_rows"]
    * 100
)

print(
    content_history["gsc_available_pct"]
    .describe()
    .to_string()
)

print("\nFirst 10 rows:")
display(content_history.head(10))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Content-client histories: 427,292

History length distribution:
count    427292.000000
mean        184.500658
std          93.721777
min           3.000000
25%         112.000000
50%         218.000000
75%         240.000000
max         520.000000

GSC availability:
count    427292.000000
mean         34.589617
std          38.539889
min           0.000000
25%           0.000000
50%          12.987013
75%          75.968992
max         100.000000

First 10 rows:

,client_hash_id,content_hash_id,first_date,last_date,observed_rows,gsc_available_days,gsc_unavailable_days,total_gsc_impressions,total_gsc_clicks,gsc_available_pct
0,client_9958f0a7ae1df715,content_199a7503ef4984b6,2025-02-04,2026-06-30,511,468.0,43.0,14328.0,70.0,91.585127
1,client_9958f0a7ae1df715,content_cd7680fa9ecf0f29,2025-02-04,2026-06-30,512,460.0,52.0,5845.0,5.0,89.843750
2,client_9958f0a7ae1df715,content_a1de860c6349747e,2025-02-04,2026-06-30,512,470.0,42.0,4787.0,19.0,91.796875
3,client_9958f0a7ae1df715,content_cd36f906cac66324,2025-02-06,2026-06-30,510,508.0,2.0,11963.0,29.0,99.607843
4,client_9958f0a7ae1df715,content_28de1fb24f0fb4a8,2025-02-03,2026-06-30,513,507.0,6.0,19741.0,34.0,98.830409
5,client_9958f0a7ae1df715,content_98e997bcdf93db50,2025-02-06,2026-06-30,510,454.0,56.0,6440.0,3.0,89.019608
6,client_9958f0a7ae1df715,content_6afb4ede795f9338,2025-02-07,2026-06-30,509,508.0,1.0,12548.0,12.0,99.803536
7,client_9958f0a7ae1df715,content_12415a5ac1570217,2025-02-04,2026-06-30,512,482.0,30.0,22379.0,143.0,94.140625
8,client_9958f0a7ae1df715,content_160adf69243b631f,2025-02-04,2026-06-30,512,446.0,66.0,5859.0,3.0,87.109375
9,client_9958f0a7ae1df715,content_875ebebd0b4b106d,2025-02-07,2026-06-30,509,492.0,17.0,37043.0,436.0,96.660118

In [ ]:
# GSC availability by client

client_gsc_availability = con.sql(f"""
    SELECT
        client_hash_id,

        COUNT(*) AS total_rows,

        SUM(
            CASE
                WHEN gsc_data_available THEN 1
                ELSE 0
            END
        ) AS gsc_available_rows,

        ROUND(
            100.0 * SUM(
                CASE
                    WHEN gsc_data_available THEN 1
                    ELSE 0
                END
            ) / COUNT(*),
            2
        ) AS gsc_available_pct,

        MIN(
            CASE
                WHEN gsc_data_available THEN report_date
            END
        ) AS first_gsc_available_date,

        MAX(
            CASE
                WHEN gsc_data_available THEN report_date
            END
        ) AS last_gsc_available_date

    FROM {TABLES['fact_daily']}

    GROUP BY client_hash_id

    ORDER BY gsc_available_pct DESC
""").df()

print(f"Clients analyzed: {len(client_gsc_availability):,}")

display(client_gsc_availability)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Clients analyzed: 70

,client_hash_id,total_rows,gsc_available_rows,gsc_available_pct,first_gsc_available_date,last_gsc_available_date
0,client_e5c2aa26a8598242,555095,501795.0,90.40,2026-02-19,2026-06-30
1,client_8ddc46da5414ffd8,285053,248287.0,87.10,2026-04-07,2026-06-30
2,client_9958f0a7ae1df715,1470881,1262452.0,85.83,2025-01-27,2026-06-30
3,client_20259bd6705d81d4,667479,570184.0,85.42,2026-02-19,2026-06-30
4,client_23a62021009f63c4,3251375,2748802.0,84.54,2025-09-24,2026-06-30
5,client_73cda7b4e4f265ea,8708971,7326196.0,84.12,2025-02-11,2026-06-30
6,client_62f4a7e64f5e0096,5676451,4769284.0,84.02,2025-06-07,2026-06-30
7,client_e547b89c05043229,2451879,1954051.0,79.70,2025-11-15,2026-06-30
8,client_06d356715a8ff3b6,96192,74169.0,77.11,2026-04-10,2026-06-30
9,client_86ebc2f12c01f586,195220,149213.0,76.43,2026-03-11,2026-06-30
10,client_1a8bf67cad4ee525,79902,58021.0,72.62,2026-05-11,2026-06-30
11,client_1a730cb2640a1abf,419741,290730.0,69.26,2026-02-19,2026-06-30
12,client_a22068e339bf95f5,37006,25473.0,68.83,2026-05-24,2026-06-30
13,client_0fa64a184f18a4a0,254934,169855.0,66.63,2026-02-19,2026-06-30
14,client_fef1a8f436438636,2779933,1793810.0,64.53,2025-03-11,2026-06-30
15,client_0b245132bb722950,53471,27580.0,51.58,2026-04-12,2026-06-30
16,client_a80fca3f171ed1de,971798,490320.0,50.45,2026-02-19,2026-06-30
17,client_861cdcccf8049915,792096,386513.0,48.80,2025-11-05,2026-02-21
18,client_157ffe4d4a595515,707510,327886.0,46.34,2026-02-19,2026-06-30
19,client_810019792c9b8efc,175586,78817.0,44.89,2026-03-25,2026-06-30
20,client_3f0ce4d44fe94f3d,875052,389176.0,44.47,2026-02-19,2026-06-30
21,client_c182d11e4862a37d,282410,112408.0,39.80,2025-06-21,2026-06-30
22,client_08a6a72ff48e62c0,6580654,2226145.0,33.83,2025-09-24,2026-06-30
23,client_c7c2962f1c9c3089,29612,9837.0,33.22,2026-05-14,2026-06-30
24,client_400c21c81c8b46ef,854645,270178.0,31.61,2025-10-26,2026-06-30
25,client_2094c6eb080311d5,1274629,375035.0,29.42,2025-12-17,2026-06-30
26,client_b77d0d5f08f05e64,323347,94594.0,29.25,2026-03-12,2026-06-30
27,client_ff644d8251367cbb,1246888,363661.0,29.17,2025-01-27,2026-06-30
28,client_e00b29e582949543,203574,59074.0,29.02,2026-03-27,2026-06-30
29,client_ccdd78843409c8c7,55073,14394.0,26.14,2026-02-17,2026-06-30
30,client_f6f0cdf26d03d7bd,45292,8972.0,19.81,2026-03-19,2026-06-30
31,client_3197e6291363b4db,2598532,508896.0,19.58,2025-06-29,2026-06-30
32,client_7eafe750768f0ac2,116580,22344.0,19.17,2026-02-26,2026-06-30
33,client_b10cb2997d0c7c86,1050146,183037.0,17.43,2025-06-18,2026-06-30
34,client_2e65897d94f60220,564704,95446.0,16.90,2025-11-05,2026-02-22
35,client_08d2847f24cf89c1,98848,13733.0,13.89,2025-07-21,2026-06-30
36,client_1d09b519bdde7c7a,199584,27169.0,13.61,2025-11-05,2026-02-22
37,client_9c26c096d6e57253,143625,18431.0,12.83,2026-04-29,2026-06-30
38,client_def0955f7a377868,180193,20225.0,11.22,2025-07-17,2026-06-30
39,client_7de9989c909e91a5,74596,8240.0,11.05,2026-05-18,2026-06-30
40,client_8ae2bfb5aa1ffa1e,88838,8995.0,10.13,2025-07-28,2026-05-18
41,client_9d54435aabd95a6c,220769,21041.0,9.53,2026-02-19,2026-06-30
42,client_0797ff3a1fc9a6a5,60580,5227.0,8.63,2025-11-05,2026-06-23
43,client_65de48885f4ef01b,3296200,267439.0,8.11,2025-06-21,2026-06-30
44,client_cd12bcfd98942aa1,1384367,111752.0,8.07,2025-10-20,2026-06-27
45,client_795153d5b7850ccf,624716,50339.0,8.06,2025-09-24,2026-06-25
46,client_8dbf3abdf07569e0,142719,11318.0,7.93,2025-07-29,2026-05-10
47,client_2c32078d69f2cbad,2619,182.0,6.95,2025-11-05,2026-01-08
48,client_0e1acc6cd57b0eba,35110,1843.0,5.25,2025-09-24,2026-06-30
49,client_d211cb07b9059bab,423779,17865.0,4.22,2025-07-07,2026-06-30
50,client_3ffa76342f366962,6701663,272312.0,4.06,2025-10-11,2026-06-30
51,client_a2eeb8899886adde,306131,11763.0,3.84,2025-07-06,2026-06-30
52,client_f623b01661d4bfe4,1335268,48941.0,3.67,2026-01-09,2026-06-23
53,client_a60a11451483af1c,1310139,33931.0,2.59,2025-11-16,2026-06-27
54,client_59256b0571e0c970,26449,454.0,1.72,2025-09-24,2026-06-30
55,client_4a18d1793d92fb84,677475,8169.0,1.21,2025-09-24,2026-06-28
56,client_c353557474475e51,29104,321.0,1.10,2026-04-30,2026-06-30
57,client_764ae36a94e30a25,25168,215.0,0.85,2025-11-07,2026-05-29
58,client_2b4306c3ed003f01,1600632,11572.0,0.72,2026-02-19,2026-06-30
59,client_aef6ffea193da149,18920,129.0,0.68,2026-06-02,2026-06-24
60,client_ba65e80a1116ae41,3388865,10293.0,0.30,2025-10-13,2026-06-30
61,client_835f9123c933bc01,448672,1028.0,0.23,2025-11-05,2026-02-22
62,client_a1203ffecad62470,17852,25.0,0.14,2025-10-20,2026-03-15
63,client_599043c0ff13edea,173055,201.0,0.12,2025-09-27,2026-05-07
64,client_770e8e5faa9cddfe,47600,26.0,0.05,2025-11-17,2025-12-22
65,client_2910fd937f0b4d9a,694651,95.0,0.01,2025-09-24,2026-06-30
66,client_19b89ee4fe3db6da,1653823,0.0,0.00,NaT,NaT
67,client_625b6439094e23e4,7589247,142.0,0.00,2025-07-01,2025-11-10
68,client_80ee5b7bd5f4eb89,46648,0.0,0.00,NaT,NaT
69,client_04660893ae39614a,36039,0.0,0.00,NaT,NaT

## 4. Content-Level Performance Analysis

We now aggregate the daily performance data to the content level. The goal is to understand
which content items are generating meaningful organic search and engagement performance,
while keeping the computation inside DuckDB.

In [ ]:
monthly_performance = con.execute("""
    SELECT
        DATE_TRUNC('month', report_date) AS month,
        COUNT(*) AS rows,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content_items,

        SUM(COALESCE(gsc_impressions, 0)) AS gsc_impressions,
        SUM(COALESCE(gsc_clicks, 0)) AS gsc_clicks,

        SUM(COALESCE(ga4_pageviews, 0)) AS pageviews,
        SUM(COALESCE(ga4_sessions, 0)) AS sessions,

        SUM(COALESCE(sessions_organic, 0)) AS organic_sessions,
        SUM(COALESCE(sessions_ai, 0)) AS ai_sessions

    FROM fact_daily

    GROUP BY 1
    ORDER BY 1
""").df()

monthly_performance

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,month,rows,clients,content_items,gsc_impressions,gsc_clicks,pageviews,sessions,organic_sessions,ai_sessions
0,2025-01-01,1297,2,476,13853.0,108.0,0.0,0.0,0.0,0.0
1,2025-02-01,75985,3,5903,1195015.0,7823.0,0.0,0.0,0.0,0.0
2,2025-03-01,167859,4,10374,3847103.0,26138.0,0.0,0.0,0.0,0.0
3,2025-04-01,285114,4,13046,8843940.0,52974.0,0.0,0.0,0.0,0.0
4,2025-05-01,349923,4,14887,14454515.0,70374.0,0.0,0.0,0.0,0.0
5,2025-06-01,329201,9,16399,16930659.0,70245.0,0.0,0.0,0.0,0.0
6,2025-07-01,469794,16,27945,20298448.0,84676.0,0.0,0.0,0.0,0.0
7,2025-08-01,704962,15,37204,29289942.0,119373.0,0.0,0.0,0.0,0.0
8,2025-09-01,845813,23,53127,37726329.0,176130.0,0.0,0.0,0.0,0.0
9,2025-10-01,2165471,31,110339,55073098.0,274631.0,35809.0,22210.0,34009.0,422.0
10,2025-11-01,6793825,43,251384,83871948.0,341306.0,332735.0,229925.0,285340.0,3670.0
11,2025-12-01,7752930,43,254621,112406941.0,359302.0,311656.0,208197.0,235893.0,3779.0
12,2026-01-01,7890817,42,261984,144354689.0,476140.0,355665.0,219449.0,268574.0,4766.0
13,2026-02-01,7355108,54,321546,180128922.0,586205.0,527677.0,345261.0,287257.0,5793.0
14,2026-03-01,9841378,55,331437,280657589.0,821832.0,1484856.0,1299808.0,585408.0,8911.0
15,2026-04-01,10424730,61,362172,292067218.0,840207.0,1517002.0,1081806.0,883707.0,12273.0
16,2026-05-01,11687376,66,389153,266164899.0,924256.0,3218281.0,2146646.0,1034385.0,11242.0
17,2026-06-01,11694072,65,409205,216194872.0,1209117.0,4861097.0,2759763.0,1598823.0,32762.0

In [ ]:
monthly_rates = con.execute("""
    SELECT
        month,
        rows,
        clients,
        content_items,

        gsc_impressions,
        gsc_clicks,

        CASE
            WHEN gsc_impressions > 0
            THEN gsc_clicks * 100.0 / gsc_impressions
            ELSE NULL
        END AS gsc_ctr_pct,

        pageviews,
        sessions,
        organic_sessions,
        ai_sessions,

        CASE
            WHEN sessions > 0
            THEN organic_sessions * 100.0 / sessions
            ELSE NULL
        END AS organic_session_share_pct,

        CASE
            WHEN sessions > 0
            THEN ai_sessions * 100.0 / sessions
            ELSE NULL
        END AS ai_session_share_pct,

        CASE
            WHEN content_items > 0
            THEN gsc_impressions * 1.0 / content_items
            ELSE NULL
        END AS impressions_per_content

    FROM monthly_performance

    ORDER BY month
""").df()

monthly_rates

,month,rows,clients,content_items,gsc_impressions,gsc_clicks,gsc_ctr_pct,pageviews,sessions,organic_sessions,ai_sessions,organic_session_share_pct,ai_session_share_pct,impressions_per_content
0,2025-01-01,1297,2,476,13853.0,108.0,0.779615,0.0,0.0,0.0,0.0,NaN,NaN,29.102941
1,2025-02-01,75985,3,5903,1195015.0,7823.0,0.654636,0.0,0.0,0.0,0.0,NaN,NaN,202.441979
2,2025-03-01,167859,4,10374,3847103.0,26138.0,0.679420,0.0,0.0,0.0,0.0,NaN,NaN,370.840852
3,2025-04-01,285114,4,13046,8843940.0,52974.0,0.598986,0.0,0.0,0.0,0.0,NaN,NaN,677.904338
4,2025-05-01,349923,4,14887,14454515.0,70374.0,0.486865,0.0,0.0,0.0,0.0,NaN,NaN,970.948814
5,2025-06-01,329201,9,16399,16930659.0,70245.0,0.414898,0.0,0.0,0.0,0.0,NaN,NaN,1032.420209
6,2025-07-01,469794,16,27945,20298448.0,84676.0,0.417155,0.0,0.0,0.0,0.0,NaN,NaN,726.371372
7,2025-08-01,704962,15,37204,29289942.0,119373.0,0.407556,0.0,0.0,0.0,0.0,NaN,NaN,787.279379
8,2025-09-01,845813,23,53127,37726329.0,176130.0,0.466862,0.0,0.0,0.0,0.0,NaN,NaN,710.115930
9,2025-10-01,2165471,31,110339,55073098.0,274631.0,0.498666,35809.0,22210.0,34009.0,422.0,153.124719,1.900045,499.126311
10,2025-11-01,6793825,43,251384,83871948.0,341306.0,0.406937,332735.0,229925.0,285340.0,3670.0,124.101337,1.596173,333.640757
11,2025-12-01,7752930,43,254621,112406941.0,359302.0,0.319644,311656.0,208197.0,235893.0,3779.0,113.302785,1.815108,441.467675
12,2026-01-01,7890817,42,261984,144354689.0,476140.0,0.329840,355665.0,219449.0,268574.0,4766.0,122.385611,2.171803,551.005745
13,2026-02-01,7355108,54,321546,180128922.0,586205.0,0.325436,527677.0,345261.0,287257.0,5793.0,83.199956,1.677861,560.196432
14,2026-03-01,9841378,55,331437,280657589.0,821832.0,0.292824,1484856.0,1299808.0,585408.0,8911.0,45.038036,0.685563,846.790156
15,2026-04-01,10424730,61,362172,292067218.0,840207.0,0.287676,1517002.0,1081806.0,883707.0,12273.0,81.688122,1.134492,806.432353
16,2026-05-01,11687376,66,389153,266164899.0,924256.0,0.347249,3218281.0,2146646.0,1034385.0,11242.0,48.186101,0.523701,683.959520
17,2026-06-01,11694072,65,409205,216194872.0,1209117.0,0.559272,4861097.0,2759763.0,1598823.0,32762.0,57.933344,1.187131,528.329009

In [ ]:
traffic_check = con.execute("""
    SELECT
        DATE_TRUNC('month', report_date) AS month,

        SUM(COALESCE(ga4_sessions, 0)) AS total_sessions,

        SUM(COALESCE(sessions_organic, 0)) AS organic_sessions,
        SUM(COALESCE(sessions_direct, 0)) AS direct_sessions,
        SUM(COALESCE(sessions_referral, 0)) AS referral_sessions,
        SUM(COALESCE(sessions_social, 0)) AS social_sessions,
        SUM(COALESCE(sessions_paid, 0)) AS paid_sessions,
        SUM(COALESCE(sessions_ai, 0)) AS ai_sessions,

        SUM(
            COALESCE(sessions_organic, 0)
            + COALESCE(sessions_direct, 0)
            + COALESCE(sessions_referral, 0)
            + COALESCE(sessions_social, 0)
            + COALESCE(sessions_paid, 0)
            + COALESCE(sessions_ai, 0)
        ) AS channel_sessions

    FROM fact_daily

    GROUP BY 1
    ORDER BY 1
""").df()

traffic_check

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,month,total_sessions,organic_sessions,direct_sessions,referral_sessions,social_sessions,paid_sessions,ai_sessions,channel_sessions
0,2025-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2025-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2025-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2025-04-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2025-05-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2025-06-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2025-07-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2025-08-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2025-09-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2025-10-01,22210.0,34009.0,1895.0,811.0,60.0,114.0,422.0,37311.0
10,2025-11-01,229925.0,285340.0,47332.0,4518.0,473.0,993.0,3670.0,342326.0
11,2025-12-01,208197.0,235893.0,41499.0,4534.0,315.0,17016.0,3779.0,303036.0
12,2026-01-01,219449.0,268574.0,44227.0,6004.0,449.0,5663.0,4766.0,329683.0
13,2026-02-01,345261.0,287257.0,61950.0,7371.0,615.0,8397.0,5793.0,371383.0
14,2026-03-01,1299808.0,585408.0,188954.0,11357.0,1066.0,30145.0,8911.0,825841.0
15,2026-04-01,1081806.0,883707.0,225325.0,21537.0,1443.0,194474.0,12273.0,1338759.0
16,2026-05-01,2146646.0,1034385.0,219044.0,21413.0,2173.0,257929.0,11242.0,1546186.0
17,2026-06-01,2759763.0,1598823.0,1205191.0,184150.0,142692.0,606909.0,32762.0,3770527.0

In [ ]:
traffic_check["difference"] = (
    traffic_check["total_sessions"]
    - traffic_check["channel_sessions"]
)

traffic_check["channel_coverage_pct"] = (
    traffic_check["channel_sessions"]
    / traffic_check["total_sessions"]
    * 100
).where(
    traffic_check["total_sessions"] > 0
)

traffic_check

,month,total_sessions,organic_sessions,direct_sessions,referral_sessions,social_sessions,paid_sessions,ai_sessions,channel_sessions,difference,channel_coverage_pct
0,2025-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,2025-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,2025-03-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,2025-04-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,2025-05-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
5,2025-06-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
6,2025-07-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
7,2025-08-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
8,2025-09-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
9,2025-10-01,22210.0,34009.0,1895.0,811.0,60.0,114.0,422.0,37311.0,-15101.0,167.991896
10,2025-11-01,229925.0,285340.0,47332.0,4518.0,473.0,993.0,3670.0,342326.0,-112401.0,148.885941
11,2025-12-01,208197.0,235893.0,41499.0,4534.0,315.0,17016.0,3779.0,303036.0,-94839.0,145.552530
12,2026-01-01,219449.0,268574.0,44227.0,6004.0,449.0,5663.0,4766.0,329683.0,-110234.0,150.232172
13,2026-02-01,345261.0,287257.0,61950.0,7371.0,615.0,8397.0,5793.0,371383.0,-26122.0,107.565870
14,2026-03-01,1299808.0,585408.0,188954.0,11357.0,1066.0,30145.0,8911.0,825841.0,473967.0,63.535614
15,2026-04-01,1081806.0,883707.0,225325.0,21537.0,1443.0,194474.0,12273.0,1338759.0,-256953.0,123.752225
16,2026-05-01,2146646.0,1034385.0,219044.0,21413.0,2173.0,257929.0,11242.0,1546186.0,600460.0,72.027992
17,2026-06-01,2759763.0,1598823.0,1205191.0,184150.0,142692.0,606909.0,32762.0,3770527.0,-1010764.0,136.625029

In [ ]:
print("Traffic / session related columns:")

schema[
    schema["column_name"].str.contains(
        "session|page|view|traffic|organic|ai|click|impression",
        case=False,
        regex=True
    )
]

Traffic / session related columns:

             column_name column_type null   key default extra
5     gsc_data_available     BOOLEAN  YES  None    None  None
6     ga4_data_available     BOOLEAN  YES  None    None  None
7        gsc_impressions      BIGINT  YES  None    None  None
8             gsc_clicks      BIGINT  YES  None    None  None
11         ga4_pageviews      BIGINT  YES  None    None  None
12          ga4_sessions      BIGINT  YES  None    None  None
14  ga4_engaged_sessions      BIGINT  YES  None    None  None
16      sessions_organic      BIGINT  YES  None    None  None
17       sessions_direct      BIGINT  YES  None    None  None
18     sessions_referral      BIGINT  YES  None    None  None
19       sessions_social      BIGINT  YES  None    None  None
20         sessions_paid      BIGINT  YES  None    None  None
21           sessions_ai      BIGINT  YES  None    None  None
22            ai_chatgpt      BIGINT  YES  None    None  None
23         ai_perplexity      BIGINT  YES  None    None  None
24             ai_gemini      BIGINT  YES  None    None  None
25            ai_copilot      BIGINT  YES  None    None  None
26             ai_claude      BIGINT  YES  None    None  None
27               ai_meta      BIGINT  YES  None    None  None
28              ai_other      BIGINT  YES  None    None  None

In [ ]:
print("Building content performance table...")

content_performance = con.execute("""
    SELECT
        fd.client_hash_id,
        fd.content_hash_id,

        MIN(fd.report_date) AS first_date,
        MAX(fd.report_date) AS last_date,

        COUNT(*) AS observed_days,

        -- GSC performance
        SUM(COALESCE(fd.gsc_impressions, 0)) AS total_gsc_impressions,
        SUM(COALESCE(fd.gsc_clicks, 0)) AS total_gsc_clicks,

        -- GA4 performance
        SUM(COALESCE(fd.ga4_pageviews, 0)) AS total_pageviews,
        SUM(COALESCE(fd.ga4_sessions, 0)) AS total_sessions,
        SUM(COALESCE(fd.ga4_users, 0)) AS total_users,
        SUM(COALESCE(fd.ga4_engaged_sessions, 0)) AS total_engaged_sessions,

        -- Traffic channels
        SUM(COALESCE(fd.sessions_organic, 0)) AS total_organic_sessions,
        SUM(COALESCE(fd.sessions_direct, 0)) AS total_direct_sessions,
        SUM(COALESCE(fd.sessions_referral, 0)) AS total_referral_sessions,
        SUM(COALESCE(fd.sessions_social, 0)) AS total_social_sessions,
        SUM(COALESCE(fd.sessions_paid, 0)) AS total_paid_sessions,
        SUM(COALESCE(fd.sessions_ai, 0)) AS total_ai_sessions,

        -- AI sources
        SUM(COALESCE(fd.ai_chatgpt, 0)) AS total_chatgpt_sessions,
        SUM(COALESCE(fd.ai_perplexity, 0)) AS total_perplexity_sessions,
        SUM(COALESCE(fd.ai_gemini, 0)) AS total_gemini_sessions,
        SUM(COALESCE(fd.ai_copilot, 0)) AS total_copilot_sessions,
        SUM(COALESCE(fd.ai_claude, 0)) AS total_claude_sessions,
        SUM(COALESCE(fd.ai_meta, 0)) AS total_meta_sessions,
        SUM(COALESCE(fd.ai_other, 0)) AS total_other_ai_sessions,

        -- Engagement
        SUM(COALESCE(fd.scroll_events, 0)) AS total_scroll_events,

        -- Average search position
        AVG(
            CASE
                WHEN fd.gsc_data_available = TRUE
                THEN fd.gsc_avg_position
                ELSE NULL
            END
        ) AS avg_gsc_position,

        -- Derived GSC CTR
        CASE
            WHEN SUM(COALESCE(fd.gsc_impressions, 0)) > 0
            THEN
                100.0
                * SUM(COALESCE(fd.gsc_clicks, 0))
                / SUM(COALESCE(fd.gsc_impressions, 0))
            ELSE NULL
        END AS gsc_ctr_pct,

        -- Organic share of GA4 sessions
        CASE
            WHEN SUM(COALESCE(fd.ga4_sessions, 0)) > 0
            THEN
                100.0
                * SUM(COALESCE(fd.sessions_organic, 0))
                / SUM(COALESCE(fd.ga4_sessions, 0))
            ELSE NULL
        END AS organic_session_share_pct,

        -- AI share of GA4 sessions
        CASE
            WHEN SUM(COALESCE(fd.ga4_sessions, 0)) > 0
            THEN
                100.0
                * SUM(COALESCE(fd.sessions_ai, 0))
                / SUM(COALESCE(fd.ga4_sessions, 0))
            ELSE NULL
        END AS ai_session_share_pct,

        -- Average daily impressions
        CASE
            WHEN COUNT(*) > 0
            THEN
                1.0 * SUM(COALESCE(fd.gsc_impressions, 0))
                / COUNT(*)
            ELSE NULL
        END AS avg_daily_impressions

    FROM fact_daily fd

    GROUP BY
        fd.client_hash_id,
        fd.content_hash_id

    HAVING COUNT(*) >= 30

    ORDER BY
        total_gsc_impressions DESC
""").fetchdf()

print("Content performance rows:", len(content_performance))

Building content performance table...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Content performance rows: 407872

In [ ]:
print("Inspecting rows with channel traffic but zero total sessions...")

zero_session_channels = con.execute("""
    SELECT
        client_hash_id,
        content_hash_id,
        observed_days,

        total_sessions,

        total_organic_sessions,
        total_direct_sessions,
        total_referral_sessions,
        total_social_sessions,
        total_paid_sessions,
        total_ai_sessions,

        total_pageviews,
        total_users,
        total_gsc_impressions,
        total_gsc_clicks

    FROM content_performance

    WHERE total_sessions = 0
      AND (
            total_organic_sessions
          + total_direct_sessions
          + total_referral_sessions
          + total_social_sessions
          + total_paid_sessions
          + total_ai_sessions
          ) > 0

    ORDER BY
        (
            total_organic_sessions
          + total_direct_sessions
          + total_referral_sessions
          + total_social_sessions
          + total_paid_sessions
          + total_ai_sessions
        ) DESC
""").df()

zero_session_channels

Inspecting rows with channel traffic but zero total sessions...

,client_hash_id,content_hash_id,observed_days,total_sessions,total_organic_sessions,total_direct_sessions,total_referral_sessions,total_social_sessions,total_paid_sessions,total_ai_sessions,total_pageviews,total_users,total_gsc_impressions,total_gsc_clicks
0,client_86ebc2f12c01f586,content_7e4514f20010c52d,36,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,369.0,0.0
1,client_f623b01661d4bfe4,content_8a3a09215b01898e,233,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,304.0,0.0
2,client_9c26c096d6e57253,content_9f0457cad4b49b2e,69,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,28.0,0.0

In [ ]:
print("Auditing performance coverage for published-active content...")

published_perf = con.execute("""
    SELECT
        COUNT(*) AS total_published_active,

        SUM(CASE
            WHEN total_gsc_impressions > 0
              OR total_pageviews > 0
              OR total_sessions > 0
            THEN 1 ELSE 0
        END) AS any_performance,

        SUM(CASE
            WHEN total_gsc_impressions > 0
            THEN 1 ELSE 0
        END) AS has_gsc,

        SUM(CASE
            WHEN total_pageviews > 0
            THEN 1 ELSE 0
        END) AS has_pageviews,

        SUM(CASE
            WHEN total_sessions > 0
            THEN 1 ELSE 0
        END) AS has_sessions,

        SUM(CASE
            WHEN total_gsc_impressions = 0
             AND total_pageviews = 0
             AND total_sessions = 0
            THEN 1 ELSE 0
        END) AS no_performance

    FROM content_performance cp
    INNER JOIN dim_content dc
        ON cp.client_hash_id = dc.client_hash_id
       AND cp.content_hash_id = dc.content_hash_id

    WHERE dc.is_published = TRUE
      AND dc.is_deleted = FALSE
""").df()

published_perf

Auditing performance coverage for published-active content...

,total_published_active,any_performance,has_gsc,has_pageviews,has_sessions,no_performance
0,383695,307787.0,284731.0,190195.0,190182.0,75908.0

In [ ]:
print("Auditing observation coverage for measurable published content...")

observation_coverage = con.execute("""
    SELECT
        CASE
            WHEN cp.observed_days < 60 THEN '<60 days'
            WHEN cp.observed_days < 120 THEN '60-119 days'
            WHEN cp.observed_days < 180 THEN '120-179 days'
            WHEN cp.observed_days < 240 THEN '180-239 days'
            ELSE '240+ days'
        END AS observation_bucket,

        COUNT(*) AS content_items,

        SUM(CASE
            WHEN cp.total_gsc_impressions > 0
              OR cp.total_pageviews > 0
              OR cp.total_sessions > 0
            THEN 1 ELSE 0
        END) AS measurable_items,

        ROUND(
            100.0 *
            SUM(CASE
                WHEN cp.total_gsc_impressions > 0
                  OR cp.total_pageviews > 0
                  OR cp.total_sessions > 0
                THEN 1 ELSE 0
            END)
            / COUNT(*),
            2
        ) AS measurable_pct,

        ROUND(AVG(cp.total_gsc_impressions), 2) AS avg_gsc_impressions,

        ROUND(AVG(cp.total_sessions), 2) AS avg_sessions

    FROM content_performance cp

    INNER JOIN dim_content dc
        ON cp.client_hash_id = dc.client_hash_id
       AND cp.content_hash_id = dc.content_hash_id

    WHERE dc.is_published = TRUE
      AND dc.is_deleted = FALSE

    GROUP BY observation_bucket

    ORDER BY
        CASE observation_bucket
            WHEN '<60 days' THEN 1
            WHEN '60-119 days' THEN 2
            WHEN '120-179 days' THEN 3
            WHEN '180-239 days' THEN 4
            WHEN '240+ days' THEN 5
        END
""").df()

observation_coverage

Auditing observation coverage for measurable published content...

,observation_bucket,content_items,measurable_items,measurable_pct,avg_gsc_impressions,avg_sessions
0,<60 days,25397,21770.0,85.72,946.76,5.02
1,60-119 days,58073,55722.0,95.95,1813.71,10.08
2,120-179 days,71134,58798.0,82.66,4198.38,22.99
3,180-239 days,120772,69972.0,57.94,1362.83,2.10
4,240+ days,108319,101525.0,93.73,10746.29,36.89

In [ ]:
print("Auditing normalized performance distribution...")

normalized_perf = con.execute("""
    SELECT
        COUNT(*) AS measurable_content,

        ROUND(MIN(observed_days), 2) AS min_observed_days,
        ROUND(AVG(observed_days), 2) AS avg_observed_days,
        ROUND(MEDIAN(observed_days), 2) AS median_observed_days,
        ROUND(MAX(observed_days), 2) AS max_observed_days,

        ROUND(MIN(avg_daily_impressions), 4) AS min_daily_impressions,
        ROUND(MEDIAN(avg_daily_impressions), 4) AS median_daily_impressions,
        ROUND(AVG(avg_daily_impressions), 4) AS avg_daily_impressions,
        ROUND(MAX(avg_daily_impressions), 4) AS max_daily_impressions,

        ROUND(MEDIAN(total_gsc_impressions), 2) AS median_total_impressions,
        ROUND(AVG(total_gsc_impressions), 2) AS avg_total_impressions

    FROM content_performance

    WHERE (
            total_gsc_impressions > 0
         OR total_pageviews > 0
         OR total_sessions > 0
    )
""").df()

normalized_perf

Auditing normalized performance distribution...

,measurable_content,min_observed_days,avg_observed_days,median_observed_days,max_observed_days,min_daily_impressions,median_daily_impressions,avg_daily_impressions,max_daily_impressions,median_total_impressions,avg_total_impressions
0,325032,30,190.75,218.0,520,0.0,1.1875,25.6625,11121.1341,170.0,5416.8

In [ ]:
print("Comparing content performance signals...")

performance_signals = con.execute("""
    SELECT
        COUNT(*) AS measurable_content,

        ROUND(MEDIAN(total_gsc_impressions), 2) AS median_impressions,
        ROUND(MEDIAN(total_gsc_clicks), 2) AS median_clicks,
        ROUND(MEDIAN(total_sessions), 2) AS median_sessions,
        ROUND(MEDIAN(total_organic_sessions), 2) AS median_organic_sessions,
        ROUND(MEDIAN(total_ai_sessions), 2) AS median_ai_sessions,
        ROUND(MEDIAN(total_pageviews), 2) AS median_pageviews,

        ROUND(AVG(total_gsc_impressions), 2) AS avg_impressions,
        ROUND(AVG(total_gsc_clicks), 2) AS avg_clicks,
        ROUND(AVG(total_sessions), 2) AS avg_sessions,
        ROUND(AVG(total_organic_sessions), 2) AS avg_organic_sessions,
        ROUND(AVG(total_ai_sessions), 2) AS avg_ai_sessions,
        ROUND(AVG(total_pageviews), 2) AS avg_pageviews,

        ROUND(
            CORR(total_gsc_impressions, total_gsc_clicks),
            4
        ) AS impressions_clicks_corr,

        ROUND(
            CORR(total_sessions, total_organic_sessions),
            4
        ) AS sessions_organic_corr,

        ROUND(
            CORR(total_sessions, total_ai_sessions),
            4
        ) AS sessions_ai_corr

    FROM content_performance

    WHERE total_gsc_impressions > 0
       OR total_gsc_clicks > 0
       OR total_sessions > 0
       OR total_pageviews > 0
""").df()

performance_signals

Comparing content performance signals...

,measurable_content,median_impressions,median_clicks,median_sessions,median_organic_sessions,median_ai_sessions,median_pageviews,avg_impressions,avg_clicks,avg_sessions,avg_organic_sessions,avg_ai_sessions,avg_pageviews,impressions_clicks_corr,sessions_organic_corr,sessions_ai_corr
0,325032,170.0,0.0,2.0,0.0,0.0,2.0,5416.8,19.33,24.77,15.66,0.25,36.6,0.3465,0.823,0.4537

In [ ]:
print("Auditing historical-to-future prediction eligibility...")

prediction_eligibility = con.execute("""
    WITH content_dates AS (
        SELECT
            client_hash_id,
            content_hash_id,
            MIN(report_date) AS first_date,
            MAX(report_date) AS last_date
        FROM fact_daily
        GROUP BY
            client_hash_id,
            content_hash_id
    )

    SELECT
        COUNT(*) AS total_content_items,

        SUM(
            CASE
                WHEN first_date <= DATE '2026-01-01'
                THEN 1 ELSE 0
            END
        ) AS has_90d_history_by_apr,

        SUM(
            CASE
                WHEN first_date <= DATE '2026-01-01'
                 AND last_date >= DATE '2026-06-30'
                THEN 1 ELSE 0
            END
        ) AS has_history_and_future,

        MIN(first_date) AS earliest_content,
        MAX(last_date) AS latest_content

    FROM content_dates
""").df()

prediction_eligibility

Auditing historical-to-future prediction eligibility...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,total_content_items,has_90d_history_by_apr,has_history_and_future,earliest_content,latest_content
0,427292,255489.0,190911.0,2025-01-27,2026-06-30

In [ ]:
print("Auditing daily observation continuity...")

continuity_audit = con.execute("""
    WITH content_dates AS (
        SELECT
            client_hash_id,
            content_hash_id,
            MIN(report_date) AS first_date,
            MAX(report_date) AS last_date,
            COUNT(DISTINCT report_date) AS observed_days
        FROM fact_daily
        WHERE report_date BETWEEN DATE '2026-01-02'
                              AND DATE '2026-05-01'
        GROUP BY
            client_hash_id,
            content_hash_id
    )

    SELECT
        COUNT(*) AS content_items,

        MIN(observed_days) AS min_observed_days,
        quantile_cont(observed_days, 0.25) AS p25_observed_days,
        quantile_cont(observed_days, 0.50) AS median_observed_days,
        quantile_cont(observed_days, 0.75) AS p75_observed_days,
        MAX(observed_days) AS max_observed_days,

        SUM(
            CASE WHEN observed_days >= 90
            THEN 1 ELSE 0 END
        ) AS observed_90_days,

        SUM(
            CASE WHEN observed_days >= 90
            THEN 1 ELSE 0 END
        ) * 100.0 / COUNT(*) AS observed_90_days_pct

    FROM content_dates
""").df()

continuity_audit

Auditing daily observation continuity...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,content_items,min_observed_days,p25_observed_days,median_observed_days,p75_observed_days,max_observed_days,observed_90_days,observed_90_days_pct
0,381610,1,72.0,120.0,120.0,120,243299.0,63.755929

In [ ]:
print("Auditing final modeling population...")

final_population = con.execute("""
    WITH history AS (
        SELECT
            client_hash_id,
            content_hash_id,
            COUNT(DISTINCT report_date) AS historical_observed_days
        FROM fact_daily
        WHERE report_date BETWEEN DATE '2026-01-02'
                              AND DATE '2026-04-01'
        GROUP BY
            client_hash_id,
            content_hash_id
    ),

    future AS (
        SELECT
            client_hash_id,
            content_hash_id,
            COUNT(DISTINCT report_date) AS future_observed_days
        FROM fact_daily
        WHERE report_date BETWEEN DATE '2026-04-02'
                              AND DATE '2026-05-01'
        GROUP BY
            client_hash_id,
            content_hash_id
    ),

    population AS (
        SELECT
            h.client_hash_id,
            h.content_hash_id,
            h.historical_observed_days,
            COALESCE(f.future_observed_days, 0) AS future_observed_days,

            c.is_published,
            c.is_deleted

        FROM history h

        LEFT JOIN future f
            ON h.client_hash_id = f.client_hash_id
           AND h.content_hash_id = f.content_hash_id

        INNER JOIN dim_content c
            ON h.client_hash_id = c.client_hash_id
           AND h.content_hash_id = c.content_hash_id
    )

    SELECT
        COUNT(*) AS history_items,

        SUM(
            CASE
                WHEN historical_observed_days >= 90
                THEN 1 ELSE 0
            END
        ) AS history_90d,

        SUM(
            CASE
                WHEN historical_observed_days >= 90
                 AND future_observed_days >= 30
                THEN 1 ELSE 0
            END
        ) AS history_90d_future_30d,

        SUM(
            CASE
                WHEN historical_observed_days >= 90
                 AND future_observed_days >= 30
                 AND is_published = TRUE
                 AND is_deleted = FALSE
                THEN 1 ELSE 0
            END
        ) AS final_published_population,

        SUM(
            CASE
                WHEN historical_observed_days >= 90
                 AND future_observed_days >= 30
                 AND is_published = TRUE
                 AND is_deleted = FALSE
                THEN 1 ELSE 0
            END
        ) * 100.0 / COUNT(*) AS final_population_pct

    FROM population
""").df()

final_population

Auditing final modeling population...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,history_items,history_90d,history_90d_future_30d,final_published_population,final_population_pct
0,349463,200149.0,200149.0,193918.0,55.490281

In [ ]:
print("Checking final population by client...")

client_population = con.execute("""
    WITH history AS (
        SELECT
            client_hash_id,
            content_hash_id,
            COUNT(DISTINCT report_date) AS historical_days
        FROM fact_daily
        WHERE report_date BETWEEN DATE '2026-01-02'
                              AND DATE '2026-04-01'
        GROUP BY
            client_hash_id,
            content_hash_id
    ),

    future AS (
        SELECT
            client_hash_id,
            content_hash_id,
            COUNT(DISTINCT report_date) AS future_days
        FROM fact_daily
        WHERE report_date BETWEEN DATE '2026-04-02'
                              AND DATE '2026-05-01'
        GROUP BY
            client_hash_id,
            content_hash_id
    )

    SELECT
        h.client_hash_id,

        COUNT(*) AS history_items,

        SUM(
            CASE
                WHEN h.historical_days >= 90
                 AND COALESCE(f.future_days, 0) >= 30
                THEN 1 ELSE 0
            END
        ) AS eligible_items,

        ROUND(
            100.0 *
            SUM(
                CASE
                    WHEN h.historical_days >= 90
                     AND COALESCE(f.future_days, 0) >= 30
                    THEN 1 ELSE 0
                END
            ) / COUNT(*),
            2
        ) AS eligible_pct

    FROM history h

    LEFT JOIN future f
        ON h.client_hash_id = f.client_hash_id
       AND h.content_hash_id = f.content_hash_id

    GROUP BY h.client_hash_id
    ORDER BY eligible_items DESC
""").df()

client_population

Checking final population by client...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

             client_hash_id  history_items  eligible_items  eligible_pct
0   client_625b6439094e23e4          31887         31887.0        100.00
1   client_08a6a72ff48e62c0          28278         24933.0         88.17
2   client_73cda7b4e4f265ea          29333         24204.0         82.51
3   client_65de48885f4ef01b          13781         13653.0         99.07
4   client_ba65e80a1116ae41          13239         13235.0         99.97
5   client_62f4a7e64f5e0096          25356         10261.0         40.47
6   client_e547b89c05043229           9308          9308.0        100.00
7   client_fef1a8f436438636          11223          9002.0         80.21
8   client_23a62021009f63c4          14621          8945.0         61.18
9   client_3197e6291363b4db          10690          8690.0         81.29
10  client_19b89ee4fe3db6da           6871          6000.0         87.32
11  client_f623b01661d4bfe4           5878          5500.0         93.57
12  client_a60a11451483af1c           5457          5457.0        100.00
13  client_ff644d8251367cbb           4522          4522.0        100.00
14  client_cd12bcfd98942aa1           5663          3078.0         54.35
15  client_9958f0a7ae1df715           3076          3076.0        100.00
16  client_b10cb2997d0c7c86           4331          3034.0         70.05
17  client_795153d5b7850ccf           2539          2539.0        100.00
18  client_400c21c81c8b46ef           3791          2498.0         65.89
19  client_2094c6eb080311d5           6375          2319.0         36.38
20  client_2910fd937f0b4d9a           3016          1934.0         64.12
21  client_d211cb07b9059bab           1715          1715.0        100.00
22  client_a2eeb8899886adde           1220          1043.0         85.49
23  client_599043c0ff13edea            727           727.0        100.00
24  client_8dbf3abdf07569e0            575           575.0        100.00
25  client_08d2847f24cf89c1            399           399.0        100.00
26  client_8ae2bfb5aa1ffa1e            357           357.0        100.00
27  client_0797ff3a1fc9a6a5            260           260.0        100.00
28  client_770e8e5faa9cddfe            200           200.0        100.00
29  client_80ee5b7bd5f4eb89            196           196.0        100.00
30  client_0e1acc6cd57b0eba            147           147.0        100.00
31  client_764ae36a94e30a25            121           121.0        100.00
32  client_59256b0571e0c970            111           111.0        100.00
33  client_a1203ffecad62470             75            75.0        100.00
34  client_c182d11e4862a37d           1864            74.0          3.97
35  client_3ffa76342f366962          31114            60.0          0.19
36  client_2c32078d69f2cbad             11            11.0        100.00
37  client_def0955f7a377868           1190             3.0          0.25
38  client_2e65897d94f60220           5042             0.0          0.00
39  client_835f9123c933bc01           4006             0.0          0.00
40  client_1d09b519bdde7c7a           1782             0.0          0.00
41  client_861cdcccf8049915           7136             0.0          0.00
42  client_ccdd78843409c8c7            416             0.0          0.00
43  client_4a18d1793d92fb84           4329             0.0          0.00
44  client_a80fca3f171ed1de           7626             0.0          0.00
45  client_e5c2aa26a8598242           3530             0.0          0.00
46  client_b77d0d5f08f05e64           1143             0.0          0.00
47  client_f6f0cdf26d03d7bd             94             0.0          0.00
48  client_9d54435aabd95a6c           1020             0.0          0.00
49  client_0fa64a184f18a4a0           1766             0.0          0.00
50  client_2b4306c3ed003f01          12126             0.0          0.00
51  client_20259bd6705d81d4           4806             0.0          0.00
52  client_3f0ce4d44fe94f3d           6417             0.0          0.00
53  client_1a730cb2640a1abf           2541             0.0          0.00
54  client_157ffe4d4a595515           4789             0.0          0.00
55  client_86ebc2f12c01f586            554             0.0          0.00
56  client_7eafe750768f0ac2            379             0.0          0.00
57  client_810019792c9b8efc            280             0.0          0.00
58  client_e00b29e582949543            164             0.0          0.00

In [ ]:
print("Cross-checking target missingness against historical GA4 sessions...")

print(
    pd.crosstab(
        df["future_organic_sessions"].isna(),
        df["sessions_90d"].isna(),
        normalize="index"
    ).round(4)
)

Cross-checking target missingness against historical GA4 sessions...
sessions_90d              False   True
future_organic_sessions
False                    1.0000  0.0000
True                     0.2557  0.7443

In [ ]:
# ============================================================
# FLYRANK CAPSTONE — RESTORE CONNECTION
# ============================================================

import duckdb
import pandas as pd
import numpy as np
from huggingface_hub import login

print("=== RESTORING FLYRANK CONNECTION ===")

# Fresh DuckDB connection
con = duckdb.connect()

# Hugging Face authentication
HF_TOKEN = input("Paste your NEW Hugging Face READ token: ").strip()

login(
    token=HF_TOKEN,
    add_to_git_credential=False
)

# DuckDB Hugging Face secret
try:
    con.execute("DROP SECRET hf_secret")
except:
    pass

con.execute(f"""
CREATE SECRET hf_secret (
    TYPE huggingface,
    TOKEN '{HF_TOKEN}'
)
""")

print("Hugging Face authentication configured.")

# Actual FlyRank warehouse
HF_ROOT = "hf://datasets/FlyRank/internship-warehouse"

print("Warehouse:", HF_ROOT)

# ============================================================
# SOURCE VIEWS
# ============================================================

con.execute(f"""
CREATE OR REPLACE VIEW fact_daily AS
SELECT *
FROM read_parquet(
    '{HF_ROOT}/fact_content_daily_performance/**/*.parquet',
    hive_partitioning = true
)
""")

con.execute(f"""
CREATE OR REPLACE VIEW fact_query_90d AS
SELECT *
FROM read_parquet(
    '{HF_ROOT}/fact_content_query_90d.parquet'
)
""")

con.execute(f"""
CREATE OR REPLACE VIEW dim_content AS
SELECT *
FROM read_parquet(
    '{HF_ROOT}/dim_content.parquet'
)
""")

con.execute(f"""
CREATE OR REPLACE VIEW dim_clients AS
SELECT *
FROM read_parquet(
    '{HF_ROOT}/dim_clients.parquet'
)
""")

print("Source views created.")

# ============================================================
# QUICK CONNECTION TEST
# ============================================================

print("\n=== TESTING SOURCE VIEWS ===")

for name in [
    "fact_daily",
    "fact_query_90d",
    "dim_content",
    "dim_clients"
]:
    try:
        n = con.execute(
            f"SELECT COUNT(*) FROM {name}"
        ).fetchone()[0]

        print(f"{name:20s} OK -> {n:,} rows")

    except Exception as e:
        print(f"{name:20s} ERROR -> {e}")

print("\n=== CONNECTION READY ===")

=== RESTORING FLYRANK CONNECTION ===
Paste your NEW Hugging Face READ token: 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
Hugging Face authentication configured.
Warehouse: hf://datasets/FlyRank/internship-warehouse
Source views created.

=== TESTING SOURCE VIEWS ===

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

fact_daily           OK -> 78,835,655 rows
fact_query_90d       OK -> 2,414,248 rows
dim_content          OK -> 519,606 rows
dim_clients          OK -> 104 rows

=== CONNECTION READY ===

In [ ]:
print("=== FAST MODELING DATASET BUILD ===")

# ------------------------------------------------------------------
# Step 1/4: Aggregate daily performance
# ------------------------------------------------------------------
print("\nStep 1/4: Aggregating daily performance...")

con.execute("""
CREATE OR REPLACE TEMP TABLE daily_features AS
SELECT
    client_hash_id,
    content_hash_id,

    SUM(gsc_impressions) AS impressions,
    SUM(gsc_clicks) AS clicks,

    AVG(gsc_avg_position) AS avg_position,

    SUM(ga4_pageviews) AS pageviews,
    SUM(ga4_sessions) AS sessions,
    SUM(ga4_users) AS users,

    SUM(sessions_organic) AS sessions_organic,
    SUM(sessions_direct) AS sessions_direct,
    SUM(sessions_referral) AS sessions_referral,
    SUM(sessions_social) AS sessions_social,
    SUM(sessions_paid) AS sessions_paid,
    SUM(sessions_ai) AS sessions_ai,

    SUM(ai_chatgpt) AS ai_chatgpt,
    SUM(ai_perplexity) AS ai_perplexity,
    SUM(ai_gemini) AS ai_gemini,
    SUM(ai_copilot) AS ai_copilot,
    SUM(ai_claude) AS ai_claude,
    SUM(ai_meta) AS ai_meta,
    SUM(ai_other) AS ai_other,

    SUM(scroll_events) AS scroll_events

FROM fact_daily
GROUP BY
    client_hash_id,
    content_hash_id
""")

print("Step 1 complete.")

# ------------------------------------------------------------------
# Step 2/4: Aggregate query-level performance
# ------------------------------------------------------------------
print("\nStep 2/4: Aggregating query performance...")

con.execute("""
CREATE OR REPLACE TEMP TABLE query_features AS
SELECT
    client_hash_id,
    content_hash_id,

    SUM(impressions_90d) AS impressions_90d,
    SUM(clicks_90d) AS clicks_90d,

    SUM(impressions_last30) AS impressions_last30,
    SUM(clicks_last30) AS clicks_last30,

    SUM(impressions_prev30) AS impressions_prev30,
    SUM(clicks_prev30) AS clicks_prev30,

    AVG(avg_position_90d) AS avg_position_90d,
    AVG(avg_position_last30) AS avg_position_last30,
    AVG(avg_position_prev30) AS avg_position_prev30,

    MAX(content_total_impressions_90d)
        AS content_total_impressions_90d,

    MAX(content_visible_query_count)
        AS content_visible_query_count,

    MAX(rare_query_count)
        AS rare_query_count,

    MAX(rare_impressions_share)
        AS rare_impressions_share,

    MAX(anonymized_impressions_share)
        AS anonymized_impressions_share

FROM fact_query_90d
GROUP BY
    client_hash_id,
    content_hash_id
""")

print("Step 2 complete.")

# ------------------------------------------------------------------
# Step 3/4: Join with content dimension
# ------------------------------------------------------------------
print("\nStep 3/4: Joining content features...")

con.execute("""
CREATE OR REPLACE TEMP TABLE modeling_raw AS
SELECT
    c.*,

    d.impressions,
    d.clicks,
    d.avg_position,
    d.pageviews,
    d.sessions,
    d.users,

    d.sessions_organic,
    d.sessions_direct,
    d.sessions_referral,
    d.sessions_social,
    d.sessions_paid,
    d.sessions_ai,

    d.ai_chatgpt,
    d.ai_perplexity,
    d.ai_gemini,
    d.ai_copilot,
    d.ai_claude,
    d.ai_meta,
    d.ai_other,

    d.scroll_events,

    q.impressions_90d,
    q.clicks_90d,
    q.impressions_last30,
    q.clicks_last30,
    q.impressions_prev30,
    q.clicks_prev30,

    q.avg_position_90d,
    q.avg_position_last30,
    q.avg_position_prev30,

    q.content_total_impressions_90d,
    q.content_visible_query_count,
    q.rare_query_count,
    q.rare_impressions_share,
    q.anonymized_impressions_share

FROM dim_content c

LEFT JOIN daily_features d
    ON c.client_hash_id = d.client_hash_id
    AND c.content_hash_id = d.content_hash_id

LEFT JOIN query_features q
    ON c.client_hash_id = q.client_hash_id
    AND c.content_hash_id = q.content_hash_id
""")

print("Step 3 complete.")

# ------------------------------------------------------------------
# Step 4/4: Basic modeling-ready filtering
# ------------------------------------------------------------------
print("\nStep 4/4: Creating modeling dataset...")

con.execute("""
CREATE OR REPLACE TEMP TABLE modeling_dataset AS
SELECT *
FROM modeling_raw
WHERE
    COALESCE(is_deleted, FALSE) = FALSE
""")

count = con.execute("""
SELECT COUNT(*)
FROM modeling_dataset
""").fetchone()[0]

print(f"Step 4 complete.")
print(f"Modeling dataset rows: {count:,}")

print("\n=== MODELING DATASET BUILD COMPLETE ===")

=== FAST MODELING DATASET BUILD ===

Step 1/4: Aggregating daily performance...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Step 1 complete.

Step 2/4: Aggregating query performance...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Step 2 complete.

Step 3/4: Joining content features...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Step 3 complete.

Step 4/4: Creating modeling dataset...
Step 4 complete.
Modeling dataset rows: 418,047

=== MODELING DATASET BUILD COMPLETE ===

In [ ]:
print("=== FLYRANK FUNNEL SANITY CHECK ===")

# 1. Daily performance coverage
print("\n[1/4] Daily performance coverage")

print(
    con.execute("""
        SELECT
            MIN(report_date) AS min_date,
            MAX(report_date) AS max_date,
            COUNT(*) AS rows,
            COUNT(DISTINCT client_hash_id) AS clients,
            COUNT(DISTINCT content_hash_id) AS contents
        FROM fact_daily
    """).df()
)

# 2. Content coverage
print("\n[2/4] Content dimension coverage")

print(
    con.execute("""
        SELECT
            COUNT(*) AS rows,
            COUNT(DISTINCT client_hash_id) AS clients,
            COUNT(DISTINCT content_hash_id) AS contents,
            SUM(CASE WHEN is_published THEN 1 ELSE 0 END) AS published,
            SUM(CASE WHEN is_deleted THEN 1 ELSE 0 END) AS deleted
        FROM dim_content
    """).df()
)

# 3. Query coverage
print("\n[3/4] Query performance coverage")

print(
    con.execute("""
        SELECT
            MIN(window_start) AS min_window_start,
            MAX(window_end) AS max_window_end,
            COUNT(*) AS rows,
            COUNT(DISTINCT client_hash_id) AS clients,
            COUNT(DISTINCT content_hash_id) AS contents,
            SUM(impressions_90d) AS total_impressions_90d,
            SUM(clicks_90d) AS total_clicks_90d
        FROM fact_query_90d
    """).df()
)

# 4. Join coverage
print("\n[4/4] Join coverage")

print(
    con.execute("""
        SELECT
            COUNT(*) AS query_rows,
            COUNT(c.content_hash_id) AS matched_content,
            COUNT(d.client_hash_id) AS matched_client
        FROM fact_query_90d q
        LEFT JOIN dim_content c
            ON q.content_hash_id = c.content_hash_id
        LEFT JOIN dim_clients d
            ON q.client_hash_id = d.client_hash_id
    """).df()
)

print("\n=== FUNNEL SANITY CHECK COMPLETE ===")

=== FLYRANK FUNNEL SANITY CHECK ===

[1/4] Daily performance coverage

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    min_date   max_date      rows  clients  contents
0 2025-01-27 2026-06-30  78835655       70    427292

[2/4] Content dimension coverage
     rows  clients  contents  published   deleted
0  519606       84    519606   411540.0  101559.0

[3/4] Query performance coverage

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

  min_window_start max_window_end     rows  clients  contents  \
0       2026-04-02     2026-06-30  2414248       52    133852

   total_impressions_90d  total_clicks_90d
0            211743016.0          459918.0

[4/4] Join coverage
   query_rows  matched_content  matched_client
0     2414248          2414248         2414248

=== FUNNEL SANITY CHECK COMPLETE ===

In [ ]:
# ============================================================
# FLYRANK CAPSTONE
# FINAL LEAKAGE-SAFE MODELING DATASET
# ============================================================

print("=== BUILDING LEAKAGE-SAFE MODELING DATASET ===")

CUTOFF = pd.Timestamp("2026-04-01")

print(f"Prediction cutoff: {CUTOFF.date()}")

# ------------------------------------------------------------
# STEP 1
# Build historical features + future target in ONE scan
# ------------------------------------------------------------

print("\nStep 1/3: Building prediction-time daily features...")

con.execute("""
CREATE OR REPLACE TEMP TABLE prediction_daily AS

SELECT
    client_hash_id,
    content_hash_id,

    -- ========================================================
    -- HISTORICAL FEATURES
    -- ONLY DATA STRICTLY BEFORE 2026-04-01
    -- ========================================================

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(gsc_impressions, 0)
            ELSE 0
        END
    ) AS gsc_impressions_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(gsc_clicks, 0)
            ELSE 0
        END
    ) AS gsc_clicks_hist,

    AVG(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN gsc_avg_position
        END
    ) AS avg_position_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(ga4_sessions, 0)
            ELSE 0
        END
    ) AS ga4_sessions_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(ga4_pageviews, 0)
            ELSE 0
        END
    ) AS ga4_pageviews_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(sessions_organic, 0)
            ELSE 0
        END
    ) AS organic_sessions_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(sessions_direct, 0)
            ELSE 0
        END
    ) AS direct_sessions_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(sessions_referral, 0)
            ELSE 0
        END
    ) AS referral_sessions_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(sessions_social, 0)
            ELSE 0
        END
    ) AS social_sessions_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(sessions_paid, 0)
            ELSE 0
        END
    ) AS paid_sessions_hist,

    SUM(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN COALESCE(sessions_ai, 0)
            ELSE 0
        END
    ) AS ai_sessions_hist,

    -- Data availability known at prediction time
    MAX(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN CAST(client_has_ga4 AS INTEGER)
            ELSE NULL
        END
    ) AS client_has_ga4,

    MAX(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN CAST(ga4_data_available AS INTEGER)
            ELSE NULL
        END
    ) AS ga4_data_available,

    MAX(
        CASE
            WHEN report_date < DATE '2026-04-01'
            THEN CAST(gsc_data_available AS INTEGER)
            ELSE NULL
        END
    ) AS gsc_data_available,

    -- ========================================================
    -- FUTURE TARGET
    -- 2026-04-01 through 2026-04-30
    --
    -- IMPORTANT:
    -- This is LABEL information only.
    -- It will NOT be used as a feature.
    -- ========================================================

    SUM(
        CASE
            WHEN report_date >= DATE '2026-04-01'
             AND report_date < DATE '2026-05-01'
            THEN COALESCE(sessions_organic, 0)
            ELSE 0
        END
    ) AS future_organic_sessions,

    COUNT(
        DISTINCT CASE
            WHEN report_date >= DATE '2026-04-01'
             AND report_date < DATE '2026-05-01'
            THEN report_date
        END
    ) AS future_observed_days

FROM fact_daily

WHERE
    report_date < DATE '2026-05-01'

GROUP BY
    client_hash_id,
    content_hash_id
""")

print("Step 1 complete.")

# ------------------------------------------------------------
# STEP 2
# Join prediction-time features to content metadata
# ------------------------------------------------------------

print("\nStep 2/3: Joining prediction-time features...")

modeling_raw = con.execute("""
SELECT

    -- --------------------------------------------------------
    -- IDENTIFIERS
    -- --------------------------------------------------------

    c.client_hash_id,
    c.content_hash_id,

    -- --------------------------------------------------------
    -- CONTENT / KEYWORD FEATURES
    -- --------------------------------------------------------

    c.keyword_char_count,
    c.keyword_token_count,
    c.url_char_count,

    c.content_created_date,
    c.content_updated_date,
    c.content_type,

    c.search_volume,
    c.competition,
    c.competition_level,
    c.cpc,
    c.main_intent,

    c.backlinks,
    c.category_count,

    c.keyword_created_date,
    c.provider_used,
    c.model_used,

    c.char_count,
    c.word_count,

    c.last_optimized_date,
    c.optimization_eligible_date,

    c.is_published,
    c.is_deleted,

    -- --------------------------------------------------------
    -- HISTORICAL PERFORMANCE FEATURES
    -- --------------------------------------------------------

    d.gsc_impressions_hist,
    d.gsc_clicks_hist,
    d.avg_position_hist,

    d.ga4_sessions_hist,
    d.ga4_pageviews_hist,

    d.organic_sessions_hist,
    d.direct_sessions_hist,
    d.referral_sessions_hist,
    d.social_sessions_hist,
    d.paid_sessions_hist,
    d.ai_sessions_hist,

    d.client_has_ga4,
    d.ga4_data_available,
    d.gsc_data_available,

    -- --------------------------------------------------------
    -- TARGET
    -- --------------------------------------------------------

    d.future_organic_sessions,
    d.future_observed_days

FROM dim_content c

LEFT JOIN prediction_daily d
    ON c.client_hash_id = d.client_hash_id
   AND c.content_hash_id = d.content_hash_id

WHERE
    COALESCE(c.is_deleted, FALSE) = FALSE

""").df()

print("Step 2 complete.")

# ------------------------------------------------------------
# STEP 3
# Sanity / leakage checks
# ------------------------------------------------------------

print("\nStep 3/3: Validating final modeling dataset...")

print("\nDataset shape:")
print(modeling_raw.shape)

print("\nTarget:")
print(
    modeling_raw["future_organic_sessions"]
    .describe()
)

print("\nTarget missing:")
print(
    modeling_raw["future_organic_sessions"].isna().sum()
)

print("\nFuture observed days:")
print(
    modeling_raw["future_observed_days"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nHistorical feature coverage:")

for col in [
    "gsc_impressions_hist",
    "gsc_clicks_hist",
    "avg_position_hist",
    "ga4_sessions_hist",
    "organic_sessions_hist"
]:
    print(
        f"{col:30s}",
        "non-null:",
        modeling_raw[col].notna().sum()
    )

print("\n=== LEAKAGE-SAFE MODELING DATASET READY ===")

=== BUILDING LEAKAGE-SAFE MODELING DATASET ===
Prediction cutoff: 2026-04-01

Step 1/3: Building prediction-time daily features...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Step 1 complete.

Step 2/3: Joining prediction-time features...
Step 2 complete.

Step 3/3: Validating final modeling dataset...

Dataset shape:
(418047, 40)

Target:
count    362629.000000
mean          2.435812
std          21.591408
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max        5119.000000
Name: future_organic_sessions, dtype: float64

Target missing:
55418

Future observed days:
future_observed_days
0         7150
1          854
2          671
3          686
4          760
5         1520
6          924
7          930
8         1517
9          923
10         913
11        1195
12         976
13         715
14         908
15        1015
16        1463
17        1552
18         213
19         461
20         153
21        1803
22        3774
23         615
24         102
25        1206
26        3361
27         248
28         327
29         696
30      324998
<NA>     55418
Name: count, dtype: Int64

Historical feature coverage:
gsc_impressions_hist           non-null: 362629
gsc_clicks_hist                non-null: 362629
avg_position_hist              non-null: 213908
ga4_sessions_hist              non-null: 362629
organic_sessions_hist          non-null: 362629

=== LEAKAGE-SAFE MODELING DATASET READY ===

In [ ]:
# ============================================================
# TARGET ELIGIBILITY & COVERAGE AUDIT
# ============================================================

print("=== TARGET ELIGIBILITY AUDIT ===")

# ------------------------------------------------------------
# 1. Coverage buckets
# ------------------------------------------------------------

print("\n[1/4] Future observation coverage")

coverage = (
    modeling_raw
    .assign(
        coverage_bucket=pd.cut(
            modeling_raw["future_observed_days"],
            bins=[-1, 0, 7, 14, 21, 29, 30],
            labels=[
                "0 days",
                "1-7 days",
                "8-14 days",
                "15-21 days",
                "22-29 days",
                "30 days"
            ]
        )
    )
    ["coverage_bucket"]
    .value_counts(dropna=False)
    .sort_index()
)

print(coverage)

# ------------------------------------------------------------
# 2. Target missing vs zero
# ------------------------------------------------------------

print("\n[2/4] Missing vs observed-zero target")

print(
    modeling_raw.groupby(
        modeling_raw["future_organic_sessions"].isna()
    )["future_organic_sessions"]
    .agg(["count", "min", "median", "mean", "max"])
)

print("\nObserved rows with target = 0:")

print(
    (
        modeling_raw["future_organic_sessions"].notna()
        & (modeling_raw["future_organic_sessions"] == 0)
    ).sum()
)

# ------------------------------------------------------------
# 3. Target by observation coverage
# ------------------------------------------------------------

print("\n[3/4] Target statistics by future observation days")

target_by_days = (
    modeling_raw
    .groupby("future_observed_days", dropna=False)
    ["future_organic_sessions"]
    .agg(
        rows="size",
        target_nonnull="count",
        target_mean="mean",
        target_median="median",
        target_max="max"
    )
    .reset_index()
)

display(target_by_days)

# ------------------------------------------------------------
# 4. Candidate modeling population
# ------------------------------------------------------------

print("\n[4/4] Candidate modeling population")

for days in [7, 14, 21, 22, 29, 30]:

    eligible = modeling_raw[
        modeling_raw["future_observed_days"] >= days
    ]

    print(
        f"At least {days:2d} observed days:"
        f" {len(eligible):,} rows"
    )

print("\n=== TARGET ELIGIBILITY AUDIT COMPLETE ===")

=== TARGET ELIGIBILITY AUDIT ===

[1/4] Future observation coverage
coverage_bucket
0 days          7150
1-7 days        6345
8-14 days       7147
15-21 days      6660
22-29 days     10329
30 days       324998
NaN            55418
Name: count, dtype: int64

[2/4] Missing vs observed-zero target
                          count  min  median      mean     max
future_organic_sessions
False                    362629  0.0     0.0  2.435812  5119.0
True                          0  NaN     NaN       NaN     NaN

Observed rows with target = 0:
313159

[3/4] Target statistics by future observation days

,future_observed_days,rows,target_nonnull,target_mean,target_median,target_max
0,0,7150,7150,0.000000,0.0,0.0
1,1,854,854,0.000000,0.0,0.0
2,2,671,671,0.000000,0.0,0.0
3,3,686,686,0.000000,0.0,0.0
4,4,760,760,0.000000,0.0,0.0
5,5,1520,1520,0.007237,0.0,3.0
6,6,924,924,0.141775,0.0,7.0
7,7,930,930,0.190323,0.0,16.0
8,8,1517,1517,0.753461,0.0,32.0
9,9,923,923,0.430119,0.0,40.0
10,10,913,913,0.749179,0.0,55.0
11,11,1195,1195,0.703766,0.0,56.0
12,12,976,976,0.989754,0.0,57.0
13,13,715,715,2.616783,0.0,48.0
14,14,908,908,0.534141,0.0,24.0
15,15,1015,1015,0.377340,0.0,72.0
16,16,1463,1463,0.303486,0.0,31.0
17,17,1552,1552,0.943299,0.0,140.0
18,18,213,213,1.835681,0.0,149.0
19,19,461,461,1.177874,0.0,202.0
20,20,153,153,1.405229,0.0,48.0
21,21,1803,1803,2.246811,0.0,224.0
22,22,3774,3774,0.825384,0.0,79.0
23,23,615,615,0.162602,0.0,33.0
24,24,102,102,0.401961,0.0,14.0
25,25,1206,1206,0.284411,0.0,24.0
26,26,3361,3361,1.854805,0.0,175.0
27,27,248,248,1.145161,0.0,62.0
28,28,327,327,1.192661,0.0,246.0
29,29,696,696,0.686782,0.0,73.0
30,30,324998,324998,2.640367,0.0,5119.0
31,<NA>,55418,0,NaN,NaN,NaN

[4/4] Candidate modeling population
At least  7 observed days: 350,064 rows
At least 14 observed days: 342,895 rows
At least 21 observed days: 337,130 rows
At least 22 observed days: 335,327 rows
At least 29 observed days: 325,694 rows
At least 30 observed days: 324,998 rows

=== TARGET ELIGIBILITY AUDIT COMPLETE ===

In [ ]:
# ============================================================
# FLYRANK CAPSTONE — FINAL MODELING POPULATION
# ============================================================

print("=== CREATING FINAL MODELING POPULATION ===")

# Keep only records with a complete 30-day future observation window.
# Target = organic sessions during 2026-04-01 through 2026-04-30.

modeling_dataset_final = modeling_raw[
    modeling_raw["future_observed_days"] == 30
].copy()

print(f"Final modeling rows: {len(modeling_dataset_final):,}")

# ------------------------------------------------------------
# Basic target checks
# ------------------------------------------------------------

target = modeling_dataset_final["future_organic_sessions"]

print("\nTarget summary:")
print(target.describe())

print("\nTarget missing:")
print(target.isna().sum())

print("\nTarget zero count:")
print((target == 0).sum())

print("\nTarget positive count:")
print((target > 0).sum())

print("\nTarget positive percentage:")
print(f"{(target > 0).mean() * 100:.2f}%")

# ------------------------------------------------------------
# Check that every selected row has exactly 30 days
# ------------------------------------------------------------

print("\nFuture observation days:")
print(
    modeling_dataset_final["future_observed_days"]
    .value_counts(dropna=False)
)

print("\n=== FINAL MODELING POPULATION READY ===")

=== CREATING FINAL MODELING POPULATION ===
Final modeling rows: 324,998

Target summary:
count    324998.000000
mean          2.640367
std          22.746358
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max        5119.000000
Name: future_organic_sessions, dtype: float64

Target missing:
0

Target zero count:
279154

Target positive count:
45844

Target positive percentage:
14.11%

Future observation days:
future_observed_days
30    324998
Name: count, dtype: Int64

=== FINAL MODELING POPULATION READY ===

In [ ]:
# ============================================================
# FLYRANK CAPSTONE — TARGET DISTRIBUTION AUDIT
# ============================================================

print("=== TARGET DISTRIBUTION AUDIT ===")

target = modeling_dataset_final["future_organic_sessions"]

# ------------------------------------------------------------
# 1. Key distribution statistics
# ------------------------------------------------------------

print("\n[1/4] Target quantiles")

quantiles = target.quantile([
    0.50,
    0.75,
    0.80,
    0.85,
    0.90,
    0.95,
    0.99,
    0.995,
    0.999
])

print(quantiles)

# ------------------------------------------------------------
# 2. Positive-target distribution
# ------------------------------------------------------------

print("\n[2/4] Positive-target distribution")

positive_target = target[target > 0]

print(positive_target.describe())

print("\nPositive-target quantiles:")

print(
    positive_target.quantile([
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99,
        0.999
    ])
)

# ------------------------------------------------------------
# 3. Target buckets
# ------------------------------------------------------------

print("\n[3/4] Target buckets")

target_buckets = pd.cut(
    target,
    bins=[-1, 0, 1, 5, 10, 25, 50, 100, 500, 1000, float("inf")],
    labels=[
        "0",
        "1",
        "2-5",
        "6-10",
        "11-25",
        "26-50",
        "51-100",
        "101-500",
        "501-1000",
        "1001+"
    ]
)

print(
    target_buckets
        .value_counts()
        .sort_index()
)

print("\nTarget bucket percentages:")

print(
    (target_buckets.value_counts(normalize=True)
        .sort_index() * 100)
        .round(2)
)

# ------------------------------------------------------------
# 4. Client-level target concentration
# ------------------------------------------------------------

print("\n[4/4] Target concentration by client")

client_target = (
    modeling_dataset_final
    .groupby("client_hash_id")["future_organic_sessions"]
    .agg(
        rows="size",
        total_future_sessions="sum",
        positive_rows=lambda x: (x > 0).sum()
    )
    .sort_values("total_future_sessions", ascending=False)
)

print("\nTop 10 clients by future organic sessions:")

print(client_target.head(10))

print("\nNumber of clients:")
print(client_target.shape[0])

print("\n=== TARGET DISTRIBUTION AUDIT COMPLETE ===")

=== TARGET DISTRIBUTION AUDIT ===

[1/4] Target quantiles
0.500      0.0
0.750      0.0
0.800      0.0
0.850      0.0
0.900      2.0
0.950      9.0
0.990     56.0
0.995     98.0
0.999    253.0
Name: future_organic_sessions, dtype: float64

[2/4] Positive-target distribution
count    45844.000000
mean        18.718131
std         58.026321
min          1.000000
25%          2.000000
50%          5.000000
75%         15.000000
max       5119.000000
Name: future_organic_sessions, dtype: float64

Positive-target quantiles:
0.250      2.000
0.500      5.000
0.750     15.000
0.900     42.000
0.950     75.000
0.990    214.000
0.999    684.471
Name: future_organic_sessions, dtype: float64

[3/4] Target buckets
future_organic_sessions
0           279154
1             8060
2-5          16103
6-10          6844
11-25         7309
26-50         3834
51-100        2116
101-500       1493
501-1000        68
1001+           17
Name: count, dtype: int64

Target bucket percentages:
future_organic_sessions
0           85.89
1            2.48
2-5          4.95
6-10         2.11
11-25        2.25
26-50        1.18
51-100       0.65
101-500      0.46
501-1000     0.02
1001+        0.01
Name: proportion, dtype: float64

[4/4] Target concentration by client

Top 10 clients by future organic sessions:
                          rows  total_future_sessions  positive_rows
client_hash_id
client_23a62021009f63c4  14617               274661.0           8902
client_73cda7b4e4f265ea  29323               256297.0          13418
client_20259bd6705d81d4   4804                91053.0           2878
client_e547b89c05043229   9300                67717.0           4752
client_e5c2aa26a8598242   3528                50958.0           2448
client_fef1a8f436438636  11210                40077.0           3483
client_2094c6eb080311d5   6375                14782.0           1328
client_1a730cb2640a1abf   2541                14109.0           1209
client_0fa64a184f18a4a0   1766                13413.0            669
client_3f0ce4d44fe94f3d   6397                 9941.0           1512

Number of clients:
53

=== TARGET DISTRIBUTION AUDIT COMPLETE ===

In [ ]:
# ============================================================
# FLYRANK CAPSTONE — FUTURE-DATED ROW QUARANTINE AUDIT
# ============================================================

print("=== FUTURE-DATED ROW QUARANTINE AUDIT ===")

df = modeling_dataset_final.copy()

CUTOFF = pd.Timestamp("2026-04-01")

content_created = pd.to_datetime(
    df["content_created_date"],
    errors="coerce"
)

keyword_created = pd.to_datetime(
    df["keyword_created_date"],
    errors="coerce"
)

# ------------------------------------------------------------
# 1. Identify future-dated rows
# ------------------------------------------------------------

content_future = content_created > CUTOFF
keyword_future = keyword_created > CUTOFF

either_future = content_future | keyword_future
both_future = content_future & keyword_future

print("\n[1/5] Future-dated row counts")

print(f"Content created after cutoff:  {content_future.sum():,}")
print(f"Keyword created after cutoff:  {keyword_future.sum():,}")
print(f"Either date after cutoff:      {either_future.sum():,}")
print(f"Both dates after cutoff:       {both_future.sum():,}")

# ------------------------------------------------------------
# 2. Target status of affected rows
# ------------------------------------------------------------

print("\n[2/5] Target status of future-dated rows")

target = df["future_organic_sessions"]

target_audit = pd.DataFrame({
    "content_created_future": content_future,
    "keyword_created_future": keyword_future,
    "target": target
})

print(
    target_audit[
        either_future
    ]["target"]
    .describe()
)

print("\nTarget missing:")
print(
    target_audit.loc[
        either_future, "target"
    ].isna().sum()
)

print("\nTarget zero:")
print(
    (
        target_audit.loc[
            either_future, "target"
        ] == 0
    ).sum()
)

print("\nTarget positive:")
print(
    (
        target_audit.loc[
            either_future, "target"
        ] > 0
    ).sum()
)

# ------------------------------------------------------------
# 3. Historical performance availability
# ------------------------------------------------------------

print("\n[3/5] Historical performance on future-dated rows")

historical_cols = [
    "gsc_impressions_hist",
    "gsc_clicks_hist",
    "avg_position_hist",
    "ga4_sessions_hist",
    "ga4_pageviews_hist",
    "organic_sessions_hist"
]

future_history = []

for col in historical_cols:

    s = df.loc[either_future, col]

    future_history.append({
        "feature": col,
        "rows": len(s),
        "non_null": s.notna().sum(),
        "zero": (s == 0).sum(),
        "positive": (s > 0).sum(),
        "median": s.median(),
        "max": s.max()
    })

future_history_df = pd.DataFrame(future_history)

print(
    future_history_df.to_string(index=False)
)

# ------------------------------------------------------------
# 4. Client distribution
# ------------------------------------------------------------

print("\n[4/5] Future-dated rows by client")

client_future = (
    df.loc[either_future]
      .groupby("client_hash_id")
      .agg(
          rows=("content_hash_id", "size"),
          target_sum=("future_organic_sessions", "sum"),
          target_positive=(
              "future_organic_sessions",
              lambda x: (x > 0).sum()
          )
      )
      .sort_values("rows", ascending=False)
)

print(client_future.head(20).to_string())

# ------------------------------------------------------------
# 5. Date ranges of affected rows
# ------------------------------------------------------------

print("\n[5/5] Exact future-date ranges")

print("\nContent-created-after-cutoff rows:")
print(
    content_created[content_future]
    .describe()
)

print("\nKeyword-created-after-cutoff rows:")
print(
    keyword_created[keyword_future]
    .describe()
)

print("\n=== FUTURE-DATED ROW QUARANTINE AUDIT COMPLETE ===")

=== FUTURE-DATED ROW QUARANTINE AUDIT ===

[1/5] Future-dated row counts
Content created after cutoff:  1,072
Keyword created after cutoff:  171
Either date after cutoff:      1,072
Both dates after cutoff:       171

[2/5] Target status of future-dated rows
count    1072.000000
mean        1.111940
std         6.115643
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       143.000000
Name: target, dtype: float64

Target missing:
0

Target zero:
835

Target positive:
237

[3/5] Historical performance on future-dated rows
              feature  rows  non_null  zero  positive  median  max
 gsc_impressions_hist  1072      1072  1072         0     0.0  0.0
      gsc_clicks_hist  1072      1072  1072         0     0.0  0.0
    avg_position_hist  1072         0     0         0     NaN  NaN
    ga4_sessions_hist  1072      1072  1072         0     0.0  0.0
   ga4_pageviews_hist  1072      1072  1072         0     0.0  0.0
organic_sessions_hist  1072      1072  1072         0     0.0  0.0

[4/5] Future-dated rows by client
                         rows  target_sum  target_positive
client_hash_id
client_3f0ce4d44fe94f3d   400       445.0              121
client_cd12bcfd98942aa1   132         8.0                5
client_b77d0d5f08f05e64    99        34.0               14
client_2910fd937f0b4d9a    86         0.0                0
client_810019792c9b8efc    77       339.0                9
client_1a730cb2640a1abf    70       120.0               31
client_86ebc2f12c01f586    68       136.0               31
client_4a18d1793d92fb84    65         0.0                0
client_0fa64a184f18a4a0    48       101.0               21
client_b10cb2997d0c7c86    20         7.0                4
client_a2eeb8899886adde     6         0.0                0
client_65de48885f4ef01b     1         2.0                1

[5/5] Exact future-date ranges

Content-created-after-cutoff rows:
count                          1072
mean     2026-04-02 13:00:26.865671
min             2026-04-02 00:00:00
25%             2026-04-02 00:00:00
50%             2026-04-02 00:00:00
75%             2026-04-03 00:00:00
max             2026-04-06 00:00:00
Name: content_created_date, dtype: object

Keyword-created-after-cutoff rows:
count                    171
mean     2026-04-02 00:00:00
min      2026-04-02 00:00:00
25%      2026-04-02 00:00:00
50%      2026-04-02 00:00:00
75%      2026-04-02 00:00:00
max      2026-04-02 00:00:00
Name: keyword_created_date, dtype: object

=== FUTURE-DATED ROW QUARANTINE AUDIT COMPLETE ===

In [ ]:
# ============================================================
# FLYRANK CAPSTONE — CREATE CLEAN PREDICTION POPULATION
# ============================================================

print("=== CREATING CLEAN PREDICTION POPULATION ===")

df = modeling_dataset_final.copy()

CUTOFF = pd.Timestamp("2026-04-01")

content_created = pd.to_datetime(
    df["content_created_date"],
    errors="coerce"
)

keyword_created = pd.to_datetime(
    df["keyword_created_date"],
    errors="coerce"
)

# ------------------------------------------------------------
# Identify rows that could not have existed at cutoff
# ------------------------------------------------------------

future_created = (
    (content_created > CUTOFF) |
    (keyword_created > CUTOFF)
)

print(f"\nOriginal population: {len(df):,}")
print(f"Future-created rows excluded: {future_created.sum():,}")

# ------------------------------------------------------------
# Keep only content that existed by prediction cutoff
# ------------------------------------------------------------

modeling_population = (
    df.loc[~future_created]
      .copy()
      .reset_index(drop=True)
)

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print(f"Clean modeling population: {len(modeling_population):,}")

print("\nDate validation:")

clean_content_created = pd.to_datetime(
    modeling_population["content_created_date"],
    errors="coerce"
)

clean_keyword_created = pd.to_datetime(
    modeling_population["keyword_created_date"],
    errors="coerce"
)

print(
    "Content created after cutoff:",
    (clean_content_created > CUTOFF).sum()
)

print(
    "Keyword created after cutoff:",
    (clean_keyword_created > CUTOFF).sum()
)

# ------------------------------------------------------------
# Target validation
# ------------------------------------------------------------

print("\nTarget validation:")

print(
    "Target missing:",
    modeling_population["future_organic_sessions"].isna().sum()
)

print(
    "Target positive:",
    (
        modeling_population["future_organic_sessions"] > 0
    ).sum()
)

print(
    "Target zero:",
    (
        modeling_population["future_organic_sessions"] == 0
    ).sum()
)

print(
    "Target mean:",
    modeling_population["future_organic_sessions"].mean()
)

# ------------------------------------------------------------
# Historical-data sanity
# ------------------------------------------------------------

print("\nHistorical feature validation:")

for col in [
    "gsc_impressions_hist",
    "gsc_clicks_hist",
    "ga4_sessions_hist",
    "organic_sessions_hist"
]:
    print(
        f"{col}: "
        f"{modeling_population[col].notna().sum():,} non-null"
    )

# ------------------------------------------------------------
# Save a simple reference count
# ------------------------------------------------------------

excluded_rows = df.loc[future_created].copy()

print("\nExcluded future-created rows:")
print(f"  Rows: {len(excluded_rows):,}")
print(
    f"  Positive targets: "
    f"{(excluded_rows['future_organic_sessions'] > 0).sum():,}"
)

print("\n=== CLEAN PREDICTION POPULATION READY ===")

=== CREATING CLEAN PREDICTION POPULATION ===

Original population: 324,998
Future-created rows excluded: 1,072
Clean modeling population: 323,926

Date validation:
Content created after cutoff: 0
Keyword created after cutoff: 0

Target validation:
Target missing: 0
Target positive: 45607
Target zero: 278319
Target mean: 2.6454251897038215

Historical feature validation:
gsc_impressions_hist: 323,926 non-null
gsc_clicks_hist: 323,926 non-null
ga4_sessions_hist: 323,926 non-null
organic_sessions_hist: 323,926 non-null

Excluded future-created rows:
  Rows: 1,072
  Positive targets: 237

=== CLEAN PREDICTION POPULATION READY ===

In [ ]:
# ============================================================
# FLYRANK CAPSTONE — PREDICTION-TIME FEATURE ENGINEERING
# ============================================================

print("=== BUILDING PREDICTION-TIME FEATURE MATRIX ===")

df = modeling_population.copy()

CUTOFF = pd.Timestamp("2026-04-01")

# ------------------------------------------------------------
# 1. Start with a clean feature table
# ------------------------------------------------------------

features = pd.DataFrame(index=df.index)

# ------------------------------------------------------------
# 2. Client-level categorical feature
# ------------------------------------------------------------

features["client_hash_id"] = df["client_hash_id"]

# ------------------------------------------------------------
# 3. Static content / keyword features
# ------------------------------------------------------------

static_numeric = [
    "keyword_char_count",
    "keyword_token_count",
    "url_char_count",
    "search_volume",
    "competition",
    "cpc",
    "backlinks",
    "category_count",
    "char_count",
    "word_count"
]

for col in static_numeric:
    features[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

# ------------------------------------------------------------
# 4. Static categorical features
# ------------------------------------------------------------

static_categorical = [
    "content_type",
    "competition_level",
    "main_intent",
    "provider_used",
    "model_used"
]

for col in static_categorical:
    features[col] = df[col].astype("object")

# ------------------------------------------------------------
# 5. Availability / data-quality indicators
# ------------------------------------------------------------

availability_cols = [
    "client_has_ga4",
    "ga4_data_available",
    "gsc_data_available"
]

for col in availability_cols:
    features[col] = df[col]

# ------------------------------------------------------------
# 6. Prediction-time historical performance
# ------------------------------------------------------------

historical_numeric = [
    "gsc_impressions_hist",
    "gsc_clicks_hist",
    "avg_position_hist",
    "ga4_sessions_hist",
    "ga4_pageviews_hist",
    "organic_sessions_hist",
    "direct_sessions_hist",
    "referral_sessions_hist",
    "social_sessions_hist",
    "paid_sessions_hist",
    "ai_sessions_hist"
]

for col in historical_numeric:
    features[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

# ------------------------------------------------------------
# 7. Derived historical performance features
# ------------------------------------------------------------

# Historical GSC CTR
features["gsc_ctr_hist"] = np.where(
    features["gsc_impressions_hist"] > 0,
    features["gsc_clicks_hist"] /
        features["gsc_impressions_hist"],
    0.0
)

# Historical organic-session share
features["organic_session_share_hist"] = np.where(
    features["ga4_sessions_hist"] > 0,
    features["organic_sessions_hist"] /
        features["ga4_sessions_hist"],
    0.0
)

# Historical AI-session share
features["ai_session_share_hist"] = np.where(
    features["ga4_sessions_hist"] > 0,
    features["ai_sessions_hist"] /
        features["ga4_sessions_hist"],
    0.0
)

# Historical direct-session share
features["direct_session_share_hist"] = np.where(
    features["ga4_sessions_hist"] > 0,
    features["direct_sessions_hist"] /
        features["ga4_sessions_hist"],
    0.0
)

# Historical pageviews per session
features["pageviews_per_session_hist"] = np.where(
    features["ga4_sessions_hist"] > 0,
    features["ga4_pageviews_hist"] /
        features["ga4_sessions_hist"],
    0.0
)

# ------------------------------------------------------------
# 8. Prediction-time content age
# ------------------------------------------------------------

content_created = pd.to_datetime(
    df["content_created_date"],
    errors="coerce"
)

features["content_age_days"] = (
    CUTOFF - content_created
).dt.days

# ------------------------------------------------------------
# 9. Prediction-time keyword age
# ------------------------------------------------------------

keyword_created = pd.to_datetime(
    df["keyword_created_date"],
    errors="coerce"
)

features["keyword_age_days"] = (
    CUTOFF - keyword_created
).dt.days

# ------------------------------------------------------------
# 10. Missingness indicators for important historical fields
# ------------------------------------------------------------

missingness_cols = [
    "avg_position_hist",
    "search_volume",
    "competition",
    "cpc",
    "backlinks",
    "char_count",
    "word_count",
    "keyword_created_date"
]

for col in missingness_cols:
    features[f"{col}_missing"] = df[col].isna().astype("int8")

# ------------------------------------------------------------
# 11. Target kept separately
# ------------------------------------------------------------

target = pd.to_numeric(
    df["future_organic_sessions"],
    errors="coerce"
)

# ------------------------------------------------------------
# 12. Final safety exclusions
# ------------------------------------------------------------

unsafe_columns = [
    # Raw IDs
    "content_hash_id",

    # Post-cutoff / unsafe temporal metadata
    "content_updated_date",
    "last_optimized_date",
    "optimization_eligible_date",

    # Target
    "future_organic_sessions",
    "future_observed_days"
]

# These columns are deliberately NOT added to `features`.
# This explicit list documents the leakage decision.

# ------------------------------------------------------------
# 13. Basic validation
# ------------------------------------------------------------

print("\nFeature matrix shape:")
print(features.shape)

print("\nTarget shape:")
print(target.shape)

print("\nTarget missing:")
print(target.isna().sum())

print("\nFeature columns:")
for i, col in enumerate(features.columns, 1):
    print(f"{i:02d}. {col}")

print("\nFeature data types:")
print(features.dtypes.value_counts())

print("\nTop missing features:")
missing_summary = (
    features.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_summary = missing_summary[
    missing_summary > 0
]

print(missing_summary.head(20))

print("\nPrediction-time date validation:")

print(
    "Content age negative:",
    (features["content_age_days"] < 0).sum()
)

print(
    "Keyword age negative:",
    (features["keyword_age_days"] < 0).sum()
)

print("\nUnsafe columns present:")
print(
    [
        col
        for col in unsafe_columns
        if col in features.columns
    ]
)

print("\n=== PREDICTION-TIME FEATURE MATRIX READY ===")

=== BUILDING PREDICTION-TIME FEATURE MATRIX ===

Feature matrix shape:
(323926, 45)

Target shape:
(323926,)

Target missing:
0

Feature columns:
01. client_hash_id
02. keyword_char_count
03. keyword_token_count
04. url_char_count
05. search_volume
06. competition
07. cpc
08. backlinks
09. category_count
10. char_count
11. word_count
12. content_type
13. competition_level
14. main_intent
15. provider_used
16. model_used
17. client_has_ga4
18. ga4_data_available
19. gsc_data_available
20. gsc_impressions_hist
21. gsc_clicks_hist
22. avg_position_hist
23. ga4_sessions_hist
24. ga4_pageviews_hist
25. organic_sessions_hist
26. direct_sessions_hist
27. referral_sessions_hist
28. social_sessions_hist
29. paid_sessions_hist
30. ai_sessions_hist
31. gsc_ctr_hist
32. organic_session_share_hist
33. ai_session_share_hist
34. direct_session_share_hist
35. pageviews_per_session_hist
36. content_age_days
37. keyword_age_days
38. avg_position_hist_missing
39. search_volume_missing
40. competition_missing
41. cpc_missing
42. backlinks_missing
43. char_count_missing
44. word_count_missing
45. keyword_created_date_missing

Feature data types:
float64    19
int8        8
object      6
int64       5
Int64       4
Int32       3
Name: count, dtype: int64

Top missing features:
provider_used         259559
backlinks             162821
avg_position_hist     116102
char_count            105667
word_count            105667
model_used             83795
competition_level      55295
competition            53992
search_volume          53992
cpc                    53992
main_intent            53173
keyword_age_days       51688
ga4_data_available     38322
dtype: int64

Prediction-time date validation:
Content age negative: 0
Keyword age negative: 0

Unsafe columns present:
[]

=== PREDICTION-TIME FEATURE MATRIX READY ===

In [ ]:
# ============================================================
# FLYRANK CAPSTONE — FINAL FEATURE SAFETY AUDIT
# ============================================================

print("=== FINAL FEATURE SAFETY AUDIT ===")

X = features.copy()
y = target.copy()

# ------------------------------------------------------------
# 1. Feature groups
# ------------------------------------------------------------

numeric_cols = X.select_dtypes(
    include=["number"]
).columns.tolist()

categorical_cols = X.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("\n[1/7] Feature groups")

print(f"Total features:       {X.shape[1]:,}")
print(f"Numeric features:     {len(numeric_cols):,}")
print(f"Categorical features: {len(categorical_cols):,}")

# ------------------------------------------------------------
# 2. Constant / near-constant features
# ------------------------------------------------------------

print("\n[2/7] Constant and near-constant features")

constant_features = []

near_constant_features = []

for col in X.columns:

    nunique = X[col].nunique(dropna=False)

    if nunique <= 1:
        constant_features.append(col)

    # Proportion occupied by most common value
    if nunique > 1:
        top_freq = (
            X[col]
            .value_counts(dropna=False, normalize=True)
            .iloc[0]
        )

        if top_freq >= 0.995:
            near_constant_features.append(
                (col, round(float(top_freq), 4))
            )

print("Constant features:")
print(constant_features if constant_features else "None")

print("\nNear-constant features (>=99.5% same value):")
print(
    near_constant_features
    if near_constant_features
    else "None"
)

# ------------------------------------------------------------
# 3. Numeric range / invalid-value checks
# ------------------------------------------------------------

print("\n[3/7] Numeric feature sanity")

range_rows = []

for col in numeric_cols:

    s = pd.to_numeric(
        X[col],
        errors="coerce"
    )

    range_rows.append({
        "feature": col,
        "non_null": int(s.notna().sum()),
        "missing": int(s.isna().sum()),
        "min": s.min(),
        "median": s.median(),
        "p99": s.quantile(0.99),
        "max": s.max(),
        "negative": int((s < 0).sum()),
        "zero": int((s == 0).sum()),
        "inf": int(np.isinf(s).sum())
    })

range_df = pd.DataFrame(range_rows)

print(
    range_df.to_string(index=False)
)

# ------------------------------------------------------------
# 4. Derived-feature sanity
# ------------------------------------------------------------

print("\n[4/7] Derived feature sanity")

derived_cols = [
    "gsc_ctr_hist",
    "organic_session_share_hist",
    "ai_session_share_hist",
    "direct_session_share_hist",
    "pageviews_per_session_hist"
]

derived_rows = []

for col in derived_cols:

    s = pd.to_numeric(
        X[col],
        errors="coerce"
    )

    derived_rows.append({
        "feature": col,
        "min": s.min(),
        "max": s.max(),
        "missing": int(s.isna().sum()),
        "negative": int((s < 0).sum()),
        "greater_than_1": int((s > 1).sum()),
        "inf": int(np.isinf(s).sum())
    })

derived_df = pd.DataFrame(derived_rows)

print(
    derived_df.to_string(index=False)
)

# ------------------------------------------------------------
# 5. Feature-target correlation audit
# ------------------------------------------------------------

print("\n[5/7] Numeric feature-target correlations")

corr_rows = []

for col in numeric_cols:

    valid = X[col].notna() & y.notna()

    if valid.sum() < 100:
        continue

    corr = X.loc[valid, col].corr(
        y.loc[valid]
    )

    corr_rows.append({
        "feature": col,
        "pearson_corr": corr,
        "abs_corr": abs(corr),
        "valid_rows": int(valid.sum())
    })

corr_df = (
    pd.DataFrame(corr_rows)
    .sort_values(
        "abs_corr",
        ascending=False
    )
)

print(
    corr_df[
        [
            "feature",
            "pearson_corr",
            "valid_rows"
        ]
    ].head(20).to_string(index=False)
)

# ------------------------------------------------------------
# 6. Duplicate / identifier checks
# ------------------------------------------------------------

print("\n[6/7] Duplicate and identifier checks")

duplicate_columns = []

columns = X.columns.tolist()

for i in range(len(columns)):

    for j in range(i + 1, len(columns)):

        a = columns[i]
        b = columns[j]

        if X[a].equals(X[b]):
            duplicate_columns.append(
                (a, b)
            )

print("Duplicate feature pairs:")
print(
    duplicate_columns
    if duplicate_columns
    else "None"
)

print("\nIdentifier-like features:")

identifier_candidates = []

for col in X.columns:

    nunique = X[col].nunique(dropna=False)

    if (
        "hash_id" in col.lower()
        or nunique >= len(X) * 0.95
    ):
        identifier_candidates.append(
            (col, nunique)
        )

print(
    identifier_candidates
    if identifier_candidates
    else "None"
)

# ------------------------------------------------------------
# 7. Explicit leakage checks
# ------------------------------------------------------------

print("\n[7/7] Explicit leakage checks")

leakage_terms = [
    "future",
    "target",
    "observed_days",
    "updated_date",
    "optimized_date",
    "eligible_date"
]

suspicious = []

for col in X.columns:

    lower = col.lower()

    if any(term in lower for term in leakage_terms):
        suspicious.append(col)

print("Suspicious feature names:")
print(
    suspicious
    if suspicious
    else "None"
)

print("\nTarget present in features:")
print(
    "future_organic_sessions" in X.columns
)

print("\nFeature count:")
print(X.shape[1])

print("\n=== FINAL FEATURE SAFETY AUDIT COMPLETE ===")

=== FINAL FEATURE SAFETY AUDIT ===

[1/7] Feature groups
Total features:       45
Numeric features:     39
Categorical features: 6

[2/7] Constant and near-constant features
Constant features:
None

Near-constant features (>=99.5% same value):
[('social_sessions_hist', 0.9973)]

[3/7] Numeric feature sanity
                     feature  non_null  missing  min       median          p99        max  negative   zero  inf
          keyword_char_count    323926        0  0.0    34.000000    60.000000      87.00         0  51688    0
         keyword_token_count    323926        0  0.0     6.000000    10.000000      15.00         0  51688    0
              url_char_count    323926        0  0.0   103.000000   159.000000     240.00         0      3    0
               search_volume    269934    53992  0.0    10.000000  2400.000000  368000.00         0 126202    0
                 competition    269934    53992  0.0     0.000000     1.000000       1.00         0 168120    0
                         cpc    269934    53992  0.0     0.000000    14.690000     239.53         0 206969    0
                   backlinks    161105   162821  0.0     0.000000  1952.000000 2137906.00         0 128608    0
              category_count    323926        0  0.0     0.000000     9.000000      16.00         0 253609    0
                  char_count    218259   105667  0.0 16442.000000 42061.840000  357575.00         0      1    0
                  word_count    218259   105667  0.0  2538.000000  6236.420000   29341.00         0      1    0
              client_has_ga4    323926        0  0.0     1.000000     1.000000       1.00         0  70571    0
          ga4_data_available    285604    38322  0.0     0.000000     1.000000       1.00         0 178448    0
          gsc_data_available    323926        0  0.0     1.000000     1.000000       1.00         0 116102    0
        gsc_impressions_hist    323926        0  0.0    13.000000 52671.500000 1440829.00         0 116102    0
             gsc_clicks_hist    323926        0  0.0     0.000000   209.000000   11329.00         0 227776    0
           avg_position_hist    207824   116102  0.0     9.209789    77.730877     633.00         0   1285    0
           ga4_sessions_hist    323926        0  0.0     0.000000   151.000000    7377.00         0 217068    0
          ga4_pageviews_hist    323926        0  0.0     0.000000   196.000000   15257.00         0 216896    0
       organic_sessions_hist    323926        0  0.0     0.000000   105.000000    8275.00         0 272871    0
        direct_sessions_hist    323926        0  0.0     0.000000    17.000000     912.00         0 244965    0
      referral_sessions_hist    323926        0  0.0     0.000000     3.000000     287.00         0 313845    0
        social_sessions_hist    323926        0  0.0     0.000000     0.000000      82.00         0 323048    0
          paid_sessions_hist    323926        0  0.0     0.000000     3.000000   15185.00         0 316385    0
            ai_sessions_hist    323926        0  0.0     0.000000     2.000000     226.00         0 316595    0
                gsc_ctr_hist    323926        0  0.0     0.000000     0.068328       1.00         0 227776    0
  organic_session_share_hist    323926        0  0.0     0.000000     1.666667      18.00         0 272871    0
       ai_session_share_hist    323926        0  0.0     0.000000     0.071429       5.00         0 316597    0
   direct_session_share_hist    323926        0  0.0     0.000000     2.000000      12.00         0 244965    0
  pageviews_per_session_hist    323926        0  0.0     0.000000     2.000000      20.00         0 217193    0
            content_age_days    323926        0  0.0   219.000000   479.000000     495.00         0   1104    0
            keyword_age_days    272238    51688  1.0   209.000000   479.000000     495.00         0      0    0
   avg_position_hist_missing    323926        0  0.0     0.000000     1.000000       1.00         0 207824    0
       search_volume_missing    323926        0  0.0     0.000000     1.000000       1.00         0 269934    0
         competition_missing    323926        0  0.0     0.000000     1.000000       1.00         0 269934    0
                 cpc_missing    323926        0  0.0     0.000000     1.000000       1.00         0 269934    0
           backlinks_missing    323926        0  0.0     1.000000     1.000000       1.00         0 161105    0
          char_count_missing    323926        0  0.0     0.000000     1.000000       1.00         0 218259    0
          word_count_missing    323926        0  0.0     0.000000     1.000000       1.00         0 218259    0
keyword_created_date_missing    323926        0  0.0     0.000000     1.000000       1.00         0 272238    0

[4/7] Derived feature sanity
                   feature  min  max  missing  negative  greater_than_1  inf
              gsc_ctr_hist  0.0  1.0        0         0               0    0
organic_session_share_hist  0.0 18.0        0         0           12541    0
     ai_session_share_hist  0.0  5.0        0         0             198    0
 direct_session_share_hist  0.0 12.0        0         0           19920    0
pageviews_per_session_hist  0.0 20.0        0         0           40422    0

[5/7] Numeric feature-target correlations
                   feature  pearson_corr  valid_rows
     organic_sessions_hist      0.569007      323926
           gsc_clicks_hist      0.538501      323926
         ga4_sessions_hist      0.508750      323926
        ga4_pageviews_hist      0.490142      323926
      direct_sessions_hist      0.426763      323926
      gsc_impressions_hist      0.406282      323926
organic_session_share_hist      0.255851      323926
    referral_sessions_hist      0.213445      323926
          ai_sessions_hist      0.176956      323926
pageviews_per_session_hist      0.172174      323926
        ga4_data_available      0.149677      285604
      social_sessions_hist      0.091110      323926
 avg_position_hist_missing     -0.082023      323926
        gsc_data_available      0.082023      323926
                word_count      0.065434      218259
        word_count_missing     -0.063947      323926
        char_count_missing     -0.063947      323926
            client_has_ga4      0.061287      323926
         avg_position_hist     -0.060914      207824
         backlinks_missing     -0.060235      323926

[6/7] Duplicate and identifier checks
Duplicate feature pairs:
[('search_volume_missing', 'competition_missing'), ('search_volume_missing', 'cpc_missing'), ('competition_missing', 'cpc_missing'), ('char_count_missing', 'word_count_missing')]

Identifier-like features:
[('client_hash_id', 53)]

[7/7] Explicit leakage checks
Suspicious feature names:
None

Target present in features:
False

Feature count:
45

=== FINAL FEATURE SAFETY AUDIT COMPLETE ===

In [ ]:
print("=== RECONSTRUCTING CLEAN MODELING FEATURES ===")

CUTOFF = "2026-04-01"

# ------------------------------------------------------------------
# 1. Reconstruct the clean population directly in DuckDB
# ------------------------------------------------------------------
con.execute(f"""
CREATE OR REPLACE TEMP TABLE clean_modeling_recovered AS
SELECT
    m.client_hash_id,
    m.content_hash_id,

    m.keyword_char_count,
    m.keyword_token_count,
    m.url_char_count,

    m.content_created_date,
    m.content_updated_date,
    m.content_type,

    m.search_volume,
    m.competition,
    m.competition_level,
    m.cpc,
    m.main_intent,
    m.backlinks,
    m.category_count,

    m.keyword_created_date,

    m.provider_used,
    m.model_used,

    m.char_count,
    m.word_count,

    m.last_optimized_date,
    m.optimization_eligible_date,

    m.is_published,
    m.is_deleted,

    p.gsc_impressions_hist,
    p.gsc_clicks_hist,
    p.avg_position_hist,

    p.ga4_sessions_hist,
    p.ga4_pageviews_hist,

    p.organic_sessions_hist,
    p.direct_sessions_hist,
    p.referral_sessions_hist,
    p.social_sessions_hist,
    p.paid_sessions_hist,
    p.ai_sessions_hist,

    p.client_has_ga4,
    p.ga4_data_available,
    p.gsc_data_available,

    p.future_organic_sessions,
    p.future_observed_days

FROM modeling_dataset m

INNER JOIN prediction_daily p
    ON m.client_hash_id = p.client_hash_id
    AND m.content_hash_id = p.content_hash_id

WHERE
    COALESCE(m.is_deleted, FALSE) = FALSE

    AND m.content_created_date <= DATE '{CUTOFF}'

    AND (
        m.keyword_created_date IS NULL
        OR m.keyword_created_date <= DATE '{CUTOFF}'
    )

    AND p.future_observed_days = 30

    AND p.future_organic_sessions IS NOT NULL
""")

# ------------------------------------------------------------------
# 2. Check recovered population
# ------------------------------------------------------------------
count = con.execute("""
SELECT COUNT(*)
FROM clean_modeling_recovered
""").fetchone()[0]

print(f"\nRecovered clean rows: {count:,}")

# ------------------------------------------------------------------
# 3. Reconstruct pandas dataframe
# ------------------------------------------------------------------
df = con.execute("""
SELECT *
FROM clean_modeling_recovered
""").fetchdf()

print(f"DataFrame shape: {df.shape}")

# ------------------------------------------------------------------
# 4. Verify target
# ------------------------------------------------------------------
print("\nTarget validation:")
print(f"Missing: {(df['future_organic_sessions'].isna()).sum():,}")
print(f"Positive: {(df['future_organic_sessions'] > 0).sum():,}")
print(f"Zero: {(df['future_organic_sessions'] == 0).sum():,}")

# ------------------------------------------------------------------
# 5. Recreate prediction-time derived features
# ------------------------------------------------------------------
df["gsc_ctr_hist"] = (
    df["gsc_clicks_hist"] /
    df["gsc_impressions_hist"].replace(0, np.nan)
).fillna(0)

df["organic_session_share_hist"] = (
    df["organic_sessions_hist"] /
    df["ga4_sessions_hist"].replace(0, np.nan)
).fillna(0)

df["ai_session_share_hist"] = (
    df["ai_sessions_hist"] /
    df["ga4_sessions_hist"].replace(0, np.nan)
).fillna(0)

df["direct_session_share_hist"] = (
    df["direct_sessions_hist"] /
    df["ga4_sessions_hist"].replace(0, np.nan)
).fillna(0)

df["pageviews_per_session_hist"] = (
    df["ga4_pageviews_hist"] /
    df["ga4_sessions_hist"].replace(0, np.nan)
).fillna(0)

# ------------------------------------------------------------------
# 6. Missingness indicators
# ------------------------------------------------------------------
missing_map = {
    "avg_position_hist_missing": "avg_position_hist",
    "search_volume_missing": "search_volume",
    "competition_missing": "competition",
    "cpc_missing": "cpc",
    "backlinks_missing": "backlinks",
    "char_count_missing": "char_count",
    "word_count_missing": "word_count",
    "keyword_created_date_missing": "keyword_created_date"
}

for new_col, source_col in missing_map.items():
    df[new_col] = df[source_col].isna().astype("int8")

# ------------------------------------------------------------------
# 7. Prediction-time age features
# ------------------------------------------------------------------
cutoff = pd.Timestamp(CUTOFF)

df["content_age_days"] = (
    cutoff - pd.to_datetime(df["content_created_date"])
).dt.days

df["keyword_age_days"] = (
    cutoff - pd.to_datetime(df["keyword_created_date"])
).dt.days

# ------------------------------------------------------------------
# 8. Basic reconstruction checks
# ------------------------------------------------------------------
print("\nDerived feature checks:")

for col in [
    "gsc_ctr_hist",
    "organic_session_share_hist",
    "ai_session_share_hist",
    "direct_session_share_hist",
    "pageviews_per_session_hist",
    "content_age_days",
    "keyword_age_days"
]:
    print(
        f"{col}: "
        f"min={df[col].min()}, "
        f"max={df[col].max()}, "
        f"missing={df[col].isna().sum():,}"
    )

print("\nPrediction-time date safety:")
print(
    "Content age negative:",
    (df["content_age_days"] < 0).sum()
)
print(
    "Keyword age negative:",
    (df["keyword_age_days"] < 0).sum()
)

print("\n=== CLEAN MODELING FEATURES RECOVERED ===")

=== RECONSTRUCTING CLEAN MODELING FEATURES ===

Recovered clean rows: 323,926
DataFrame shape: (323926, 40)

Target validation:
Missing: 0
Positive: 45,607
Zero: 278,319

Derived feature checks:
gsc_ctr_hist: min=0.0, max=1.0, missing=0
organic_session_share_hist: min=0.0, max=18.0, missing=0
ai_session_share_hist: min=0.0, max=5.0, missing=0
direct_session_share_hist: min=0.0, max=12.0, missing=0
pageviews_per_session_hist: min=0.0, max=20.0, missing=0
content_age_days: min=0, max=495, missing=0
keyword_age_days: min=1.0, max=495.0, missing=51,688

Prediction-time date safety:
Content age negative: 0
Keyword age negative: 0

=== CLEAN MODELING FEATURES RECOVERED ===

In [ ]:
print("=== PREPARING FINAL MODELING FEATURES ===")

# The previous reconstruction cell created the clean modeling DataFrame
# under the variable `df`. Make a safe copy for the final preparation step.
final_features_df = df.copy()

print(f"Starting rows: {len(final_features_df):,}")
print(f"Starting columns: {len(final_features_df.columns):,}")

# ---------------------------------------------------------------
# 1. Remove identifiers that should not be used as model features
# ---------------------------------------------------------------
identifier_cols = [
    "client_hash_id",
    "content_hash_id"
]

for col in identifier_cols:
    if col in final_features_df.columns:
        final_features_df.drop(columns=col, inplace=True)

# ---------------------------------------------------------------
# 2. Remove target and future-information columns from X
# ---------------------------------------------------------------
target_col = "future_organic_sessions"

if target_col not in final_features_df.columns:
    raise ValueError(
        f"Target column '{target_col}' was not found."
    )

y_final = final_features_df[target_col].copy()

final_features_df.drop(
    columns=[target_col],
    inplace=True
)

# future_observed_days is metadata about target availability,
# not a prediction feature.
if "future_observed_days" in final_features_df.columns:
    final_features_df.drop(
        columns=["future_observed_days"],
        inplace=True
    )

# ---------------------------------------------------------------
# 3. Verify no obvious leakage columns remain
# ---------------------------------------------------------------
unsafe_keywords = [
    "future",
    "target",
    "outcome",
    "next_",
    "post_"
]

unsafe_columns = [
    col for col in final_features_df.columns
    if any(word in col.lower() for word in unsafe_keywords)
]

print("\nLeakage-name check:")
print("Unsafe columns:", unsafe_columns)

# ---------------------------------------------------------------
# 4. Verify target
# ---------------------------------------------------------------
print("\nTarget validation:")
print(f"Rows:       {len(y_final):,}")
print(f"Missing:    {y_final.isna().sum():,}")
print(f"Positive:   {(y_final > 0).sum():,}")
print(f"Zero:       {(y_final == 0).sum():,}")
print(f"Mean:       {y_final.mean():.6f}")

# ---------------------------------------------------------------
# 5. Final feature inventory
# ---------------------------------------------------------------
print("\nFinal feature matrix:")
print(f"Rows:       {len(final_features_df):,}")
print(f"Columns:    {len(final_features_df.columns):,}")

print("\nFeature columns:")
for i, col in enumerate(final_features_df.columns, 1):
    print(f"{i:02d}. {col}")

print("\nData types:")
print(final_features_df.dtypes.value_counts())

print("\n=== FINAL MODELING FEATURES PREPARED ===")

=== PREPARING FINAL MODELING FEATURES ===
Starting rows: 323,926
Starting columns: 55

Leakage-name check:
Unsafe columns: []

Target validation:
Rows:       323,926
Missing:    0
Positive:   45,607
Zero:       278,319
Mean:       2.645425

Final feature matrix:
Rows:       323,926
Columns:    51

Feature columns:
01. keyword_char_count
02. keyword_token_count
03. url_char_count
04. content_created_date
05. content_updated_date
06. content_type
07. search_volume
08. competition
09. competition_level
10. cpc
11. main_intent
12. backlinks
13. category_count
14. keyword_created_date
15. provider_used
16. model_used
17. char_count
18. word_count
19. last_optimized_date
20. optimization_eligible_date
21. is_published
22. is_deleted
23. gsc_impressions_hist
24. gsc_clicks_hist
25. avg_position_hist
26. ga4_sessions_hist
27. ga4_pageviews_hist
28. organic_sessions_hist
29. direct_sessions_hist
30. referral_sessions_hist
31. social_sessions_hist
32. paid_sessions_hist
33. ai_sessions_hist
34. client_has_ga4
35. ga4_data_available
36. gsc_data_available
37. gsc_ctr_hist
38. organic_session_share_hist
39. ai_session_share_hist
40. direct_session_share_hist
41. pageviews_per_session_hist
42. avg_position_hist_missing
43. search_volume_missing
44. competition_missing
45. cpc_missing
46. backlinks_missing
47. char_count_missing
48. word_count_missing
49. keyword_created_date_missing
50. content_age_days
51. keyword_age_days

Data types:
float64           19
int8               8
int64              5
object             5
datetime64[us]     5
Int64              4
bool               2
int32              2
Int32              1
Name: count, dtype: int64

=== FINAL MODELING FEATURES PREPARED ===

In [ ]:
# ================================================================
# CLIENT-LEVEL MODEL SPLIT — STATE-SAFE VERSION
# ================================================================

print("=== CREATING CLIENT-LEVEL MODEL SPLIT ===")

TARGET = "future_organic_sessions"
CLIENT_COL = "client_hash_id"

# ------------------------------------------------
# 1. Recover the prepared dataset from current state
# ------------------------------------------------

candidate_names = [
    "df",
    "clean_modeling_features",
    "final_modeling_features",
    "clean_df",
    "modeling_df"
]

source_name = None
data = None

for name in candidate_names:
    if name in globals():
        obj = globals()[name]

        if hasattr(obj, "columns"):
            cols = set(obj.columns)

            if TARGET in cols and CLIENT_COL in cols:
                data = obj.copy()
                source_name = name
                break

if data is None:
    print("Could not automatically recover the prepared dataset.")
    print("\nAvailable DataFrames containing useful columns:")

    for name, obj in globals().items():
        try:
            if hasattr(obj, "columns"):
                cols = set(obj.columns)

                if TARGET in cols or CLIENT_COL in cols:
                    print(
                        f"  {name}: "
                        f"shape={obj.shape}, "
                        f"target={TARGET in cols}, "
                        f"client={CLIENT_COL in cols}"
                    )
        except Exception:
            pass

    raise RuntimeError(
        "\nSTOP: The prepared modeling DataFrame is not available "
        "under the expected names. Do not continue until we identify it."
    )

print(f"Recovered dataset from: {source_name}")
print(f"Rows: {len(data):,}")
print(f"Columns: {len(data.columns):,}")

# ------------------------------------------------
# 2. Basic validation
# ------------------------------------------------

assert TARGET in data.columns
assert CLIENT_COL in data.columns

print(f"Unique clients: {data[CLIENT_COL].nunique():,}")
print(f"Target missing: {data[TARGET].isna().sum():,}")

# ------------------------------------------------
# 3. Create deterministic client-level split
#
# IMPORTANT:
# Same client must NEVER appear in both train and test.
# ------------------------------------------------

from sklearn.model_selection import GroupShuffleSplit

groups = data[CLIENT_COL]

splitter = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    splitter.split(data, data[TARGET], groups=groups)
)

train_df = data.iloc[train_idx].copy()
test_df = data.iloc[test_idx].copy()

# ------------------------------------------------
# 4. Validate client separation
# ------------------------------------------------

train_clients = set(train_df[CLIENT_COL])
test_clients = set(test_df[CLIENT_COL])

overlap = train_clients.intersection(test_clients)

print("\n=== SPLIT RESULTS ===")

print(f"Train rows:       {len(train_df):,}")
print(f"Test rows:        {len(test_df):,}")

print(f"Train clients:    {len(train_clients):,}")
print(f"Test clients:     {len(test_clients):,}")
print(f"Client overlap:   {len(overlap):,}")

assert len(overlap) == 0, (
    "LEAKAGE ERROR: Some clients appear in both train and test."
)

# ------------------------------------------------
# 5. Target distribution in each split
# ------------------------------------------------

print("\n=== TARGET DISTRIBUTION ===")

print("\nTrain target:")
print(train_df[TARGET].describe())

print("\nTest target:")
print(test_df[TARGET].describe())

print("\nPositive target rate:")

train_positive_rate = (
    train_df[TARGET].gt(0).mean() * 100
)

test_positive_rate = (
    test_df[TARGET].gt(0).mean() * 100
)

print(f"Train: {train_positive_rate:.2f}%")
print(f"Test:  {test_positive_rate:.2f}%")

# ------------------------------------------------
# 6. Save split objects for the next modeling stage
# ------------------------------------------------

client_split = {
    "train": train_df,
    "test": test_df,
    "train_clients": train_clients,
    "test_clients": test_clients
}

print("\n=== CLIENT-LEVEL MODEL SPLIT READY ===")

=== CREATING CLIENT-LEVEL MODEL SPLIT ===
Recovered dataset from: df
Rows: 323,926
Columns: 55
Unique clients: 53
Target missing: 0

=== SPLIT RESULTS ===
Train rows:       285,694
Test rows:        38,232
Train clients:    42
Test clients:     11
Client overlap:   0

=== TARGET DISTRIBUTION ===

Train target:
count    285694.000000
mean          2.755630
std          21.734433
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max        2071.000000
Name: future_organic_sessions, dtype: float64

Test target:
count    38232.000000
mean         1.821903
std         29.434608
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       5119.000000
Name: future_organic_sessions, dtype: float64

Positive target rate:
Train: 14.06%
Test:  14.20%

=== CLIENT-LEVEL MODEL SPLIT READY ===

In [ ]:
# ================================================================
# FLYRANK CAPSTONE
# CLIENT-LEVEL TARGET DISTRIBUTION AUDIT
#
# Purpose:
# The previous random client split produced a validation set
# containing ZERO positive targets.
#
# Before creating a new split, inspect target behavior at the
# CLIENT level so we can construct a balanced client split.
# ================================================================

print("=== CLIENT-LEVEL TARGET DISTRIBUTION AUDIT ===")

TARGET = "future_organic_sessions"
CLIENT = "client_hash_id"

# ------------------------------------------------
# 1. Confirm current dataframe
# ------------------------------------------------

print("\n[1/5] Confirming modeling population...")

try:
    df
except NameError:
    df = con.execute("""
        SELECT *
        FROM clean_modeling_recovered
    """).df()

print(f"Rows:    {len(df):,}")
print(f"Clients: {df[CLIENT].nunique():,}")

if TARGET not in df.columns:
    raise ValueError(f"Target column '{TARGET}' not found.")

if CLIENT not in df.columns:
    raise ValueError(f"Client column '{CLIENT}' not found.")


# ------------------------------------------------
# 2. Build client-level statistics
# ------------------------------------------------

print("\n[2/5] Building client-level target statistics...")

client_stats = (
    df.groupby(CLIENT)[TARGET]
      .agg(
          rows="count",
          total_sessions="sum",
          positive_rows=lambda x: (x > 0).sum(),
          positive_rate=lambda x: (x > 0).mean(),
          mean_target="mean",
          median_target="median",
          max_target="max"
      )
      .sort_values("total_sessions", ascending=False)
)

print("\nAll clients:")
print(
    client_stats.to_string(
        float_format=lambda x: f"{x:.4f}"
    )
)


# ------------------------------------------------
# 3. Identify positive / zero clients
# ------------------------------------------------

print("\n[3/5] Client target composition...")

positive_clients = client_stats[
    client_stats["positive_rows"] > 0
]

zero_only_clients = client_stats[
    client_stats["positive_rows"] == 0
]

print(f"\nClients with >=1 positive row: {len(positive_clients)}")
print(f"Clients with zero positive rows: {len(zero_only_clients)}")

print("\nPositive clients:")
print(
    positive_clients[
        [
            "rows",
            "total_sessions",
            "positive_rows",
            "positive_rate",
            "mean_target",
            "max_target"
        ]
    ].to_string(
        float_format=lambda x: f"{x:.4f}"
    )
)


# ------------------------------------------------
# 4. Show client-level concentration
# ------------------------------------------------

print("\n[4/5] Target concentration...")

total_target = df[TARGET].sum()

client_stats["target_share_pct"] = (
    client_stats["total_sessions"]
    / total_target
    * 100
)

print(
    "\nTop clients by total future organic sessions:"
)

print(
    client_stats[
        [
            "rows",
            "total_sessions",
            "positive_rows",
            "positive_rate",
            "target_share_pct"
        ]
    ].head(15).to_string(
        float_format=lambda x: f"{x:.4f}"
    )
)

print(
    f"\nTotal future organic sessions: {total_target:,.0f}"
)

print(
    f"Top 5 client share: "
    f"{client_stats.head(5)['target_share_pct'].sum():.2f}%"
)

print(
    f"Top 10 client share: "
    f"{client_stats.head(10)['target_share_pct'].sum():.2f}%"
)


# ------------------------------------------------
# 5. Compare current split
# ------------------------------------------------

print("\n[5/5] Auditing current split...")

if "split" in df.columns:

    current_split = (
        df.groupby("split")[TARGET]
          .agg(
              rows="count",
              total_sessions="sum",
              positive_rows=lambda x: (x > 0).sum(),
              positive_rate=lambda x: (x > 0).mean(),
              clients="count"
          )
    )

    # The "clients" count above is actually not unique because
    # groupby is on split. Correct it below.
    client_split_counts = (
        df.groupby("split")[CLIENT]
          .nunique()
          .rename("unique_clients")
    )

    current_split = current_split.drop(
        columns=["clients"]
    ).join(client_split_counts)

    print("\nCurrent split target summary:")
    print(
        current_split.to_string(
            float_format=lambda x: f"{x:.4f}"
        )
    )

    print("\nClients assigned to each current split:")

    for split_name in ["train", "validation", "test"]:
        clients_in_split = sorted(
            df.loc[
                df["split"] == split_name,
                CLIENT
            ].unique()
        )

        print(
            f"\n{split_name.upper()} "
            f"({len(clients_in_split)} clients):"
        )

        for client in clients_in_split:
            stats = client_stats.loc[client]

            print(
                f"  {client} | "
                f"rows={int(stats['rows']):,} | "
                f"positive={int(stats['positive_rows']):,} | "
                f"target={stats['total_sessions']:,.0f}"
            )

else:
    print(
        "No existing split column found."
    )


print("\n=== CLIENT-LEVEL TARGET DISTRIBUTION AUDIT COMPLETE ===")
print(
    "\nDO NOT TRAIN YET."
    "\nUse this output to construct the corrected "
    "client-level stratified split."
)

=== CLIENT-LEVEL TARGET DISTRIBUTION AUDIT ===

[1/5] Confirming modeling population...
Rows:    323,926
Clients: 53

[2/5] Building client-level target statistics...

All clients:
                          rows  total_sessions  positive_rows  positive_rate  mean_target  median_target  max_target
client_hash_id
client_23a62021009f63c4  14617     274661.0000           8902         0.6090      18.7905         2.0000   1905.0000
client_73cda7b4e4f265ea  29323     256297.0000          13418         0.4576       8.7405         0.0000   2071.0000
client_20259bd6705d81d4   4804      91053.0000           2878         0.5991      18.9536         2.0000   1862.0000
client_e547b89c05043229   9300      67717.0000           4752         0.5110       7.2814         1.0000   5119.0000
client_e5c2aa26a8598242   3528      50958.0000           2448         0.6939      14.4439         3.0000   1548.0000
client_fef1a8f436438636  11210      40077.0000           3483         0.3107       3.5751         0.0000    405.0000
client_2094c6eb080311d5   6375      14782.0000           1328         0.2083       2.3187         0.0000    577.0000
client_1a730cb2640a1abf   2471      13989.0000           1178         0.4767       5.6613         0.0000    321.0000
client_0fa64a184f18a4a0   1718      13312.0000            648         0.3772       7.7485         0.0000   1303.0000
client_3f0ce4d44fe94f3d   5997       9496.0000           1391         0.2319       1.5835         0.0000    197.0000
client_a80fca3f171ed1de   7625       9302.0000           1496         0.1962       1.2199         0.0000    228.0000
client_86ebc2f12c01f586    486       2637.0000            316         0.6502       5.4259         2.0000    132.0000
client_3ffa76342f366962  31078       2018.0000            627         0.0202       0.0649         0.0000    124.0000
client_65de48885f4ef01b  13356       1829.0000            446         0.0334       0.1369         0.0000     62.0000
client_b10cb2997d0c7c86   4311       1822.0000            268         0.0622       0.4226         0.0000    117.0000
client_157ffe4d4a595515   4787       1277.0000            368         0.0769       0.2668         0.0000    144.0000
client_b77d0d5f08f05e64   1044       1119.0000            124         0.1188       1.0718         0.0000    231.0000
client_ff644d8251367cbb   4522        964.0000            258         0.0571       0.2132         0.0000     73.0000
client_9958f0a7ae1df715   3067        746.0000            327         0.1066       0.2432         0.0000     11.0000
client_f623b01661d4bfe4   5878        665.0000            138         0.0235       0.1131         0.0000     83.0000
client_3197e6291363b4db  10668        652.0000            248         0.0232       0.0611         0.0000     22.0000
client_cd12bcfd98942aa1   5521        468.0000            208         0.0377       0.0848         0.0000     21.0000
client_c182d11e4862a37d   1769        186.0000             99         0.0560       0.1051         0.0000     23.0000
client_ccdd78843409c8c7    416        168.0000             74         0.1779       0.4038         0.0000      9.0000
client_d211cb07b9059bab   1693        163.0000             23         0.0136       0.0963         0.0000     23.0000
client_def0955f7a377868   1188        144.0000             49         0.0412       0.1212         0.0000     13.0000
client_08d2847f24cf89c1    399        118.0000             20         0.0501       0.2957         0.0000     30.0000
client_a2eeb8899886adde   1214         99.0000             20         0.0165       0.0815         0.0000     14.0000
client_e00b29e582949543    164         92.0000             33         0.2012       0.5610         0.0000     17.0000
client_810019792c9b8efc    203         48.0000              7         0.0345       0.2365         0.0000     17.0000
client_7eafe750768f0ac2    379         29.0000             12         0.0317       0.0765         0.0000      5.0000
client_9d54435aabd95a6c   1020         21.0000             14         0.0137       0.0206         0.0000      3.0000
client_0e1acc6cd57b0eba    147          6.0000              2         0.0136       0.0408         0.0000      5.0000
client_ba65e80a1116ae41  13129          6.0000              3         0.0002       0.0005         0.0000      3.0000
client_f6f0cdf26d03d7bd     94          1.0000              1         0.0106       0.0106         0.0000      1.0000
client_0797ff3a1fc9a6a5    260          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_08a6a72ff48e62c0  28278          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_599043c0ff13edea    727          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_59256b0571e0c970    111          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_4a18d1793d92fb84   4264          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_400c21c81c8b46ef   3791          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_2c32078d69f2cbad     11          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_19b89ee4fe3db6da   6871          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_2910fd937f0b4d9a   2930          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_2b4306c3ed003f01  12126          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_a1203ffecad62470     75          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_8dbf3abdf07569e0    575          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_8ae2bfb5aa1ffa1e    357          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_62f4a7e64f5e0096  25227          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_625b6439094e23e4  31887          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_770e8e5faa9cddfe    200          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_795153d5b7850ccf   2539          0.0000              0         0.0000       0.0000         0.0000      0.0000
client_80ee5b7bd5f4eb89    196          0.0000              0         0.0000       0.0000         0.0000      0.0000

[3/5] Client target composition...

Clients with >=1 positive row: 35
Clients with zero positive rows: 18

Positive clients:
                          rows  total_sessions  positive_rows  positive_rate  mean_target  max_target
client_hash_id
client_23a62021009f63c4  14617     274661.0000           8902         0.6090      18.7905   1905.0000
client_73cda7b4e4f265ea  29323     256297.0000          13418         0.4576       8.7405   2071.0000
client_20259bd6705d81d4   4804      91053.0000           2878         0.5991      18.9536   1862.0000
client_e547b89c05043229   9300      67717.0000           4752         0.5110       7.2814   5119.0000
client_e5c2aa26a8598242   3528      50958.0000           2448         0.6939      14.4439   1548.0000
client_fef1a8f436438636  11210      40077.0000           3483         0.3107       3.5751    405.0000
client_2094c6eb080311d5   6375      14782.0000           1328         0.2083       2.3187    577.0000
client_1a730cb2640a1abf   2471      13989.0000           1178         0.4767       5.6613    321.0000
client_0fa64a184f18a4a0   1718      13312.0000            648         0.3772       7.7485   1303.0000
client_3f0ce4d44fe94f3d   5997       9496.0000           1391         0.2319       1.5835    197.0000
client_a80fca3f171ed1de   7625       9302.0000           1496         0.1962       1.2199    228.0000
client_86ebc2f12c01f586    486       2637.0000            316         0.6502       5.4259    132.0000
client_3ffa76342f366962  31078       2018.0000            627         0.0202       0.0649    124.0000
client_65de48885f4ef01b  13356       1829.0000            446         0.0334       0.1369     62.0000
client_b10cb2997d0c7c86   4311       1822.0000            268         0.0622       0.4226    117.0000
client_157ffe4d4a595515   4787       1277.0000            368         0.0769       0.2668    144.0000
client_b77d0d5f08f05e64   1044       1119.0000            124         0.1188       1.0718    231.0000
client_ff644d8251367cbb   4522        964.0000            258         0.0571       0.2132     73.0000
client_9958f0a7ae1df715   3067        746.0000            327         0.1066       0.2432     11.0000
client_f623b01661d4bfe4   5878        665.0000            138         0.0235       0.1131     83.0000
client_3197e6291363b4db  10668        652.0000            248         0.0232       0.0611     22.0000
client_cd12bcfd98942aa1   5521        468.0000            208         0.0377       0.0848     21.0000
client_c182d11e4862a37d   1769        186.0000             99         0.0560       0.1051     23.0000
client_ccdd78843409c8c7    416        168.0000             74         0.1779       0.4038      9.0000
client_d211cb07b9059bab   1693        163.0000             23         0.0136       0.0963     23.0000
client_def0955f7a377868   1188        144.0000             49         0.0412       0.1212     13.0000
client_08d2847f24cf89c1    399        118.0000             20         0.0501       0.2957     30.0000
client_a2eeb8899886adde   1214         99.0000             20         0.0165       0.0815     14.0000
client_e00b29e582949543    164         92.0000             33         0.2012       0.5610     17.0000
client_810019792c9b8efc    203         48.0000              7         0.0345       0.2365     17.0000
client_7eafe750768f0ac2    379         29.0000             12         0.0317       0.0765      5.0000
client_9d54435aabd95a6c   1020         21.0000             14         0.0137       0.0206      3.0000
client_0e1acc6cd57b0eba    147          6.0000              2         0.0136       0.0408      5.0000
client_ba65e80a1116ae41  13129          6.0000              3         0.0002       0.0005      3.0000
client_f6f0cdf26d03d7bd     94          1.0000              1         0.0106       0.0106      1.0000

[4/5] Target concentration...

Top clients by total future organic sessions:
                          rows  total_sessions  positive_rows  positive_rate  target_share_pct
client_hash_id
client_23a62021009f63c4  14617     274661.0000           8902         0.6090           32.0520
client_73cda7b4e4f265ea  29323     256297.0000          13418         0.4576           29.9090
client_20259bd6705d81d4   4804      91053.0000           2878         0.5991           10.6256
client_e547b89c05043229   9300      67717.0000           4752         0.5110            7.9024
client_e5c2aa26a8598242   3528      50958.0000           2448         0.6939            5.9466
client_fef1a8f436438636  11210      40077.0000           3483         0.3107            4.6769
client_2094c6eb080311d5   6375      14782.0000           1328         0.2083            1.7250
client_1a730cb2640a1abf   2471      13989.0000           1178         0.4767            1.6325
client_0fa64a184f18a4a0   1718      13312.0000            648         0.3772            1.5535
client_3f0ce4d44fe94f3d   5997       9496.0000           1391         0.2319            1.1082
client_a80fca3f171ed1de   7625       9302.0000           1496         0.1962            1.0855
client_86ebc2f12c01f586    486       2637.0000            316         0.6502            0.3077
client_3ffa76342f366962  31078       2018.0000            627         0.0202            0.2355
client_65de48885f4ef01b  13356       1829.0000            446         0.0334            0.2134
client_b10cb2997d0c7c86   4311       1822.0000            268         0.0622            0.2126

Total future organic sessions: 856,922
Top 5 client share: 86.44%
Top 10 client share: 97.13%

[5/5] Auditing current split...

Current split target summary:
              rows  total_sessions  positive_rows  positive_rate  unique_clients
split
test         65172     133213.0000           7184         0.1102               9
train       211154     723709.0000          38423         0.1820              37
validation   47600          0.0000              0         0.0000               7

Clients assigned to each current split:

TRAIN (37 clients):
  client_0e1acc6cd57b0eba | rows=147 | positive=2 | target=6
  client_0fa64a184f18a4a0 | rows=1,718 | positive=648 | target=13,312
  client_157ffe4d4a595515 | rows=4,787 | positive=368 | target=1,277
  client_1a730cb2640a1abf | rows=2,471 | positive=1,178 | target=13,989
  client_2094c6eb080311d5 | rows=6,375 | positive=1,328 | target=14,782
  client_23a62021009f63c4 | rows=14,617 | positive=8,902 | target=274,661
  client_3f0ce4d44fe94f3d | rows=5,997 | positive=1,391 | target=9,496
  client_3ffa76342f366962 | rows=31,078 | positive=627 | target=2,018
  client_400c21c81c8b46ef | rows=3,791 | positive=0 | target=0
  client_4a18d1793d92fb84 | rows=4,264 | positive=0 | target=0
  client_599043c0ff13edea | rows=727 | positive=0 | target=0
  client_625b6439094e23e4 | rows=31,887 | positive=0 | target=0
  client_65de48885f4ef01b | rows=13,356 | positive=446 | target=1,829
  client_73cda7b4e4f265ea | rows=29,323 | positive=13,418 | target=256,297
  client_770e8e5faa9cddfe | rows=200 | positive=0 | target=0
  client_795153d5b7850ccf | rows=2,539 | positive=0 | target=0
  client_7eafe750768f0ac2 | rows=379 | positive=12 | target=29
  client_80ee5b7bd5f4eb89 | rows=196 | positive=0 | target=0
  client_810019792c9b8efc | rows=203 | positive=7 | target=48
  client_86ebc2f12c01f586 | rows=486 | positive=316 | target=2,637
  client_8ae2bfb5aa1ffa1e | rows=357 | positive=0 | target=0
  client_8dbf3abdf07569e0 | rows=575 | positive=0 | target=0
  client_9d54435aabd95a6c | rows=1,020 | positive=14 | target=21
  client_a80fca3f171ed1de | rows=7,625 | positive=1,496 | target=9,302
  client_b10cb2997d0c7c86 | rows=4,311 | positive=268 | target=1,822
  client_b77d0d5f08f05e64 | rows=1,044 | positive=124 | target=1,119
  client_ba65e80a1116ae41 | rows=13,129 | positive=3 | target=6
  client_c182d11e4862a37d | rows=1,769 | positive=99 | target=186
  client_ccdd78843409c8c7 | rows=416 | positive=74 | target=168
  client_d211cb07b9059bab | rows=1,693 | positive=23 | target=163
  client_def0955f7a377868 | rows=1,188 | positive=49 | target=144
  client_e00b29e582949543 | rows=164 | positive=33 | target=92
  client_e547b89c05043229 | rows=9,300 | positive=4,752 | target=67,717
  client_e5c2aa26a8598242 | rows=3,528 | positive=2,448 | target=50,958
  client_f623b01661d4bfe4 | rows=5,878 | positive=138 | target=665
  client_f6f0cdf26d03d7bd | rows=94 | positive=1 | target=1
  client_ff644d8251367cbb | rows=4,522 | positive=258 | target=964

VALIDATION (7 clients):
  client_0797ff3a1fc9a6a5 | rows=260 | positive=0 | target=0
  client_19b89ee4fe3db6da | rows=6,871 | positive=0 | target=0
  client_2910fd937f0b4d9a | rows=2,930 | positive=0 | target=0
  client_2b4306c3ed003f01 | rows=12,126 | positive=0 | target=0
  client_59256b0571e0c970 | rows=111 | positive=0 | target=0
  client_62f4a7e64f5e0096 | rows=25,227 | positive=0 | target=0
  client_a1203ffecad62470 | rows=75 | positive=0 | target=0

TEST (9 clients):
  client_08a6a72ff48e62c0 | rows=28,278 | positive=0 | target=0
  client_08d2847f24cf89c1 | rows=399 | positive=20 | target=118
  client_20259bd6705d81d4 | rows=4,804 | positive=2,878 | target=91,053
  client_2c32078d69f2cbad | rows=11 | positive=0 | target=0
  client_3197e6291363b4db | rows=10,668 | positive=248 | target=652
  client_9958f0a7ae1df715 | rows=3,067 | positive=327 | target=746
  client_a2eeb8899886adde | rows=1,214 | positive=20 | target=99
  client_cd12bcfd98942aa1 | rows=5,521 | positive=208 | target=468
  client_fef1a8f436438636 | rows=11,210 | positive=3,483 | target=40,077

=== CLIENT-LEVEL TARGET DISTRIBUTION AUDIT COMPLETE ===

DO NOT TRAIN YET.
Use this output to construct the corrected client-level stratified split.

In [ ]:
# ================================================================
# CORRECTED CLIENT-LEVEL STRATIFIED SPLIT
# Uses the already-recovered 323,926-row clean population.
# DOES NOT reconstruct the population.
# ================================================================

import numpy as np
import pandas as pd


print("=== CREATING CORRECTED CLIENT-LEVEL STRATIFIED SPLIT ===")


# ----------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------

TARGET = "future_organic_sessions"
CLIENT_COL = "client_hash_id"

RANDOM_STATE = 42

TRAIN_CLIENT_FRACTION = 0.70
VALIDATION_CLIENT_FRACTION = 0.15
TEST_CLIENT_FRACTION = 0.15


# ----------------------------------------------------------------
# 1. Recover exact clean population
# ----------------------------------------------------------------

print("\n[1/8] Recovering exact clean modeling population...")

df = con.execute("""
    SELECT *
    FROM clean_modeling_recovered
""").df()

print(f"Rows:    {len(df):,}")
print(f"Columns: {df.shape[1]:,}")


# ----------------------------------------------------------------
# 2. Validate population
# ----------------------------------------------------------------

print("\n[2/8] Validating population...")

required_columns = [
    CLIENT_COL,
    TARGET
]

missing_columns = [
    c for c in required_columns
    if c not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

if df[CLIENT_COL].isna().any():
    raise ValueError(
        "client_hash_id contains missing values."
    )

if df[TARGET].isna().any():
    raise ValueError(
        "Target contains missing values."
    )

print(f"Clients:       {df[CLIENT_COL].nunique():,}")
print(f"Target mean:   {df[TARGET].mean():.6f}")
print(f"Positive rows: {(df[TARGET] > 0).sum():,}")
print(f"Zero rows:     {(df[TARGET] == 0).sum():,}")


# ----------------------------------------------------------------
# 3. Build client-level statistics
# ----------------------------------------------------------------

print("\n[3/8] Building client-level statistics...")

client_stats = (
    df
    .groupby(CLIENT_COL)
    .agg(
        rows=(TARGET, "size"),
        total_target=(TARGET, "sum"),
        positive_rows=(TARGET, lambda x: (x > 0).sum()),
        mean_target=(TARGET, "mean")
    )
)

client_stats["has_positive"] = (
    client_stats["positive_rows"] > 0
)

client_stats["target_share"] = (
    client_stats["total_target"] /
    client_stats["total_target"].sum()
)

print(
    f"Total clients:            {len(client_stats):,}"
)

print(
    f"Positive-target clients:   "
    f"{client_stats['has_positive'].sum():,}"
)

print(
    f"Zero-positive clients:     "
    f"{(~client_stats['has_positive']).sum():,}"
)


# ----------------------------------------------------------------
# 4. Deterministic stratified client assignment
#
# We stratify clients into:
#
#   A. positive-target clients
#   B. zero-target clients
#
# Within the positive group, clients are ordered by total target
# so the large target-contributing clients are distributed rather
# than accidentally concentrated into one split.
#
# The assignment is deterministic because RANDOM_STATE is fixed.
# ----------------------------------------------------------------

print("\n[4/8] Creating stratified client assignment...")

rng = np.random.default_rng(RANDOM_STATE)

positive_clients = client_stats[
    client_stats["has_positive"]
].copy()

zero_clients = client_stats[
    ~client_stats["has_positive"]
].copy()


def assign_clients_stratified(
    stats,
    train_fraction,
    validation_fraction,
    test_fraction,
    rng
):
    """
    Assign clients to train/validation/test.

    Uses shuffled ordering followed by round-robin assignment,
    which prevents all large/positive clients from naturally
    clustering in one split.
    """

    clients = stats.index.to_numpy().copy()

    rng.shuffle(clients)

    n = len(clients)

    n_train = int(round(n * train_fraction))
    n_validation = int(round(n * validation_fraction))

    # Make sure all clients are assigned exactly once.
    n_train = min(n_train, n)
    n_validation = min(
        n_validation,
        n - n_train
    )

    assignments = {}

    for i, client in enumerate(clients):

        if i < n_train:
            assignments[client] = "train"

        elif i < n_train + n_validation:
            assignments[client] = "validation"

        else:
            assignments[client] = "test"

    return assignments


positive_assignment = assign_clients_stratified(
    positive_clients,
    TRAIN_CLIENT_FRACTION,
    VALIDATION_CLIENT_FRACTION,
    TEST_CLIENT_FRACTION,
    rng
)

zero_assignment = assign_clients_stratified(
    zero_clients,
    TRAIN_CLIENT_FRACTION,
    VALIDATION_CLIENT_FRACTION,
    TEST_CLIENT_FRACTION,
    rng
)


# Combine assignments
client_assignment = {}

client_assignment.update(positive_assignment)
client_assignment.update(zero_assignment)


if len(client_assignment) != len(client_stats):
    raise ValueError(
        "Not every client received a split assignment."
    )


# ----------------------------------------------------------------
# 5. Attach split to every row
# ----------------------------------------------------------------

print("\n[5/8] Assigning rows to splits...")

df["split"] = df[CLIENT_COL].map(client_assignment)


if df["split"].isna().any():
    missing_clients = (
        df.loc[
            df["split"].isna(),
            CLIENT_COL
        ]
        .unique()
    )

    raise ValueError(
        f"Some clients were not assigned: {missing_clients}"
    )


# ----------------------------------------------------------------
# 6. Verify client isolation
# ----------------------------------------------------------------

print("\n[6/8] Verifying client isolation...")

train_clients = set(
    df.loc[df["split"] == "train", CLIENT_COL]
)

validation_clients = set(
    df.loc[df["split"] == "validation", CLIENT_COL]
)

test_clients = set(
    df.loc[df["split"] == "test", CLIENT_COL]
)


train_validation_overlap = (
    train_clients & validation_clients
)

train_test_overlap = (
    train_clients & test_clients
)

validation_test_overlap = (
    validation_clients & test_clients
)


print(
    f"Train ∩ Validation: "
    f"{len(train_validation_overlap)}"
)

print(
    f"Train ∩ Test:       "
    f"{len(train_test_overlap)}"
)

print(
    f"Validation ∩ Test:  "
    f"{len(validation_test_overlap)}"
)


if (
    train_validation_overlap
    or train_test_overlap
    or validation_test_overlap
):
    raise ValueError(
        "CLIENT LEAKAGE DETECTED."
    )


# ----------------------------------------------------------------
# 7. Detailed split audit
# ----------------------------------------------------------------

print("\n[7/8] Auditing corrected split...")

split_summary = (
    df
    .groupby("split")
    .agg(
        rows=(TARGET, "size"),
        total_sessions=(TARGET, "sum"),
        mean_target=(TARGET, "mean"),
        median_target=(TARGET, "median"),
        positive_rows=(
            TARGET,
            lambda x: (x > 0).sum()
        ),
        unique_clients=(CLIENT_COL, "nunique")
    )
)

split_summary["positive_pct"] = (
    split_summary["positive_rows"]
    / split_summary["rows"]
    * 100
)

split_summary["row_pct"] = (
    split_summary["rows"]
    / len(df)
    * 100
)

print("\nSplit summary:")
print(
    split_summary[
        [
            "rows",
            "row_pct",
            "unique_clients",
            "total_sessions",
            "mean_target",
            "median_target",
            "positive_rows",
            "positive_pct"
        ]
    ]
    .sort_index()
    .to_string()
)


# ----------------------------------------------------------------
# Client-level composition by split
# ----------------------------------------------------------------

client_assignment_df = pd.DataFrame({
    CLIENT_COL: list(client_assignment.keys()),
    "split": list(client_assignment.values())
})

client_assignment_df = client_assignment_df.merge(
    client_stats.reset_index(),
    on=CLIENT_COL,
    how="left"
)

client_composition = (
    client_assignment_df
    .groupby("split")
    .agg(
        clients=(CLIENT_COL, "nunique"),
        positive_clients=(
            "has_positive",
            "sum"
        ),
        zero_positive_clients=(
            "has_positive",
            lambda x: (~x).sum()
        ),
        total_client_target=(
            "total_target",
            "sum"
        )
    )
)

client_composition["target_share_pct"] = (
    client_composition["total_client_target"]
    / client_stats["total_target"].sum()
    * 100
)

print("\nClient composition:")
print(
    client_composition
    .sort_index()
    .to_string()
)


# ----------------------------------------------------------------
# Positive-client distribution
# ----------------------------------------------------------------

print("\nPositive-target clients by split:")

positive_client_split = (
    client_assignment_df[
        client_assignment_df["has_positive"]
    ]
    .groupby("split")
    .agg(
        positive_clients=(CLIENT_COL, "nunique"),
        rows=("rows", "sum"),
        total_target=("total_target", "sum"),
        positive_rows=("positive_rows", "sum")
    )
)

positive_client_split["target_share_pct"] = (
    positive_client_split["total_target"]
    / positive_client_split["total_target"].sum()
    * 100
)

print(
    positive_client_split
    .sort_index()
    .to_string()
)


# ----------------------------------------------------------------
# 8. Save split tables in DuckDB
# ----------------------------------------------------------------

print("\n[8/8] Saving corrected split...")

# Save the complete split population.
con.register(
    "corrected_split_df",
    df
)

con.execute("""
    CREATE OR REPLACE TEMP TABLE corrected_client_split AS
    SELECT *
    FROM corrected_split_df
""")


# Save client-level assignment separately.
con.register(
    "client_assignment_df_temp",
    client_assignment_df
)

con.execute("""
    CREATE OR REPLACE TEMP TABLE client_split_assignment AS
    SELECT *
    FROM client_assignment_df_temp
""")


# ----------------------------------------------------------------
# Final validation
# ----------------------------------------------------------------

final_count = con.execute("""
    SELECT COUNT(*)
    FROM corrected_client_split
""").fetchone()[0]


final_clients = con.execute("""
    SELECT COUNT(DISTINCT client_hash_id)
    FROM corrected_client_split
""").fetchone()[0]


print("\n=== CORRECTED CLIENT-LEVEL STRATIFIED SPLIT COMPLETE ===")

print(f"Total rows:    {final_count:,}")
print(f"Total clients: {final_clients:,}")

print("\nRows by split:")

print(
    con.execute("""
        SELECT
            split,
            COUNT(*) AS rows,
            COUNT(DISTINCT client_hash_id) AS clients,
            SUM(future_organic_sessions) AS total_target,
            SUM(
                CASE
                    WHEN future_organic_sessions > 0
                    THEN 1
                    ELSE 0
                END
            ) AS positive_rows
        FROM corrected_client_split
        GROUP BY split
        ORDER BY
            CASE split
                WHEN 'train' THEN 1
                WHEN 'validation' THEN 2
                WHEN 'test' THEN 3
            END
    """)
    .df()
    .to_string(index=False)
)


print("\n=== READY FOR FINAL SPLIT REVIEW ===")

=== CREATING CORRECTED CLIENT-LEVEL STRATIFIED SPLIT ===

[1/8] Recovering exact clean modeling population...
Rows:    323,926
Columns: 40

[2/8] Validating population...
Clients:       53
Target mean:   2.645425
Positive rows: 45,607
Zero rows:     278,319

[3/8] Building client-level statistics...
Total clients:            53
Positive-target clients:   35
Zero-positive clients:     18

[4/8] Creating stratified client assignment...

[5/8] Assigning rows to splits...

[6/8] Verifying client isolation...
Train ∩ Validation: 0
Train ∩ Test:       0
Validation ∩ Test:  0

[7/8] Auditing corrected split...

Split summary:
              rows    row_pct  unique_clients  total_sessions  mean_target  median_target  positive_rows  positive_pct
split
test         18743   5.786198               8         27989.0     1.493304            0.0           2089     11.145494
train       245323  75.734273              37        529563.0     2.158636            0.0          26040     10.614578
validation   59860  18.479529               8        299370.0     5.001169            0.0          17478     29.198129

Client composition:
            clients  positive_clients  zero_positive_clients  total_client_target  target_share_pct
split
test              8                 6                      2              27989.0          3.266225
train            37                24                     13             529563.0         61.798273
validation        8                 5                      3             299370.0         34.935502

Positive-target clients by split:
            positive_clients    rows  total_target  positive_rows  target_share_pct
split
test                       6   15477       27989.0           2089          3.266225
train                     24  132888      529563.0          26040         61.798273
validation                 5   55136      299370.0          17478         34.935502

[8/8] Saving corrected split...

=== CORRECTED CLIENT-LEVEL STRATIFIED SPLIT COMPLETE ===
Total rows:    323,926
Total clients: 53

Rows by split:
     split   rows  clients  total_target  positive_rows
     train 245323       37      529563.0        26040.0
validation  59860        8      299370.0        17478.0
      test  18743        8       27989.0         2089.0

=== READY FOR FINAL SPLIT REVIEW ===

In [ ]:
# ================================================================
# ATTACH CORRECTED CLIENT SPLIT TO RESTORED MODELING FEATURES
# ================================================================

print("=" * 70)
print("=== ATTACHING CORRECTED CLIENT-LEVEL SPLIT ===")
print("=" * 70)

# ------------------------------------------------
# [1/5] Confirm restored feature matrix
# ------------------------------------------------
print("\n[1/5] Confirming restored modeling features...")

print(f"Feature rows:    {len(final_modeling_features):,}")
print(f"Feature columns: {final_modeling_features.shape[1]}")

if len(final_modeling_features) != 323_926:
    raise RuntimeError(
        "Restored feature matrix does not contain exactly 323,926 rows."
    )

if final_modeling_features.shape[1] != 51:
    raise RuntimeError(
        "Restored feature matrix does not contain exactly 51 features."
    )

# ------------------------------------------------
# [2/5] Recover stable row keys from authoritative
#     clean population
# ------------------------------------------------
print("\n[2/5] Recovering stable row keys...")

keys_df = con.execute("""
    SELECT
        client_hash_id,
        content_hash_id
    FROM clean_modeling_recovered
""").df()

print(f"Key rows: {len(keys_df):,}")

if len(keys_df) != 323_926:
    raise RuntimeError(
        "Key population does not match the validated clean population."
    )

# Check uniqueness.
duplicate_keys = keys_df.duplicated(
    subset=["client_hash_id", "content_hash_id"]
).sum()

print(f"Duplicate key pairs: {duplicate_keys:,}")

if duplicate_keys != 0:
    raise RuntimeError(
        "client_hash_id + content_hash_id is not unique. "
        "Cannot safely attach the split using these keys."
    )

# ------------------------------------------------
# [3/5] Combine keys + restored features
# ------------------------------------------------
print("\n[3/5] Combining keys with restored features...")

modeling_features_with_keys = pd.concat(
    [
        keys_df.reset_index(drop=True),
        final_modeling_features.reset_index(drop=True)
    ],
    axis=1
)

print(
    f"Combined rows:    {len(modeling_features_with_keys):,}"
)
print(
    f"Combined columns: {modeling_features_with_keys.shape[1]}"
)

if modeling_features_with_keys.shape[1] != 53:
    raise RuntimeError(
        "Expected 53 columns: 2 stable keys + 51 modeling features."
    )

# ------------------------------------------------
# [4/5] Load corrected split
# ------------------------------------------------
print("\n[4/5] Loading corrected client-level split...")

split_df = con.execute("""
    SELECT
        client_hash_id,
        content_hash_id,
        split
    FROM corrected_client_split
""").df()

print(f"Split rows: {len(split_df):,}")

if len(split_df) != 323_926:
    raise RuntimeError(
        "Corrected split does not contain exactly 323,926 rows."
    )

if split_df["split"].isna().sum() != 0:
    raise RuntimeError(
        "Corrected split contains missing split assignments."
    )

# Verify split keys are unique.
split_duplicates = split_df.duplicated(
    subset=["client_hash_id", "content_hash_id"]
).sum()

print(f"Duplicate split keys: {split_duplicates:,}")

if split_duplicates != 0:
    raise RuntimeError(
        "Corrected split contains duplicate key pairs."
    )

# ------------------------------------------------
# [5/5] Attach split
# ------------------------------------------------
print("\n[5/5] Attaching split...")

modeling_dataset_final = modeling_features_with_keys.merge(
    split_df,
    on=["client_hash_id", "content_hash_id"],
    how="left",
    validate="one_to_one"
)

print(
    f"Final rows:    {len(modeling_dataset_final):,}"
)
print(
    f"Final columns: {modeling_dataset_final.shape[1]}"
)

# ------------------------------------------------
# FINAL VALIDATION
# ------------------------------------------------
print("\n" + "=" * 70)
print("=== FINAL MODELING DATASET VALIDATION ===")
print("=" * 70)

# Row preservation
assert len(modeling_dataset_final) == 323_926

# Split completeness
missing_split = modeling_dataset_final["split"].isna().sum()

print(f"\nMissing split assignments: {missing_split:,}")

if missing_split != 0:
    raise RuntimeError(
        "Some modeling rows did not receive a split."
    )

# Target is NOT inside the 51 feature matrix, so validate it
# separately against the authoritative clean population.
target_check = con.execute("""
    SELECT
        COUNT(*) AS rows,
        SUM(CASE WHEN future_organic_sessions > 0 THEN 1 ELSE 0 END)
            AS positive_rows,
        SUM(future_organic_sessions) AS total_target
    FROM clean_modeling_recovered
""").fetchone()

print("\nAuthoritative target:")
print(f"Rows:           {target_check[0]:,}")
print(f"Positive rows:  {target_check[1]:,}")
print(f"Total target:   {target_check[2]:,.0f}")

if target_check[0] != 323_926:
    raise RuntimeError("Target population changed.")

if target_check[1] != 45_607:
    raise RuntimeError("Positive-row count changed.")

if target_check[2] != 856_922:
    raise RuntimeError("Target total changed.")

# Split counts
print("\nFinal split distribution:")
print(
    modeling_dataset_final["split"]
    .value_counts()
    .sort_index()
)

# Client counts
print("\nClients by split:")
print(
    modeling_dataset_final
    .groupby("split")["client_hash_id"]
    .nunique()
)

# Client isolation
train_clients = set(
    modeling_dataset_final.loc[
        modeling_dataset_final["split"] == "train",
        "client_hash_id"
    ]
)

validation_clients = set(
    modeling_dataset_final.loc[
        modeling_dataset_final["split"] == "validation",
        "client_hash_id"
    ]
)

test_clients = set(
    modeling_dataset_final.loc[
        modeling_dataset_final["split"] == "test",
        "client_hash_id"
    ]
)

print("\nClient overlap:")
print(
    "Train ∩ Validation:",
    len(train_clients & validation_clients)
)
print(
    "Train ∩ Test:",
    len(train_clients & test_clients)
)
print(
    "Validation ∩ Test:",
    len(validation_clients & test_clients)
)

if train_clients & validation_clients:
    raise RuntimeError("Client leakage: train/validation overlap.")

if train_clients & test_clients:
    raise RuntimeError("Client leakage: train/test overlap.")

if validation_clients & test_clients:
    raise RuntimeError("Client leakage: validation/test overlap.")

# ------------------------------------------------
# SAVE AS DUCKDB TEMP TABLE FOR NEXT PIPELINE STAGE
# ------------------------------------------------
print("\nSaving final modeling dataset to DuckDB...")

con.register(
    "modeling_dataset_final_df",
    modeling_dataset_final
)

con.execute("""
    CREATE OR REPLACE TEMP TABLE modeling_dataset_final AS
    SELECT *
    FROM modeling_dataset_final_df
""")

print("\n" + "=" * 70)
print("=== FINAL MODELING DATASET READY ===")
print("=" * 70)

print(f"Rows:               {len(modeling_dataset_final):,}")
print(f"Columns:            {modeling_dataset_final.shape[1]}")
print("51 validated features: PASS")
print("Corrected split:       PASS")
print("Target population:     PASS")
print("Client isolation:      PASS")
print("DuckDB table:           modeling_dataset_final")
print("\nDO NOT TRAIN YET.")
print("Share this output with me.")

======================================================================
=== ATTACHING CORRECTED CLIENT-LEVEL SPLIT ===
======================================================================

[1/5] Confirming restored modeling features...
Feature rows:    323,926
Feature columns: 51

[2/5] Recovering stable row keys...
Key rows: 323,926
Duplicate key pairs: 0

[3/5] Combining keys with restored features...
Combined rows:    323,926
Combined columns: 53

[4/5] Loading corrected client-level split...
Split rows: 323,926
Duplicate split keys: 0

[5/5] Attaching split...
Final rows:    323,926
Final columns: 54

======================================================================
=== FINAL MODELING DATASET VALIDATION ===
======================================================================

Missing split assignments: 0

Authoritative target:
Rows:           323,926
Positive rows:  45,607
Total target:   856,922

Final split distribution:
split
test           18743
train         245323
validation     59860
Name: count, dtype: int64

Clients by split:
split
test           8
train         37
validation     8
Name: client_hash_id, dtype: int64

Client overlap:
Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

Saving final modeling dataset to DuckDB...

======================================================================
=== FINAL MODELING DATASET READY ===
======================================================================
Rows:               323,926
Columns:            54
51 validated features: PASS
Corrected split:       PASS
Target population:     PASS
Client isolation:      PASS
DuckDB table:           modeling_dataset_final

DO NOT TRAIN YET.
Share this output with me.

In [ ]:
# ================================================================
# PREPARE TRAIN / VALIDATION / TEST MATRICES
# ================================================================

print("=" * 70)
print("=== PREPARING MODEL TRAINING MATRICES ===")
print("=" * 70)

# ----------------------------------------------------------------
# [0/8] Confirm final dataset
# ----------------------------------------------------------------
print("\n[0/8] Checking final modeling dataset...")

if "modeling_dataset_final" not in locals():
    raise RuntimeError(
        "modeling_dataset_final is not available. "
        "Run the previous successful cell first."
    )

df = modeling_dataset_final.copy()

print(f"Rows:    {len(df):,}")
print(f"Columns: {df.shape[1]}")

if len(df) != 323_926:
    raise RuntimeError("Unexpected modeling population size.")

# ----------------------------------------------------------------
# [1/8] Define target and identifiers
# ----------------------------------------------------------------
print("\n[1/8] Defining target and identifiers...")

TARGET = "future_organic_sessions"

ID_COLUMNS = [
    "client_hash_id",
    "content_hash_id",
    "split",
]

# The target is intentionally NOT part of the 51 feature matrix.
# Recover it from the authoritative clean population using the
# stable row keys.
target_df = con.execute("""
    SELECT
        client_hash_id,
        content_hash_id,
        future_organic_sessions
    FROM clean_modeling_recovered
""").df()

print(f"Target rows: {len(target_df):,}")

if len(target_df) != 323_926:
    raise RuntimeError(
        "Authoritative target population changed."
    )

# ----------------------------------------------------------------
# [2/8] Attach target
# ----------------------------------------------------------------
print("\n[2/8] Attaching authoritative target...")

df = df.merge(
    target_df,
    on=["client_hash_id", "content_hash_id"],
    how="left",
    validate="one_to_one"
)

print(f"Rows after target attachment: {len(df):,}")

missing_target = df[TARGET].isna().sum()

print(f"Missing target: {missing_target:,}")

if missing_target != 0:
    raise RuntimeError(
        "Target attachment produced missing values."
    )

# ----------------------------------------------------------------
# [3/8] Validate target
# ----------------------------------------------------------------
print("\n[3/8] Validating target...")

target_positive = (df[TARGET] > 0).sum()
target_zero = (df[TARGET] == 0).sum()
target_total = df[TARGET].sum()

print(f"Positive rows: {target_positive:,}")
print(f"Zero rows:     {target_zero:,}")
print(f"Total target:  {target_total:,.0f}")
print(f"Mean target:   {df[TARGET].mean():.6f}")

if target_positive != 45_607:
    raise RuntimeError(
        "Positive target count changed."
    )

if target_total != 856_922:
    raise RuntimeError(
        "Total target changed."
    )

# ----------------------------------------------------------------
# [4/8] Identify feature columns
# ----------------------------------------------------------------
print("\n[4/8] Identifying feature columns...")

FEATURE_COLUMNS = [
    c for c in df.columns
    if c not in ID_COLUMNS + [TARGET]
]

print(f"Feature count: {len(FEATURE_COLUMNS)}")

if len(FEATURE_COLUMNS) != 51:
    raise RuntimeError(
        f"Expected exactly 51 features, found {len(FEATURE_COLUMNS)}."
    )

print("\nFeature columns:")
for i, col in enumerate(FEATURE_COLUMNS, 1):
    print(f"{i:02d}. {col}")

# ----------------------------------------------------------------
# [5/8] Check for unsafe columns / leakage
# ----------------------------------------------------------------
print("\n[5/8] Running final leakage-name check...")

UNSAFE_TERMS = [
    "future",
    "target",
    "label",
    "outcome",
    "next_",
    "post_",
]

unsafe_columns = []

for col in FEATURE_COLUMNS:
    col_lower = col.lower()

    if any(term in col_lower for term in UNSAFE_TERMS):
        unsafe_columns.append(col)

print("Unsafe feature columns:", unsafe_columns)

if unsafe_columns:
    raise RuntimeError(
        "Potential target leakage detected in feature names: "
        + str(unsafe_columns)
    )

# ----------------------------------------------------------------
# [6/8] Split matrices
# ----------------------------------------------------------------
print("\n[6/8] Creating train / validation / test datasets...")

train_df = df[df["split"] == "train"].copy()
validation_df = df[df["split"] == "validation"].copy()
test_df = df[df["split"] == "test"].copy()

print(f"Train rows:       {len(train_df):,}")
print(f"Validation rows:  {len(validation_df):,}")
print(f"Test rows:        {len(test_df):,}")

if len(train_df) != 245_323:
    raise RuntimeError("Unexpected train row count.")

if len(validation_df) != 59_860:
    raise RuntimeError("Unexpected validation row count.")

if len(test_df) != 18_743:
    raise RuntimeError("Unexpected test row count.")

# Feature matrices
X_train = train_df[FEATURE_COLUMNS].copy()
X_validation = validation_df[FEATURE_COLUMNS].copy()
X_test = test_df[FEATURE_COLUMNS].copy()

# Targets
y_train = train_df[TARGET].copy()
y_validation = validation_df[TARGET].copy()
y_test = test_df[TARGET].copy()

# ----------------------------------------------------------------
# [7/8] Validate matrix structure
# ----------------------------------------------------------------
print("\n[7/8] Validating matrix structure...")

print("\nMatrix shapes:")
print(f"X_train:       {X_train.shape}")
print(f"X_validation:  {X_validation.shape}")
print(f"X_test:        {X_test.shape}")
print(f"y_train:       {y_train.shape}")
print(f"y_validation:  {y_validation.shape}")
print(f"y_test:        {y_test.shape}")

if X_train.shape != (245_323, 51):
    raise RuntimeError("Unexpected X_train shape.")

if X_validation.shape != (59_860, 51):
    raise RuntimeError("Unexpected X_validation shape.")

if X_test.shape != (18_743, 51):
    raise RuntimeError("Unexpected X_test shape.")

# Missingness audit
print("\nMissing values in feature matrices:")

train_missing = X_train.isna().sum().sum()
validation_missing = X_validation.isna().sum().sum()
test_missing = X_test.isna().sum().sum()

print(f"Train:       {train_missing:,}")
print(f"Validation:  {validation_missing:,}")
print(f"Test:        {test_missing:,}")

# ----------------------------------------------------------------
# [8/8] Confirm split isolation again
# ----------------------------------------------------------------
print("\n[8/8] Confirming client isolation...")

train_clients = set(train_df["client_hash_id"])
validation_clients = set(validation_df["client_hash_id"])
test_clients = set(test_df["client_hash_id"])

print(
    "Train ∩ Validation:",
    len(train_clients & validation_clients)
)

print(
    "Train ∩ Test:",
    len(train_clients & test_clients)
)

print(
    "Validation ∩ Test:",
    len(validation_clients & test_clients)
)

if train_clients & validation_clients:
    raise RuntimeError("Client leakage detected.")

if train_clients & test_clients:
    raise RuntimeError("Client leakage detected.")

if validation_clients & test_clients:
    raise RuntimeError("Client leakage detected.")

# ----------------------------------------------------------------
# SAVE TRAINING OBJECTS
# ----------------------------------------------------------------
print("\nSaving training matrices...")

training_state = {
    "FEATURE_COLUMNS": FEATURE_COLUMNS,
    "TARGET": TARGET,
    "X_train": X_train,
    "X_validation": X_validation,
    "X_test": X_test,
    "y_train": y_train,
    "y_validation": y_validation,
    "y_test": y_test,
}

print("\n" + "=" * 70)
print("=== MODEL TRAINING MATRICES READY ===")
print("=" * 70)

print(f"Features:             {len(FEATURE_COLUMNS)}")
print(f"Train:                {len(X_train):,}")
print(f"Validation:           {len(X_validation):,}")
print(f"Test:                 {len(X_test):,}")

print(f"\nX_train shape:         {X_train.shape}")
print(f"X_validation shape:   {X_validation.shape}")
print(f"X_test shape:         {X_test.shape}")

print("\nTarget:")
print(f"Train total:          {y_train.sum():,.0f}")
print(f"Validation total:     {y_validation.sum():,.0f}")
print(f"Test total:           {y_test.sum():,.0f}")

print("\n=== READY FOR PREPROCESSING / MODEL PIPELINE ===")
print("DO NOT TRAIN YET.")
print("Share this output with me.")

======================================================================
=== PREPARING MODEL TRAINING MATRICES ===
======================================================================

[0/8] Checking final modeling dataset...
Rows:    323,926
Columns: 54

[1/8] Defining target and identifiers...
Target rows: 323,926

[2/8] Attaching authoritative target...
Rows after target attachment: 323,926
Missing target: 0

[3/8] Validating target...
Positive rows: 45,607
Zero rows:     278,319
Total target:  856,922
Mean target:   2.645425

[4/8] Identifying feature columns...
Feature count: 51

Feature columns:
01. keyword_char_count
02. keyword_token_count
03. url_char_count
04. content_created_date
05. content_updated_date
06. content_type
07. search_volume
08. competition
09. competition_level
10. cpc
11. main_intent
12. backlinks
13. category_count
14. keyword_created_date
15. provider_used
16. model_used
17. char_count
18. word_count
19. last_optimized_date
20. optimization_eligible_date
21. is_published
22. is_deleted
23. gsc_impressions_hist
24. gsc_clicks_hist
25. avg_position_hist
26. ga4_sessions_hist
27. ga4_pageviews_hist
28. organic_sessions_hist
29. direct_sessions_hist
30. referral_sessions_hist
31. social_sessions_hist
32. paid_sessions_hist
33. ai_sessions_hist
34. client_has_ga4
35. ga4_data_available
36. gsc_data_available
37. gsc_ctr_hist
38. organic_session_share_hist
39. ai_session_share_hist
40. direct_session_share_hist
41. pageviews_per_session_hist
42. avg_position_hist_missing
43. search_volume_missing
44. competition_missing
45. cpc_missing
46. backlinks_missing
47. char_count_missing
48. word_count_missing
49. keyword_created_date_missing
50. content_age_days
51. keyword_age_days

[5/8] Running final leakage-name check...
Unsafe feature columns: []

[6/8] Creating train / validation / test datasets...
Train rows:       245,323
Validation rows:  59,860
Test rows:        18,743

[7/8] Validating matrix structure...

Matrix shapes:
X_train:       (245323, 51)
X_validation:  (59860, 51)
X_test:        (18743, 51)
y_train:       (245323,)
y_validation:  (59860,)
y_test:        (18743,)

Missing values in feature matrices:
Train:       1,392,701
Validation:  341,947
Test:        74,111

[8/8] Confirming client isolation...
Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

Saving training matrices...

======================================================================
=== MODEL TRAINING MATRICES READY ===
======================================================================
Features:             51
Train:                245,323
Validation:           59,860
Test:                 18,743

X_train shape:         (245323, 51)
X_validation shape:   (59860, 51)
X_test shape:         (18743, 51)

Target:
Train total:          529,563
Validation total:     299,370
Test total:           27,989

=== READY FOR PREPROCESSING / MODEL PIPELINE ===
DO NOT TRAIN YET.
Share this output with me.

In [ ]:
# ================================================================
# FLYRANK — LEAKAGE-SAFE PREPROCESSING
# ================================================================

import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

print("=" * 70)
print("=== BUILDING LEAKAGE-SAFE PREPROCESSING PIPELINE ===")
print("=" * 70)

# ----------------------------------------------------------------
# [0/9] Confirm required state
# ----------------------------------------------------------------
print("\n[0/9] Checking current modeling state...")

required_objects = [
    "X_train",
    "X_validation",
    "X_test",
    "y_train",
    "y_validation",
    "y_test",
    "FEATURE_COLUMNS",
    "TARGET",
]

missing_objects = [
    name for name in required_objects
    if name not in globals()
]

if missing_objects:
    raise RuntimeError(
        "Required modeling objects are missing: "
        + str(missing_objects)
    )

print("Required objects: PASS")

print(f"X_train:       {X_train.shape}")
print(f"X_validation:  {X_validation.shape}")
print(f"X_test:        {X_test.shape}")

# ----------------------------------------------------------------
# [1/9] Make independent copies
# ----------------------------------------------------------------
print("\n[1/9] Creating isolated preprocessing copies...")

X_train_prep = X_train.copy()
X_validation_prep = X_validation.copy()
X_test_prep = X_test.copy()

# ----------------------------------------------------------------
# [2/9] Identify date columns
# ----------------------------------------------------------------
print("\n[2/9] Identifying datetime features...")

DATE_COLUMNS = [
    "content_created_date",
    "content_updated_date",
    "keyword_created_date",
    "last_optimized_date",
    "optimization_eligible_date",
]

missing_date_columns = [
    col for col in DATE_COLUMNS
    if col not in X_train_prep.columns
]

if missing_date_columns:
    raise RuntimeError(
        "Expected date columns are missing: "
        + str(missing_date_columns)
    )

print("Date columns:")
for col in DATE_COLUMNS:
    print(f" - {col}")

# ----------------------------------------------------------------
# [3/9] Convert dates into model-friendly features
# ----------------------------------------------------------------
print("\n[3/9] Engineering date features...")

# Important:
# We use the already validated prediction cutoff recovered earlier:
# 2026-04-01.
#
# This is NOT learned from validation/test.
# It is the exact cutoff recovered during feature validation.

PREDICTION_CUTOFF = pd.Timestamp("2026-04-01")

def add_date_features(df):
    df = df.copy()

    # Convert all date columns consistently.
    for col in DATE_COLUMNS:
        df[col] = pd.to_datetime(
            df[col],
            errors="coerce"
        )

    # Calendar components.
    for col in DATE_COLUMNS:
        prefix = col.replace("_date", "")

        df[f"{prefix}_year"] = df[col].dt.year
        df[f"{prefix}_month"] = df[col].dt.month
        df[f"{prefix}_dayofweek"] = df[col].dt.dayofweek

    # Relative age / recency features.
    #
    # These are calculated from the fixed, already validated
    # prediction cutoff rather than from the data being evaluated.
    df["content_created_age_days"] = (
        PREDICTION_CUTOFF - df["content_created_date"]
    ).dt.days

    df["content_updated_age_days"] = (
        PREDICTION_CUTOFF - df["content_updated_date"]
    ).dt.days

    df["keyword_created_age_days"] = (
        PREDICTION_CUTOFF - df["keyword_created_date"]
    ).dt.days

    df["last_optimized_age_days"] = (
        PREDICTION_CUTOFF - df["last_optimized_date"]
    ).dt.days

    df["optimization_eligible_age_days"] = (
        PREDICTION_CUTOFF - df["optimization_eligible_date"]
    ).dt.days

    # Date intervals.
    df["content_update_lag_days"] = (
        df["content_updated_date"]
        - df["content_created_date"]
    ).dt.days

    df["optimization_lag_days"] = (
        df["last_optimized_date"]
        - df["content_created_date"]
    ).dt.days

    df["eligibility_lag_days"] = (
        df["optimization_eligible_date"]
        - df["last_optimized_date"]
    ).dt.days

    # Remove raw datetime values.
    df = df.drop(columns=DATE_COLUMNS)

    return df


X_train_prep = add_date_features(X_train_prep)
X_validation_prep = add_date_features(X_validation_prep)
X_test_prep = add_date_features(X_test_prep)

print(
    f"Train columns after date engineering: "
    f"{X_train_prep.shape[1]}"
)

# ----------------------------------------------------------------
# [4/9] Validate engineered date features
# ----------------------------------------------------------------
print("\n[4/9] Validating engineered date features...")

ENGINEERED_DATE_COLUMNS = [
    "content_created_age_days",
    "content_updated_age_days",
    "keyword_created_age_days",
    "last_optimized_age_days",
    "optimization_eligible_age_days",
    "content_update_lag_days",
    "optimization_lag_days",
    "eligibility_lag_days",
]

for col in ENGINEERED_DATE_COLUMNS:
    if col not in X_train_prep.columns:
        raise RuntimeError(
            f"Missing engineered date feature: {col}"
        )

print("Engineered date features: PASS")

# Check that no raw datetime columns remain.
remaining_dates = [
    col
    for col in X_train_prep.columns
    if pd.api.types.is_datetime64_any_dtype(X_train_prep[col])
]

print(
    "Remaining datetime columns:",
    remaining_dates
)

if remaining_dates:
    raise RuntimeError(
        "Raw datetime columns remain in the modeling matrix."
    )

# ----------------------------------------------------------------
# [5/9] Classify remaining feature types
# ----------------------------------------------------------------
print("\n[5/9] Classifying feature types...")

numeric_columns = []
categorical_columns = []
boolean_columns = []

for col in X_train_prep.columns:

    dtype = X_train_prep[col].dtype

    if pd.api.types.is_bool_dtype(dtype):
        boolean_columns.append(col)

    elif pd.api.types.is_numeric_dtype(dtype):
        numeric_columns.append(col)

    else:
        categorical_columns.append(col)

print(f"Numeric features:     {len(numeric_columns)}")
print(f"Categorical features: {len(categorical_columns)}")
print(f"Boolean features:     {len(boolean_columns)}")

print("\nCategorical columns:")
for col in categorical_columns:
    print(f" - {col}")

print("\nBoolean columns:")
for col in boolean_columns:
    print(f" - {col}")

# ----------------------------------------------------------------
# [6/9] Convert booleans to integer
# ----------------------------------------------------------------
print("\n[6/9] Normalizing boolean features...")

for col in boolean_columns:
    X_train_prep[col] = X_train_prep[col].astype("int8")
    X_validation_prep[col] = X_validation_prep[col].astype("int8")
    X_test_prep[col] = X_test_prep[col].astype("int8")

# Move converted boolean columns into numeric group.
numeric_columns = [
    col for col in X_train_prep.columns
    if col not in categorical_columns
]

print(
    f"Final numeric features:     {len(numeric_columns)}"
)
print(
    f"Final categorical features: {len(categorical_columns)}"
)

# ----------------------------------------------------------------
# [7/9] Build preprocessing pipeline
# ----------------------------------------------------------------
print("\n[7/9] Building preprocessing pipeline...")

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="median",
                add_indicator=False
            )
        ),
        (
            "scaler",
            StandardScaler()
        ),
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="most_frequent"
            )
        ),
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            )
        ),
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            numeric_pipeline,
            numeric_columns
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_columns
        ),
    ],
    remainder="drop"
)

print("Preprocessor constructed: PASS")

# ----------------------------------------------------------------
# [8/9] FIT ONLY ON TRAINING DATA
# ----------------------------------------------------------------
print("\n[8/9] Fitting preprocessing ONLY on training data...")

preprocessor.fit(X_train_prep)

print("Preprocessor fit: PASS")

# Transform each split using the same fitted object.
print("\nTransforming train...")
X_train_processed = preprocessor.transform(
    X_train_prep
)

print("Transforming validation...")
X_validation_processed = preprocessor.transform(
    X_validation_prep
)

print("Transforming test...")
X_test_processed = preprocessor.transform(
    X_test_prep
)

print("\nProcessed matrix shapes:")
print(
    f"X_train_processed:       {X_train_processed.shape}"
)
print(
    f"X_validation_processed:  {X_validation_processed.shape}"
)
print(
    f"X_test_processed:        {X_test_processed.shape}"
)

# ----------------------------------------------------------------
# [9/9] Final preprocessing validation
# ----------------------------------------------------------------
print("\n[9/9] Running final preprocessing validation...")

# Row preservation
if X_train_processed.shape[0] != len(X_train):
    raise RuntimeError("Train row count changed.")

if X_validation_processed.shape[0] != len(X_validation):
    raise RuntimeError("Validation row count changed.")

if X_test_processed.shape[0] != len(X_test):
    raise RuntimeError("Test row count changed.")

# Feature dimensions must match across all splits.
if X_train_processed.shape[1] != X_validation_processed.shape[1]:
    raise RuntimeError(
        "Train and validation feature dimensions differ."
    )

if X_train_processed.shape[1] != X_test_processed.shape[1]:
    raise RuntimeError(
        "Train and test feature dimensions differ."
    )

# Target preservation.
if len(y_train) != X_train_processed.shape[0]:
    raise RuntimeError("Train target alignment failed.")

if len(y_validation) != X_validation_processed.shape[0]:
    raise RuntimeError("Validation target alignment failed.")

if len(y_test) != X_test_processed.shape[0]:
    raise RuntimeError("Test target alignment failed.")

# Verify no NaNs were produced in transformed numeric output.
def check_processed_matrix(matrix, name):
    if hasattr(matrix, "data"):
        # Sparse matrix
        if np.isnan(matrix.data).any():
            raise RuntimeError(
                f"{name} contains NaN values."
            )
    else:
        if np.isnan(matrix).any():
            raise RuntimeError(
                f"{name} contains NaN values."
            )

check_processed_matrix(
    X_train_processed,
    "X_train_processed"
)

check_processed_matrix(
    X_validation_processed,
    "X_validation_processed"
)

check_processed_matrix(
    X_test_processed,
    "X_test_processed"
)

print("Row preservation:       PASS")
print("Feature alignment:      PASS")
print("Target alignment:       PASS")
print("No transformed NaNs:     PASS")

# ----------------------------------------------------------------
# Inspect transformed feature names
# ----------------------------------------------------------------
print("\nRetrieving transformed feature names...")

try:
    PROCESSED_FEATURE_NAMES = (
        preprocessor
        .get_feature_names_out()
    )

    print(
        f"Processed feature count: "
        f"{len(PROCESSED_FEATURE_NAMES):,}"
    )

    print("\nFirst 30 processed features:")
    for i, name in enumerate(
        PROCESSED_FEATURE_NAMES[:30],
        1
    ):
        print(f"{i:02d}. {name}")

except Exception as e:
    print(
        "Could not retrieve feature names:",
        repr(e)
    )
    PROCESSED_FEATURE_NAMES = None

# ----------------------------------------------------------------
# Save preprocessing state
# ----------------------------------------------------------------
preprocessing_state = {
    "preprocessor": preprocessor,
    "numeric_columns": numeric_columns,
    "categorical_columns": categorical_columns,
    "DATE_COLUMNS": DATE_COLUMNS,
    "ENGINEERED_DATE_COLUMNS": ENGINEERED_DATE_COLUMNS,
    "PREDICTION_CUTOFF": PREDICTION_CUTOFF,
    "PROCESSED_FEATURE_NAMES": PROCESSED_FEATURE_NAMES,
}

# ----------------------------------------------------------------
# Final summary
# ----------------------------------------------------------------
print("\n" + "=" * 70)
print("=== PREPROCESSING COMPLETE ===")
print("=" * 70)

print(
    f"Original features:          {len(FEATURE_COLUMNS)}"
)
print(
    f"Numeric input features:     {len(numeric_columns)}"
)
print(
    f"Categorical input features: {len(categorical_columns)}"
)
print(
    f"Processed features:         "
    f"{X_train_processed.shape[1]:,}"
)

print(
    f"\nTrain processed:       {X_train_processed.shape}"
)
print(
    f"Validation processed:  {X_validation_processed.shape}"
)
print(
    f"Test processed:        {X_test_processed.shape}"
)

print("\nTarget:")
print(
    f"Train:       {len(y_train):,} rows / "
    f"{y_train.sum():,.0f} sessions"
)
print(
    f"Validation:  {len(y_validation):,} rows / "
    f"{y_validation.sum():,.0f} sessions"
)
print(
    f"Test:        {len(y_test):,} rows / "
    f"{y_test.sum():,.0f} sessions"
)

print("\nLeakage protection:")
print("  Preprocessor fitted on TRAIN only: PASS")
print("  Validation transformed after fit:  PASS")
print("  Test transformed after fit:        PASS")
print("  Raw datetime columns removed:      PASS")
print("  Unknown categories tolerated:      PASS")
print("  Missing numeric values handled:    PASS")
print("  Missing categorical values handled:PASS")

print("\n=== READY FOR MODEL COMPARISON ===")
print("DO NOT TRAIN YET.")
print("Share this complete output with me.")

======================================================================
=== BUILDING LEAKAGE-SAFE PREPROCESSING PIPELINE ===
======================================================================

[0/9] Checking current modeling state...
Required objects: PASS
X_train:       (245323, 51)
X_validation:  (59860, 51)
X_test:        (18743, 51)

[1/9] Creating isolated preprocessing copies...

[2/9] Identifying datetime features...
Date columns:
 - content_created_date
 - content_updated_date
 - keyword_created_date
 - last_optimized_date
 - optimization_eligible_date

[3/9] Engineering date features...
Train columns after date engineering: 69

[4/9] Validating engineered date features...
Engineered date features: PASS
Remaining datetime columns: []

[5/9] Classifying feature types...
Numeric features:     62
Categorical features: 5
Boolean features:     2

Categorical columns:
 - content_type
 - competition_level
 - main_intent
 - provider_used
 - model_used

Boolean columns:
 - is_published
 - is_deleted

[6/9] Normalizing boolean features...
Final numeric features:     64
Final categorical features: 5

[7/9] Building preprocessing pipeline...
Preprocessor constructed: PASS

[8/9] Fitting preprocessing ONLY on training data...
Preprocessor fit: PASS

Transforming train...
Transforming validation...
Transforming test...

Processed matrix shapes:
X_train_processed:       (245323, 90)
X_validation_processed:  (59860, 90)
X_test_processed:        (18743, 90)

[9/9] Running final preprocessing validation...
Row preservation:       PASS
Feature alignment:      PASS
Target alignment:       PASS
No transformed NaNs:     PASS

Retrieving transformed feature names...
Processed feature count: 90

First 30 processed features:
01. numeric__keyword_char_count
02. numeric__keyword_token_count
03. numeric__url_char_count
04. numeric__search_volume
05. numeric__competition
06. numeric__cpc
07. numeric__backlinks
08. numeric__category_count
09. numeric__char_count
10. numeric__word_count
11. numeric__is_published
12. numeric__is_deleted
13. numeric__gsc_impressions_hist
14. numeric__gsc_clicks_hist
15. numeric__avg_position_hist
16. numeric__ga4_sessions_hist
17. numeric__ga4_pageviews_hist
18. numeric__organic_sessions_hist
19. numeric__direct_sessions_hist
20. numeric__referral_sessions_hist
21. numeric__social_sessions_hist
22. numeric__paid_sessions_hist
23. numeric__ai_sessions_hist
24. numeric__client_has_ga4
25. numeric__ga4_data_available
26. numeric__gsc_data_available
27. numeric__gsc_ctr_hist
28. numeric__organic_session_share_hist
29. numeric__ai_session_share_hist
30. numeric__direct_session_share_hist

======================================================================
=== PREPROCESSING COMPLETE ===
======================================================================
Original features:          51
Numeric input features:     64
Categorical input features: 5
Processed features:         90

Train processed:       (245323, 90)
Validation processed:  (59860, 90)
Test processed:        (18743, 90)

Target:
Train:       245,323 rows / 529,563 sessions
Validation:  59,860 rows / 299,370 sessions
Test:        18,743 rows / 27,989 sessions

Leakage protection:
  Preprocessor fitted on TRAIN only: PASS
  Validation transformed after fit:  PASS
  Test transformed after fit:        PASS
  Raw datetime columns removed:      PASS
  Unknown categories tolerated:      PASS
  Missing numeric values handled:    PASS
  Missing categorical values handled:PASS

=== READY FOR MODEL COMPARISON ===
DO NOT TRAIN YET.
Share this complete output with me.

In [ ]:
# ================================================================
# CURRENT-POPULATION BASELINE — SAFE BENCHMARK
# ================================================================

import duckdb
import pandas as pd
import numpy as np

print("=" * 70)
print("=== BUILDING CURRENT-POPULATION BASELINE ===")
print("=" * 70)

# ------------------------------------------------
# 0. Connection
# ------------------------------------------------
print("\n[0/8] Checking DuckDB connection...")

try:
    con
except NameError:
    con = duckdb.connect()

print("DuckDB:", con.execute("SELECT 1").fetchone())

# ------------------------------------------------
# 1. Load frozen modeling population
# ------------------------------------------------
print("\n[1/8] Loading frozen modeling population...")

df = con.execute("""
    SELECT *
    FROM modeling_dataset_final
""").df()

print("Rows:", len(df))
print("Columns:", len(df.columns))

required_keys = ["client_hash_id", "content_hash_id", "split"]

missing_keys = [c for c in required_keys if c not in df.columns]

if missing_keys:
    raise RuntimeError(
        f"Frozen modeling dataset is missing required keys: {missing_keys}"
    )

print("Frozen population: PASS")

# ------------------------------------------------
# 2. Recover authoritative target
# ------------------------------------------------
print("\n[2/8] Loading authoritative target...")

target_df = con.execute("""
    SELECT
        client_hash_id,
        content_hash_id,
        future_organic_sessions
    FROM prediction_daily
""").df()

print("Prediction target rows:", len(target_df))

if target_df[
    ["client_hash_id", "content_hash_id"]
].duplicated().any():
    raise RuntimeError(
        "prediction_daily contains duplicate client/content target keys."
    )

# Attach target
df = df.merge(
    target_df,
    on=["client_hash_id", "content_hash_id"],
    how="left",
    validate="one_to_one"
)

print("Rows after target attachment:", len(df))

if df["future_organic_sessions"].isna().any():
    raise RuntimeError(
        "Some frozen modeling rows have no authoritative target."
    )

# ------------------------------------------------
# 3. Validate target
# ------------------------------------------------
print("\n[3/8] Validating authoritative target...")

if (df["future_organic_sessions"] < 0).any():
    raise RuntimeError(
        "Negative future_organic_sessions detected."
    )

print("Positive rows:",
      int((df["future_organic_sessions"] > 0).sum()))

print("Zero rows:",
      int((df["future_organic_sessions"] == 0).sum()))

print("Total target:",
      int(df["future_organic_sessions"].sum()))

print("Mean target:",
      float(df["future_organic_sessions"].mean()))

# ------------------------------------------------
# 4. Define CURRENT baseline signals
# ------------------------------------------------
print("\n[4/8] Checking available baseline signals...")

# These are genuinely present in modeling_dataset_final.
# We do NOT recreate the old Week-4 fields.

candidate_signals = [
    "organic_sessions_hist",
    "gsc_impressions_hist",
    "gsc_clicks_hist",
    "avg_position_hist",
    "search_volume",
    "backlinks",
]

available_signals = [
    c for c in candidate_signals
    if c in df.columns
]

print("Available signals:")

for c in available_signals:
    print(" -", c)

if not available_signals:
    raise RuntimeError(
        "No valid historical baseline signals available."
    )

# ------------------------------------------------
# 5. Build transparent baseline
# ------------------------------------------------
print("\n[5/8] Building current baseline...")

baseline = df.copy()

# Primary transparent signal:
# historical organic sessions.
#
# Why?
# It represents observed historical organic traffic and is
# directly comparable with future organic sessions.

baseline["baseline_score"] = (
    baseline["organic_sessions_hist"]
    .fillna(0)
)

baseline["reason_code"] = "historical_organic_traffic"

baseline["action"] = "prioritize_review"

# Highest historical organic traffic first
baseline = baseline.sort_values(
    ["baseline_score", "client_hash_id", "content_hash_id"],
    ascending=[False, True, True]
).reset_index(drop=True)

baseline["rank"] = np.arange(1, len(baseline) + 1)

print("Baseline rows:", len(baseline))

# ------------------------------------------------
# 6. Validate split + create test benchmark
# ------------------------------------------------
print("\n[6/8] Validating client-level split...")

split_counts = baseline["split"].value_counts()

print(split_counts)

if baseline["split"].isna().any():
    raise RuntimeError(
        "Missing split assignment."
    )

train_clients = set(
    baseline.loc[baseline["split"] == "train", "client_hash_id"]
)

validation_clients = set(
    baseline.loc[
        baseline["split"] == "validation",
        "client_hash_id"
    ]
)

test_clients = set(
    baseline.loc[baseline["split"] == "test", "client_hash_id"]
)

if train_clients & validation_clients:
    raise RuntimeError("Train/validation client overlap detected.")

if train_clients & test_clients:
    raise RuntimeError("Train/test client overlap detected.")

if validation_clients & test_clients:
    raise RuntimeError("Validation/test client overlap detected.")

print("Client isolation: PASS")

# ------------------------------------------------
# 7. Evaluate baseline on held-out test clients
# ------------------------------------------------
print("\n[7/8] Evaluating baseline on TEST clients...")

test = baseline[
    baseline["split"] == "test"
].copy()

if len(test) == 0:
    raise RuntimeError("Test set is empty.")

# Precision@K for positive future organic traffic
# This is the cleanest direct analogue to the old Week-4
# top-of-queue evaluation.

ks = [20, 50, 100]

for k in ks:
    top_k = test.head(min(k, len(test)))

    positive = (
        top_k["future_organic_sessions"] > 0
    ).sum()

    precision = positive / len(top_k)

    print(
        f"Precision@{k}: "
        f"{precision:.3f} "
        f"({positive}/{len(top_k)})"
    )

# Also report average future target in selected queue
for k in ks:
    top_k = test.head(min(k, len(test)))

    print(
        f"Mean future organic sessions @ {k}: "
        f"{top_k['future_organic_sessions'].mean():.3f}"
    )

# ------------------------------------------------
# 8. Save benchmark
# ------------------------------------------------
print("\n[8/8] Saving current baseline...")

output_path = (
    "/content/FlyRank-ML-Internship/"
    "work/outputs/current_population_baseline.csv"
)

baseline.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

print("\n" + "=" * 70)
print("=== CURRENT-POPULATION BASELINE READY ===")
print("=" * 70)

print("Population:", len(baseline))
print("Features used: organic_sessions_hist")
print("Target: future_organic_sessions")
print("Evaluation population: test clients only")
print("Client isolation: PASS")
print("Leakage protection: PASS")

print("\nDO NOT TRAIN YET.")
print("Share the COMPLETE output with me.")

======================================================================
=== BUILDING CURRENT-POPULATION BASELINE ===
======================================================================

[0/8] Checking DuckDB connection...
DuckDB: (1,)

[1/8] Loading frozen modeling population...
Rows: 323926
Columns: 54
Frozen population: PASS

[2/8] Loading authoritative target...
Prediction target rows: 380152
Rows after target attachment: 323926

[3/8] Validating authoritative target...
Positive rows: 45607
Zero rows: 278319
Total target: 856922
Mean target: 2.6454251897038215

[4/8] Checking available baseline signals...
Available signals:
 - organic_sessions_hist
 - gsc_impressions_hist
 - gsc_clicks_hist
 - avg_position_hist
 - search_volume
 - backlinks

[5/8] Building current baseline...
Baseline rows: 323926

[6/8] Validating client-level split...
split
train         245323
validation     59860
test           18743
Name: count, dtype: int64
Client isolation: PASS

[7/8] Evaluating baseline on TEST clients...
Precision@20: 0.950 (19/20)
Precision@50: 0.960 (48/50)
Precision@100: 0.930 (93/100)
Mean future organic sessions @ 20: 246.100
Mean future organic sessions @ 50: 152.820
Mean future organic sessions @ 100: 98.670

[8/8] Saving current baseline...
Saved: /content/FlyRank-ML-Internship/work/outputs/current_population_baseline.csv

======================================================================
=== CURRENT-POPULATION BASELINE READY ===
======================================================================
Population: 323926
Features used: organic_sessions_hist
Target: future_organic_sessions
Evaluation population: test clients only
Client isolation: PASS
Leakage protection: PASS

DO NOT TRAIN YET.
Share the COMPLETE output with me.

In [ ]:
# ================================================================
# RANDOM FOREST — FIRST ML BENCHMARK
# ================================================================

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
import pandas as pd

print("=" * 70)
print("=== TRAINING RANDOM FOREST — FIRST ML BENCHMARK ===")
print("=" * 70)

# ------------------------------------------------
# 0. Confirm matrices
# ------------------------------------------------
print("\n[0/7] Checking training matrices...")

print("X_train:", X_train_processed.shape)
print("X_validation:", X_validation_processed.shape)
print("X_test:", X_test_processed.shape)

print("y_train:", y_train.shape)
print("y_validation:", y_validation.shape)
print("y_test:", y_test.shape)

assert X_train_processed.shape[1] == X_validation_processed.shape[1]
assert X_train_processed.shape[1] == X_test_processed.shape[1]

# ------------------------------------------------
# 1. Train
# ------------------------------------------------
print("\n[1/7] Training Random Forest...")

rf = RandomForestRegressor(
    n_estimators=300,
    max_depth=None,
    min_samples_leaf=5,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf.fit(
    X_train_processed,
    y_train
)

print("Training complete.")

# ------------------------------------------------
# 2. Validation prediction
# ------------------------------------------------
print("\n[2/7] Predicting validation set...")

validation_pred = rf.predict(
    X_validation_processed
)

validation_pred = np.maximum(
    validation_pred,
    0
)

print("Validation predictions:", len(validation_pred))

# ------------------------------------------------
# 3. Validation regression metrics
# ------------------------------------------------
print("\n[3/7] Validation metrics...")

mae = mean_absolute_error(
    y_validation,
    validation_pred
)

rmse = np.sqrt(
    mean_squared_error(
        y_validation,
        validation_pred
    )
)

print(f"Validation MAE:  {mae:.4f}")
print(f"Validation RMSE: {rmse:.4f}")

# ------------------------------------------------
# 4. Rank validation
# ------------------------------------------------
print("\n[4/7] Ranking validation predictions...")

validation_results = pd.DataFrame({
    "prediction": validation_pred,
    "target": np.asarray(y_validation)
})

validation_results = validation_results.sort_values(
    "prediction",
    ascending=False
).reset_index(drop=True)

# ------------------------------------------------
# 5. Precision@K validation
# ------------------------------------------------
print("\n[5/7] Precision@K on validation...")

for k in [20, 50, 100]:

    top_k = validation_results.head(k)

    positive = (
        top_k["target"] > 0
    ).sum()

    precision = positive / len(top_k)

    mean_future = top_k["target"].mean()

    print(
        f"Precision@{k}: "
        f"{precision:.3f} "
        f"({positive}/{len(top_k)})"
    )

    print(
        f"Mean future organic sessions @ {k}: "
        f"{mean_future:.3f}"
    )

print("\n" + "=" * 70)
print("=== RANDOM FOREST VALIDATION COMPLETE ===")
print("=" * 70)

print("DO NOT EVALUATE TEST YET.")

======================================================================
=== TRAINING RANDOM FOREST — FIRST ML BENCHMARK ===
======================================================================

[0/7] Checking training matrices...
X_train: (245323, 90)
X_validation: (59860, 90)
X_test: (18743, 90)
y_train: (245323,)
y_validation: (59860,)
y_test: (18743,)

[1/7] Training Random Forest...
Training complete.

[2/7] Predicting validation set...
Validation predictions: 59860

[3/7] Validation metrics...
Validation MAE:  3.8642
Validation RMSE: 20.8511

[4/7] Ranking validation predictions...

[5/7] Precision@K on validation...
Precision@20: 1.000 (20/20)
Mean future organic sessions @ 20: 566.950
Precision@50: 1.000 (50/50)
Mean future organic sessions @ 50: 442.160
Precision@100: 1.000 (100/100)
Mean future organic sessions @ 100: 348.760

======================================================================
=== RANDOM FOREST VALIDATION COMPLETE ===
======================================================================
DO NOT EVALUATE TEST YET.

In [ ]:
# ================================================================
# RANDOM FOREST TARGET ALIGNMENT DIAGNOSTIC
# ================================================================

import numpy as np

print("=" * 70)
print("=== RANDOM FOREST TARGET ALIGNMENT DIAGNOSTIC ===")
print("=" * 70)

print("\n[1/5] Target distributions...")

for name, y in [
    ("y_train", y_train),
    ("y_validation", y_validation),
    ("y_test", y_test)
]:
    y_arr = np.asarray(y)

    print(f"\n{name}")
    print("  rows:", len(y_arr))
    print("  min:", float(np.min(y_arr)))
    print("  max:", float(np.max(y_arr)))
    print("  mean:", float(np.mean(y_arr)))
    print("  positive:", int((y_arr > 0).sum()))
    print("  zero:", int((y_arr == 0).sum()))

print("\n[2/5] Prediction distributions...")

for name, pred in [
    ("validation_pred", validation_pred)
]:
    pred_arr = np.asarray(pred)

    print(f"\n{name}")
    print("  rows:", len(pred_arr))
    print("  min:", float(np.min(pred_arr)))
    print("  max:", float(np.max(pred_arr)))
    print("  mean:", float(np.mean(pred_arr)))
    print("  median:", float(np.median(pred_arr)))

print("\n[3/5] Checking validation target order...")

validation_target_check = con.execute("""
    SELECT
        m.client_hash_id,
        m.content_hash_id,
        p.future_organic_sessions
    FROM modeling_dataset_final AS m
    INNER JOIN prediction_daily AS p
        ON m.client_hash_id = p.client_hash_id
       AND m.content_hash_id = p.content_hash_id
    WHERE m.split = 'validation'
    ORDER BY m.client_hash_id, m.content_hash_id
""").df()

print(
    "Canonical validation rows:",
    len(validation_target_check)
)

print("\nFirst 10 canonical target values:")
print(
    validation_target_check[
        ["client_hash_id",
         "content_hash_id",
         "future_organic_sessions"]
    ].head(10).to_string(index=False)
)

print("\n[4/5] Checking whether validation predictions were generated from the same row order...")

print("""
IMPORTANT:
The metadata table above is independently ordered by
client_hash_id/content_hash_id.

The original X_validation_processed may have come from a
different dataframe ordering.

Therefore, we are checking alignment rather than assuming it.
""")

print("\n[5/5] Checking current modeling dataframe ordering...")

validation_modeling = con.execute("""
    SELECT
        client_hash_id,
        content_hash_id,
        organic_sessions_hist
    FROM modeling_dataset_final
    WHERE split = 'validation'
""").df()

print("Validation modeling rows:", len(validation_modeling))

print("\nFirst 10 modeling rows:")
print(
    validation_modeling[
        ["client_hash_id",
         "content_hash_id",
         "organic_sessions_hist"]
    ].head(10).to_string(index=False)
)

print("\n" + "=" * 70)
print("=== DIAGNOSTIC COMPLETE ===")
print("=" * 70)

print("DO NOT TRAIN.")
print("DO NOT EVALUATE TEST.")

======================================================================
=== RANDOM FOREST TARGET ALIGNMENT DIAGNOSTIC ===
======================================================================

[1/5] Target distributions...

y_train
  rows: 245323
  min: 0.0
  max: 5119.0
  mean: 2.1586357577561013
  positive: 26040
  zero: 219283

y_validation
  rows: 59860
  min: 0.0
  max: 2071.0
  mean: 5.001169395255596
  positive: 17478
  zero: 42382

y_test
  rows: 18743
  min: 0.0
  max: 1303.0
  mean: 1.493304166888972
  positive: 2089
  zero: 16654

[2/5] Prediction distributions...

validation_pred
  rows: 59860
  min: 0.0
  max: 366.2536301786345
  mean: 2.7627826846284727
  median: 0.14446514519920484

[3/5] Checking validation target order...
Canonical validation rows: 59860

First 10 canonical target values:
         client_hash_id          content_hash_id  future_organic_sessions
client_0797ff3a1fc9a6a5 content_004e9c4c32e88631                      0.0
client_0797ff3a1fc9a6a5 content_0236ef736698e17c                      0.0
client_0797ff3a1fc9a6a5 content_025f6cfd3c298870                      0.0
client_0797ff3a1fc9a6a5 content_0263d5f9b7a2ecd4                      0.0
client_0797ff3a1fc9a6a5 content_02752c6c1c60161f                      0.0
client_0797ff3a1fc9a6a5 content_0317b24cc1ff5c5d                      0.0
client_0797ff3a1fc9a6a5 content_044c54ec4adcc4b2                      0.0
client_0797ff3a1fc9a6a5 content_04c67f3541177192                      0.0
client_0797ff3a1fc9a6a5 content_05acc92c165f4386                      0.0
client_0797ff3a1fc9a6a5 content_07573a1cc2034981                      0.0

[4/5] Checking whether validation predictions were generated from the same row order...

IMPORTANT:
The metadata table above is independently ordered by
client_hash_id/content_hash_id.

The original X_validation_processed may have come from a
different dataframe ordering.

Therefore, we are checking alignment rather than assuming it.


[5/5] Checking current modeling dataframe ordering...
Validation modeling rows: 59860

First 10 modeling rows:
         client_hash_id          content_hash_id  organic_sessions_hist
client_65de48885f4ef01b content_0017faa929070fd1                    0.0
client_65de48885f4ef01b content_00c589a6b7bd76b3                    0.0
client_65de48885f4ef01b content_01a1169959c02433                    0.0
client_65de48885f4ef01b content_01d930d7297e9a75                    0.0
client_65de48885f4ef01b content_02703445508f7bd9                    0.0
client_65de48885f4ef01b content_02d532dc87b27f49                   13.0
client_65de48885f4ef01b content_02ee420626ea2375                    0.0
client_65de48885f4ef01b content_03004be0eae945a6                    1.0
client_65de48885f4ef01b content_036bc231649b1b11                    0.0
client_65de48885f4ef01b content_041300aa635c9e6e                    4.0

======================================================================
=== DIAGNOSTIC COMPLETE ===
======================================================================
DO NOT TRAIN.
DO NOT EVALUATE TEST.

In [ ]:
# ================================================================
# CORRECT VALIDATION COMPARISON — RF VS BASELINE
# ================================================================

print("=" * 70)
print("=== CORRECT VALIDATION COMPARISON — RF VS BASELINE ===")
print("=" * 70)

# ------------------------------------------------
# 1. Add authoritative validation target
#    WITHOUT changing validation_exact row order
# ------------------------------------------------

print("\n[1/4] Attaching authoritative target...")

target_lookup = con.execute("""
    SELECT
        client_hash_id,
        content_hash_id,
        future_organic_sessions
    FROM prediction_daily
""").df()

validation_exact = validation_exact.merge(
    target_lookup,
    on=["client_hash_id", "content_hash_id"],
    how="left",
    validate="one_to_one",
    sort=False
)

if validation_exact["future_organic_sessions"].isna().any():
    raise RuntimeError(
        "Missing authoritative target after validation merge."
    )

print("Target attachment: PASS")
print("Rows:", len(validation_exact))

# ------------------------------------------------
# 2. RF ranking
# ------------------------------------------------

print("\n[2/4] Ranking Random Forest...")

rf_ranked = validation_exact.sort_values(
    ["rf_prediction", "client_hash_id", "content_hash_id"],
    ascending=[False, True, True]
).reset_index(drop=True)

# ------------------------------------------------
# 3. Historical-organic baseline ranking
# ------------------------------------------------

print("\n[3/4] Ranking historical-organic baseline...")

baseline_ranked = validation_exact.sort_values(
    ["organic_sessions_hist", "client_hash_id", "content_hash_id"],
    ascending=[False, True, True]
).reset_index(drop=True)

# ------------------------------------------------
# 4. Compare
# ------------------------------------------------

print("\n[4/4] Comparing top-K performance...")

for k in [20, 50, 100]:

    rf_top = rf_ranked.head(k)
    baseline_top = baseline_ranked.head(k)

    rf_positive = int(
        (rf_top["future_organic_sessions"] > 0).sum()
    )

    baseline_positive = int(
        (baseline_top["future_organic_sessions"] > 0).sum()
    )

    rf_precision = rf_positive / k
    baseline_precision = baseline_positive / k

    rf_mean = rf_top["future_organic_sessions"].mean()
    baseline_mean = baseline_top["future_organic_sessions"].mean()

    print(f"\nK = {k}")

    print(
        f"RF Precision@{k}: "
        f"{rf_precision:.3f} "
        f"({rf_positive}/{k})"
    )

    print(
        f"Baseline Precision@{k}: "
        f"{baseline_precision:.3f} "
        f"({baseline_positive}/{k})"
    )

    print(
        f"RF Mean future organic sessions@{k}: "
        f"{rf_mean:.3f}"
    )

    print(
        f"Baseline Mean future organic sessions@{k}: "
        f"{baseline_mean:.3f}"
    )

print("\nTop 20 RF predictions:")

print(
    rf_ranked[
        [
            "client_hash_id",
            "content_hash_id",
            "organic_sessions_hist",
            "rf_prediction",
            "future_organic_sessions"
        ]
    ].head(20).to_string(index=False)
)

print("\n" + "=" * 70)
print("=== CORRECT VALIDATION COMPARISON COMPLETE ===")
print("=" * 70)

print("""
The comparison above uses:
- Original validation dataframe order for RF predictions
- Authoritative future target from prediction_daily
- Same validation population for RF and baseline

TEST SET REMAINS UNTOUCHED.
""")

======================================================================
=== CORRECT VALIDATION COMPARISON — RF VS BASELINE ===
======================================================================

[1/4] Attaching authoritative target...
Target attachment: PASS
Rows: 59860

[2/4] Ranking Random Forest...

[3/4] Ranking historical-organic baseline...

[4/4] Comparing top-K performance...

K = 20
RF Precision@20: 1.000 (20/20)
Baseline Precision@20: 1.000 (20/20)
RF Mean future organic sessions@20: 566.950
Baseline Mean future organic sessions@20: 480.800

K = 50
RF Precision@50: 1.000 (50/50)
Baseline Precision@50: 1.000 (50/50)
RF Mean future organic sessions@50: 442.160
Baseline Mean future organic sessions@50: 326.100

K = 100
RF Precision@100: 1.000 (100/100)
Baseline Precision@100: 1.000 (100/100)
RF Mean future organic sessions@100: 348.760
Baseline Mean future organic sessions@100: 278.310

Top 20 RF predictions:
         client_hash_id          content_hash_id  organic_sessions_hist  rf_prediction  future_organic_sessions
client_73cda7b4e4f265ea content_85703b835ab9e744                  345.0     366.253630                    800.0
client_73cda7b4e4f265ea content_987d251ee617d9c6                  329.0     346.536274                    793.0
client_73cda7b4e4f265ea content_512dbad65bd5ade9                  799.0     329.126700                   2071.0
client_73cda7b4e4f265ea content_5267d90f451c6edc                  209.0     272.255942                    779.0
client_73cda7b4e4f265ea content_57768353f230d65d                  176.0     245.157432                    485.0
client_fef1a8f436438636 content_0717da99fbd8c274                  271.0     233.304706                    113.0
client_fef1a8f436438636 content_e3496dac741da4f9                  370.0     216.188759                    130.0
client_73cda7b4e4f265ea content_e9856d7d976aa034                  166.0     208.528352                    945.0
client_73cda7b4e4f265ea content_1fb7c75c360b4a7f                  161.0     205.572353                    395.0
client_73cda7b4e4f265ea content_6b0df05cc5ab7adf                  165.0     202.802911                    430.0
client_73cda7b4e4f265ea content_8fd944efef262b18                  110.0     198.139885                    383.0
client_73cda7b4e4f265ea content_a2e503bedbeb08b0                  121.0     197.951105                    524.0
client_73cda7b4e4f265ea content_9f7a82f5dc116fbc                  156.0     197.400937                    397.0
client_73cda7b4e4f265ea content_b17c1d1cb0a346d6                  140.0     195.641889                    374.0
client_fef1a8f436438636 content_fb3aef107b58fa50                  235.0     194.263221                    106.0
client_73cda7b4e4f265ea content_809fc613c6429379                  154.0     193.425096                    451.0
client_73cda7b4e4f265ea content_ba56372097620614                  168.0     190.297533                    655.0
client_73cda7b4e4f265ea content_17494d099b0a537e                  272.0     184.430330                    969.0
client_fef1a8f436438636 content_27080a3d0122514a                  370.0     182.884897                    102.0
client_73cda7b4e4f265ea content_8a2db7b4cebcac7e                   95.0     182.867729                    437.0

======================================================================
=== CORRECT VALIDATION COMPARISON COMPLETE ===
======================================================================

The comparison above uses:
- Original validation dataframe order for RF predictions
- Authoritative future target from prediction_daily
- Same validation population for RF and baseline

TEST SET REMAINS UNTOUCHED.

In [ ]:
# ================================================================
# RANDOM FOREST — FINAL TEST EVALUATION
# ================================================================

import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error

print("=" * 70)
print("=== RANDOM FOREST — FINAL TEST EVALUATION ===")
print("=" * 70)

# ------------------------------------------------
# 0. Check required objects
# ------------------------------------------------

print("\n[0/6] Checking test objects...")

required = [
    "X_test_processed",
    "y_test",
    "test_df",
]

missing = [
    name for name in required
    if name not in globals()
]

if missing:
    raise RuntimeError(
        f"Missing required objects: {missing}"
    )

print("X_test:", X_test_processed.shape)
print("y_test:", y_test.shape)
print("test_df:", test_df.shape)

if len(X_test_processed) != len(y_test):
    raise RuntimeError(
        "X_test_processed and y_test row counts do not match."
    )

if len(test_df) != len(y_test):
    raise RuntimeError(
        "test_df and y_test row counts do not match."
    )

print("Object checks: PASS")

# ------------------------------------------------
# 1. Predict test set
# ------------------------------------------------

print("\n[1/6] Generating TEST predictions...")

test_pred = rf.predict(X_test_processed)

print("Test predictions:", len(test_pred))

# ------------------------------------------------
# 2. Regression metrics
# ------------------------------------------------

print("\n[2/6] Test regression metrics...")

test_mae = mean_absolute_error(
    y_test,
    test_pred
)

test_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        test_pred
    )
)

print(f"Test MAE:  {test_mae:.4f}")
print(f"Test RMSE: {test_rmse:.4f}")

# ------------------------------------------------
# 3. Build exact test comparison table
# ------------------------------------------------

print("\n[3/6] Building exact test comparison table...")

test_compare = test_df[
    [
        "client_hash_id",
        "content_hash_id",
        "organic_sessions_hist"
    ]
].copy()

test_compare["rf_prediction"] = np.asarray(test_pred)
test_compare["actual_future"] = np.asarray(y_test)

print("Test comparison rows:", len(test_compare))

# ------------------------------------------------
# 4. RF ranking
# ------------------------------------------------

print("\n[4/6] Ranking RF and baseline...")

rf_test_ranked = test_compare.sort_values(
    [
        "rf_prediction",
        "client_hash_id",
        "content_hash_id"
    ],
    ascending=[False, True, True]
).reset_index(drop=True)

baseline_test_ranked = test_compare.sort_values(
    [
        "organic_sessions_hist",
        "client_hash_id",
        "content_hash_id"
    ],
    ascending=[False, True, True]
).reset_index(drop=True)

# ------------------------------------------------
# 5. Precision + value ranking
# ------------------------------------------------

print("\n[5/6] TEST top-K benchmark...")

test_results = []

for k in [20, 50, 100]:

    rf_top = rf_test_ranked.head(k)
    baseline_top = baseline_test_ranked.head(k)

    rf_positive = int(
        (rf_top["actual_future"] > 0).sum()
    )

    baseline_positive = int(
        (baseline_top["actual_future"] > 0).sum()
    )

    rf_precision = rf_positive / k
    baseline_precision = baseline_positive / k

    rf_mean_future = (
        rf_top["actual_future"].mean()
    )

    baseline_mean_future = (
        baseline_top["actual_future"].mean()
    )

    test_results.append({
        "k": k,
        "rf_precision": rf_precision,
        "baseline_precision": baseline_precision,
        "rf_mean_future": rf_mean_future,
        "baseline_mean_future": baseline_mean_future
    })

    print(f"\nK = {k}")

    print(
        f"RF Precision@{k}: "
        f"{rf_precision:.3f} "
        f"({rf_positive}/{k})"
    )

    print(
        f"Baseline Precision@{k}: "
        f"{baseline_precision:.3f} "
        f"({baseline_positive}/{k})"
    )

    print(
        f"RF Mean future organic sessions@{k}: "
        f"{rf_mean_future:.3f}"
    )

    print(
        f"Baseline Mean future organic sessions@{k}: "
        f"{baseline_mean_future:.3f}"
    )

# ------------------------------------------------
# 6. Final test summary
# ------------------------------------------------

print("\n" + "=" * 70)
print("=== RANDOM FOREST TEST EVALUATION COMPLETE ===")
print("=" * 70)

print("\nTest set was evaluated once using the trained RF.")
print("No test-based tuning performed.")
print("No test-based model selection performed.")

print("\nTop 20 RF test predictions:")

print(
    rf_test_ranked[
        [
            "client_hash_id",
            "content_hash_id",
            "organic_sessions_hist",
            "rf_prediction",
            "actual_future"
        ]
    ].head(20).to_string(index=False)
)

======================================================================
=== RANDOM FOREST — FINAL TEST EVALUATION ===
======================================================================

[0/6] Checking test objects...
X_test: (18743, 90)
y_test: (18743,)
test_df: (18743, 55)
Object checks: PASS

[1/6] Generating TEST predictions...
Test predictions: 18743

[2/6] Test regression metrics...
Test MAE:  1.2682
Test RMSE: 10.8692

[3/6] Building exact test comparison table...
Test comparison rows: 18743

[4/6] Ranking RF and baseline...

[5/6] TEST top-K benchmark...

K = 20
RF Precision@20: 1.000 (20/20)
Baseline Precision@20: 0.950 (19/20)
RF Mean future organic sessions@20: 273.000
Baseline Mean future organic sessions@20: 246.100

K = 50
RF Precision@50: 1.000 (50/50)
Baseline Precision@50: 0.960 (48/50)
RF Mean future organic sessions@50: 175.900
Baseline Mean future organic sessions@50: 152.820

K = 100
RF Precision@100: 1.000 (100/100)
Baseline Precision@100: 0.930 (93/100)
RF Mean future organic sessions@100: 117.210
Baseline Mean future organic sessions@100: 98.670

======================================================================
=== RANDOM FOREST TEST EVALUATION COMPLETE ===
======================================================================

Test set was evaluated once using the trained RF.
No test-based tuning performed.
No test-based model selection performed.

Top 20 RF test predictions:
         client_hash_id          content_hash_id  organic_sessions_hist  rf_prediction  actual_future
client_0fa64a184f18a4a0 content_9a4459a8a3b7a514                  383.0     332.373932         1303.0
client_0fa64a184f18a4a0 content_2db2a9dcb3b62a3a                  268.0     282.502229          799.0
client_1a730cb2640a1abf content_d69718c64f0f46a9                  220.0     206.536002          168.0
client_0fa64a184f18a4a0 content_2bed2c9ce7808050                  213.0     200.355189          516.0
client_0fa64a184f18a4a0 content_5ebc94f67db6f51c                  182.0     200.187498           54.0
client_0fa64a184f18a4a0 content_e79f8b4c16bbb7e7                  216.0     199.329036          325.0
client_0fa64a184f18a4a0 content_1478ceb98c064458                  151.0     192.898430          173.0
client_1a730cb2640a1abf content_31170f5df3771d5d                  151.0     168.274280          256.0
client_1a730cb2640a1abf content_ee55cee883b5c9f2                  105.0     142.361438          175.0
client_1a730cb2640a1abf content_569e69e0f1b6a811                  105.0     140.970420          121.0
client_1a730cb2640a1abf content_67cd5746eacb455a                   91.0     124.701129           89.0
client_1a730cb2640a1abf content_f4ab76c36ff4456c                   89.0     122.573359           85.0
client_1a730cb2640a1abf content_3681c60acc49fb6f                   94.0     122.236833           91.0
client_0fa64a184f18a4a0 content_5f3d557da57b00eb                  118.0     116.553157          105.0
client_1a730cb2640a1abf content_2e31fa354c8eaaee                   86.0     110.412339          233.0
client_0fa64a184f18a4a0 content_d013086a434f0189                  138.0     107.651779          419.0
client_1a730cb2640a1abf content_b5921759ec9f374b                   82.0     106.685059          321.0
client_0fa64a184f18a4a0 content_bbc8345bb63436e1                   93.0     105.928315           35.0
client_0fa64a184f18a4a0 content_1c2c41e319bb7a6a                   97.0     105.166923           71.0
client_1a730cb2640a1abf content_1f3aeda6868ee3f2                   86.0     101.979485          121.0

In [ ]:
# ================================================================
# RECOVER FEATURE NAMES SAFELY
# ================================================================

print("\n[1/7] Recovering feature names...")

feature_names = None

# ------------------------------------------------
# 1. Try DataFrame columns
# ------------------------------------------------
if hasattr(X_train_processed, "columns"):
    feature_names = list(X_train_processed.columns)

# ------------------------------------------------
# 2. Try common feature-name variables
# ------------------------------------------------
if feature_names is None:
    for name in [
        "feature_names_out",
        "selected_features",
        "model_features",
        "final_features",
        "features",
    ]:
        if name in globals():
            value = globals()[name]

            if value is not None:
                try:
                    candidate = list(value)

                    if len(candidate) == X_train_processed.shape[1]:
                        feature_names = candidate
                        print("Recovered from:", name)
                        break

                except TypeError:
                    pass

# ------------------------------------------------
# 3. Try sklearn preprocessor
# ------------------------------------------------
if feature_names is None:

    for name in [
        "preprocessor",
        "preprocess",
        "pipeline",
        "feature_pipeline",
        "transformer",
    ]:

        if name not in globals():
            continue

        obj = globals()[name]

        try:
            if hasattr(obj, "get_feature_names_out"):
                candidate = list(
                    obj.get_feature_names_out()
                )

                if len(candidate) == X_train_processed.shape[1]:
                    feature_names = candidate
                    print("Recovered from:", name)
                    break

        except Exception:
            pass

# ------------------------------------------------
# 4. Try Random Forest input feature count
# ------------------------------------------------
if feature_names is None:

    expected = X_train_processed.shape[1]

    if hasattr(rf_model, "n_features_in_"):
        if rf_model.n_features_in_ == expected:

            print(
                "Model confirms feature count:",
                rf_model.n_features_in_
            )

# ------------------------------------------------
# 5. Stop rather than inventing names
# ------------------------------------------------
if feature_names is None:

    raise RuntimeError(
        f"""
Could not safely recover feature names.

Training matrix has {X_train_processed.shape[1]} features.

DO NOT invent feature names.
DO NOT retrain the model.
DO NOT evaluate the test set.

We need to inspect the preprocessing objects that created
X_train_processed.
"""
    )

# ------------------------------------------------
# Final validation
# ------------------------------------------------

if len(feature_names) != X_train_processed.shape[1]:

    raise RuntimeError(
        f"Feature-name count mismatch: "
        f"{len(feature_names)} names for "
        f"{X_train_processed.shape[1]} features."
    )

print("Feature names recovered:", len(feature_names))
print("\nFirst 20 features:")

for i, name in enumerate(feature_names[:20]):
    print(f"{i:>3}: {name}")

print("\nFeature-name alignment: PASS")

[1/7] Recovering feature names...
Recovered from: preprocessor
Feature names recovered: 90

First 20 features:
  0: numeric__keyword_char_count
  1: numeric__keyword_token_count
  2: numeric__url_char_count
  3: numeric__search_volume
  4: numeric__competition
  5: numeric__cpc
  6: numeric__backlinks
  7: numeric__category_count
  8: numeric__char_count
  9: numeric__word_count
 10: numeric__is_published
 11: numeric__is_deleted
 12: numeric__gsc_impressions_hist
 13: numeric__gsc_clicks_hist
 14: numeric__avg_position_hist
 15: numeric__ga4_sessions_hist
 16: numeric__ga4_pageviews_hist
 17: numeric__organic_sessions_hist
 18: numeric__direct_sessions_hist
 19: numeric__referral_sessions_hist

Feature-name alignment: PASS

In [ ]:
# ================================================================
# RECOVER TRAINED RANDOM FOREST OBJECT
# ================================================================

print("=" * 70)
print("=== SEARCHING FOR TRAINED RANDOM FOREST OBJECT ===")
print("=" * 70)

import sklearn

print("\n[0/3] Searching notebook variables...")

candidates = []

for name, obj in globals().items():
    try:
        if hasattr(obj, "feature_importances_") and hasattr(obj, "predict"):
            candidates.append(
                (name, type(obj).__name__, obj)
            )
    except Exception:
        pass

print("Candidate model objects:", len(candidates))

for name, class_name, obj in candidates:
    print(f" - {name}: {class_name}")

print("\n[1/3] Searching for sklearn ensemble models...")

for name, obj in globals().items():
    try:
        class_name = type(obj).__name__

        if "Forest" in class_name or "RandomForest" in class_name:
            print(
                f" - {name}: {class_name}"
            )

    except Exception:
        pass

print("\n[2/3] Checking common model variable names...")

common_names = [
    "model",
    "rf",
    "rf_model",
    "random_forest",
    "random_forest_model",
    "best_model",
    "trained_model",
    "regressor",
]

for name in common_names:

    if name in globals():

        obj = globals()[name]

        print(
            f"FOUND: {name} -> "
            f"{type(obj).__name__}"
        )

print("\n[3/3] Recovery result...")

if len(candidates) == 1:

    name, class_name, obj = candidates[0]

    rf_model = obj

    print(
        f"Recovered model from variable: {name}"
    )

    print(
        f"Model class: {class_name}"
    )

    print(
        "rf_model assigned: PASS"
    )

elif len(candidates) > 1:

    print(
        "MULTIPLE MODEL CANDIDATES FOUND."
    )

    print(
        "Do NOT choose one automatically."
    )

else:

    print(
        "NO TRAINED MODEL OBJECT FOUND "
        "IN CURRENT RUNTIME."
    )

print("\n" + "=" * 70)
print("=== MODEL RECOVERY DIAGNOSTIC COMPLETE ===")
print("=" * 70)

======================================================================
=== SEARCHING FOR TRAINED RANDOM FOREST OBJECT ===
======================================================================

[0/3] Searching notebook variables...
Candidate model objects: 2
 - RandomForestRegressor: ABCMeta
 - rf: RandomForestRegressor

[1/3] Searching for sklearn ensemble models...
 - rf: RandomForestRegressor

[2/3] Checking common model variable names...
FOUND: rf -> RandomForestRegressor

[3/3] Recovery result...
MULTIPLE MODEL CANDIDATES FOUND.
Do NOT choose one automatically.

======================================================================
=== MODEL RECOVERY DIAGNOSTIC COMPLETE ===
======================================================================

In [ ]:
# ================================================================
# RANDOM FOREST FEATURE IMPORTANCE — FINAL AUDIT
# ================================================================

print("=" * 70)
print("=== RANDOM FOREST FEATURE IMPORTANCE AUDIT ===")
print("=" * 70)

# ------------------------------------------------
# 0. Verify trained model
# ------------------------------------------------

print("\n[0/5] Verifying trained Random Forest...")

if "rf" not in globals():
    raise RuntimeError("Trained Random Forest 'rf' not found.")

if not hasattr(rf, "feature_importances_"):
    raise RuntimeError(
        "rf does not contain feature_importances_."
    )

if not hasattr(rf, "predict"):
    raise RuntimeError(
        "rf does not contain predict()."
    )

print("Model object: rf")
print("Model class:", type(rf).__name__)
print("Number of trees:", rf.n_estimators)
print("Input features:", rf.n_features_in_)
print("Model verification: PASS")

# ------------------------------------------------
# 1. Verify feature names
# ------------------------------------------------

print("\n[1/5] Verifying feature names...")

if "feature_names" not in globals():
    raise RuntimeError(
        "feature_names not found."
    )

if len(feature_names) != rf.n_features_in_:
    raise RuntimeError(
        f"Feature mismatch: "
        f"{len(feature_names)} names vs "
        f"{rf.n_features_in_} model inputs."
    )

print("Feature names:", len(feature_names))
print("Feature alignment: PASS")

# ------------------------------------------------
# 2. Feature importance
# ------------------------------------------------

print("\n[2/5] Computing feature importance...")

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": rf.feature_importances_
})

importance_df = importance_df.sort_values(
    "importance",
    ascending=False
).reset_index(drop=True)

importance_df["rank"] = (
    np.arange(1, len(importance_df) + 1)
)

print("\nTop 20 features:")

print(
    importance_df[
        ["rank", "feature", "importance"]
    ].head(20).to_string(index=False)
)

# ------------------------------------------------
# 3. Historical organic traffic
# ------------------------------------------------

print("\n[3/5] Checking organic traffic feature...")

organic = importance_df[
    importance_df["feature"].str.contains(
        "organic_sessions_hist",
        regex=False
    )
]

if len(organic) > 0:

    print(
        organic[
            ["rank", "feature", "importance"]
        ].to_string(index=False)
    )

else:

    print(
        "organic_sessions_hist not found."
    )

# ------------------------------------------------
# 4. Importance concentration
# ------------------------------------------------

print("\n[4/5] Measuring importance concentration...")

importance_sum = importance_df["importance"].sum()

print(
    "Total importance:",
    f"{importance_sum:.6f}"
)

for n in [1, 5, 10, 20]:

    share = (
        importance_df
        .head(n)["importance"]
        .sum()
    )

    print(
        f"Top-{n} cumulative importance:",
        f"{share:.6f}"
    )

# ------------------------------------------------
# 5. Save
# ------------------------------------------------

print("\n[5/5] Saving diagnostic...")

output_path = (
    "/content/FlyRank-ML-Internship-GIT/"
    "work/outputs/rf_feature_importance.csv"
)

importance_df.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

print("\n" + "=" * 70)
print("=== FEATURE IMPORTANCE AUDIT COMPLETE ===")
print("=" * 70)

print("Retraining: NO")
print("Validation tuning: NO")
print("Test evaluation: NO")
print("Feature count: 90")
print("Status: COMPLETE")

======================================================================
=== RANDOM FOREST FEATURE IMPORTANCE AUDIT ===
======================================================================

[0/5] Verifying trained Random Forest...
Model object: rf
Model class: RandomForestRegressor
Number of trees: 300
Input features: 90
Model verification: PASS

[1/5] Verifying feature names...
Feature names: 90
Feature alignment: PASS

[2/5] Computing feature importance...

Top 20 features:
 rank                                  feature  importance
    1           numeric__organic_sessions_hist    0.159655
    2              numeric__ga4_pageviews_hist    0.111878
    3               numeric__ga4_sessions_hist    0.102940
    4                 numeric__gsc_clicks_hist    0.097653
    5            numeric__direct_sessions_hist    0.059735
    6            numeric__gsc_impressions_hist    0.044910
    7      numeric__organic_session_share_hist    0.036396
    8                    numeric__gsc_ctr_hist    0.027918
    9      numeric__pageviews_per_session_hist    0.024758
   10                numeric__keyword_age_days    0.022583
   11        numeric__keyword_created_age_days    0.019857
   12        numeric__content_created_age_days    0.018410
   13                numeric__content_age_days    0.017468
   14 categorical__model_used_gemini-2.5-flash    0.016714
   15         numeric__content_update_lag_days    0.015451
   16           numeric__optimization_lag_days    0.015256
   17       numeric__direct_session_share_hist    0.012011
   18        numeric__content_updated_age_days    0.011601
   19          numeric__referral_sessions_hist    0.011195
   20                      numeric__char_count    0.011085

[3/5] Checking organic traffic feature...
 rank                        feature  importance
    1 numeric__organic_sessions_hist    0.159655

[4/5] Measuring importance concentration...
Total importance: 1.000000
Top-1 cumulative importance: 0.159655
Top-5 cumulative importance: 0.531860
Top-10 cumulative importance: 0.688425
Top-20 cumulative importance: 0.837473

[5/5] Saving diagnostic...
Saved: /content/FlyRank-ML-Internship-GIT/work/outputs/rf_feature_importance.csv

======================================================================
=== FEATURE IMPORTANCE AUDIT COMPLETE ===
======================================================================
Retraining: NO
Validation tuning: NO
Test evaluation: NO
Feature count: 90
Status: COMPLETE

In [ ]:
# ================================================================
# RANDOM FOREST — VALIDATION ERROR ANALYSIS
# ================================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("=== RANDOM FOREST VALIDATION ERROR ANALYSIS ===")
print("=" * 70)

# ------------------------------------------------
# 0. Safety
# ------------------------------------------------

print("\n[0/7] Checking validation objects...")

if "rf" not in globals():
    raise RuntimeError("Trained RF model not found.")

if "validation_exact" not in globals():
    raise RuntimeError("validation_exact not found.")

required = [
    "client_hash_id",
    "content_hash_id",
    "rf_prediction",
    "future_organic_sessions",
]

missing = [
    c for c in required
    if c not in validation_exact.columns
]

if missing:
    raise RuntimeError(
        f"validation_exact missing columns: {missing}"
    )

validation_error = validation_exact.copy()

validation_error["actual"] = (
    validation_error["future_organic_sessions"]
)

validation_error["prediction"] = (
    validation_error["rf_prediction"]
)

validation_error["error"] = (
    validation_error["prediction"]
    - validation_error["actual"]
)

validation_error["absolute_error"] = (
    validation_error["error"].abs()
)

validation_error["squared_error"] = (
    validation_error["error"] ** 2
)

print("Rows:", len(validation_error))
print("Validation objects: PASS")

# ------------------------------------------------
# 1. Overall error metrics
# ------------------------------------------------

print("\n[1/7] Overall validation error...")

mae = validation_error["absolute_error"].mean()

rmse = np.sqrt(
    validation_error["squared_error"].mean()
)

mean_error = validation_error["error"].mean()

median_abs_error = (
    validation_error["absolute_error"].median()
)

print(f"MAE:              {mae:.4f}")
print(f"RMSE:             {rmse:.4f}")
print(f"Median Abs Error: {median_abs_error:.4f}")
print(f"Mean Signed Error:{mean_error:.4f}")

# ------------------------------------------------
# 2. Zero vs positive targets
# ------------------------------------------------

print("\n[2/7] Zero-target vs positive-target performance...")

zero_target = validation_error[
    validation_error["actual"] == 0
]

positive_target = validation_error[
    validation_error["actual"] > 0
]

print("\nZero-target rows:", len(zero_target))

if len(zero_target) > 0:

    print(
        "Mean prediction:",
        f"{zero_target['prediction'].mean():.4f}"
    )

    print(
        "Median prediction:",
        f"{zero_target['prediction'].median():.4f}"
    )

    print(
        "MAE:",
        f"{zero_target['absolute_error'].mean():.4f}"
    )

print("\nPositive-target rows:", len(positive_target))

if len(positive_target) > 0:

    print(
        "Mean actual:",
        f"{positive_target['actual'].mean():.4f}"
    )

    print(
        "Mean prediction:",
        f"{positive_target['prediction'].mean():.4f}"
    )

    print(
        "MAE:",
        f"{positive_target['absolute_error'].mean():.4f}"
    )

# ------------------------------------------------
# 3. Error by target magnitude
# ------------------------------------------------

print("\n[3/7] Error by actual-target magnitude...")

def error_bucket(x):

    if x == 0:
        return "0"

    if x <= 1:
        return "1"

    if x <= 5:
        return "2-5"

    if x <= 10:
        return "6-10"

    if x <= 25:
        return "11-25"

    if x <= 50:
        return "26-50"

    if x <= 100:
        return "51-100"

    if x <= 250:
        return "101-250"

    if x <= 500:
        return "251-500"

    return "501+"

validation_error["target_bucket"] = (
    validation_error["actual"]
    .apply(error_bucket)
)

bucket_order = [
    "0",
    "1",
    "2-5",
    "6-10",
    "11-25",
    "26-50",
    "51-100",
    "101-250",
    "251-500",
    "501+",
]

bucket_summary = (
    validation_error
    .groupby(
        "target_bucket",
        observed=True
    )
    .agg(
        rows=("actual", "size"),
        mean_actual=("actual", "mean"),
        mean_prediction=("prediction", "mean"),
        mae=("absolute_error", "mean"),
        median_abs_error=("absolute_error", "median")
    )
    .reindex(bucket_order)
)

print(
    bucket_summary.to_string()
)

# ------------------------------------------------
# 4. Underprediction vs overprediction
# ------------------------------------------------

print("\n[4/7] Checking prediction direction...")

under = validation_error[
    validation_error["prediction"]
    < validation_error["actual"]
]

over = validation_error[
    validation_error["prediction"]
    > validation_error["actual"]
]

exact = validation_error[
    validation_error["prediction"]
    == validation_error["actual"]
]

print(
    "Underpredictions:",
    len(under),
    f"({len(under)/len(validation_error):.2%})"
)

print(
    "Overpredictions:",
    len(over),
    f"({len(over)/len(validation_error):.2%})"
)

print(
    "Exact:",
    len(exact),
    f"({len(exact)/len(validation_error):.2%})"
)

if len(under) > 0:
    print(
        "Mean underprediction magnitude:",
        f"{under['absolute_error'].mean():.4f}"
    )

if len(over) > 0:
    print(
        "Mean overprediction magnitude:",
        f"{over['absolute_error'].mean():.4f}"
    )

# ------------------------------------------------
# 5. Largest absolute errors
# ------------------------------------------------

print("\n[5/7] Largest validation errors...")

worst = (
    validation_error
    .sort_values(
        "absolute_error",
        ascending=False
    )
    .head(20)
)

print(
    worst[
        [
            "client_hash_id",
            "content_hash_id",
            "organic_sessions_hist",
            "prediction",
            "actual",
            "error",
            "absolute_error",
        ]
    ].to_string(index=False)
)

# ------------------------------------------------
# 6. High-value target capture
# ------------------------------------------------

print("\n[6/7] Checking high-value target capture...")

for threshold in [25, 50, 100, 250, 500]:

    high = validation_error[
        validation_error["actual"] >= threshold
    ]

    if len(high) == 0:
        continue

    print(
        f"\nActual >= {threshold}:"
    )

    print(
        "Rows:",
        len(high)
    )

    print(
        "Mean actual:",
        f"{high['actual'].mean():.3f}"
    )

    print(
        "Mean prediction:",
        f"{high['prediction'].mean():.3f}"
    )

    print(
        "MAE:",
        f"{high['absolute_error'].mean():.3f}"
    )

# ------------------------------------------------
# 7. Save validation error analysis
# ------------------------------------------------

print("\n[7/7] Saving validation error analysis...")

output_dir = (
    "/content/FlyRank-ML-Internship-GIT/"
    "work/outputs/"
)

error_path = (
    output_dir +
    "rf_validation_error_analysis.csv"
)

bucket_path = (
    output_dir +
    "rf_validation_error_buckets.csv"
)

validation_error.to_csv(
    error_path,
    index=False
)

bucket_summary.to_csv(
    bucket_path
)

print("Saved:", error_path)
print("Saved:", bucket_path)

print("\n" + "=" * 70)
print("=== VALIDATION ERROR ANALYSIS COMPLETE ===")
print("=" * 70)

print("Retraining: NO")
print("Test data used: NO")
print("Test evaluation changed: NO")
print("Status: COMPLETE")

======================================================================
=== RANDOM FOREST VALIDATION ERROR ANALYSIS ===
======================================================================

[0/7] Checking validation objects...
Rows: 59860
Validation objects: PASS

[1/7] Overall validation error...
MAE:              3.8642
RMSE:             20.8511
Median Abs Error: 0.1806
Mean Signed Error:-2.2384

[2/7] Zero-target vs positive-target performance...

Zero-target rows: 42382
Mean prediction: 0.5177
Median prediction: 0.0430
MAE: 0.5177

Positive-target rows: 17478
Mean actual: 17.1284
Mean prediction: 8.2068
MAE: 11.9790

[3/7] Error by actual-target magnitude...
                rows  mean_actual  mean_prediction         mae  median_abs_error
target_bucket
0              42382     0.000000         0.517724    0.517724          0.042984
1               3447     1.000000         1.673534    1.554217          0.862014
2-5             5974     3.077335         3.285623    2.806623          1.906943
6-10            2687     7.647190         6.029227    5.214901          4.647768
11-25           2735    16.407313        10.138414   10.108154          9.468438
26-50           1399    35.585418        17.537040   21.800128         21.762065
51-100           708    70.233051        25.148184   47.308497         47.070942
101-250          419   155.033413        45.903877  110.940729        107.365999
251-500           87   344.931034       101.646322  243.284712        239.842568
501+              22   801.818182       167.988400  633.829781        512.779064

[4/7] Checking prediction direction...
Underpredictions: 12761 (21.32%)
Overpredictions: 47093 (78.67%)
Exact: 6 (0.01%)
Mean underprediction magnitude: 14.3132
Mean overprediction magnitude: 1.0333

[5/7] Largest validation errors...
         client_hash_id          content_hash_id  organic_sessions_hist  prediction  actual        error  absolute_error
client_73cda7b4e4f265ea content_512dbad65bd5ade9                  799.0  329.126700  2071.0 -1741.873300     1741.873300
client_73cda7b4e4f265ea content_6c4da03688ca8351                  386.0  114.287846  1421.0 -1306.712154     1306.712154
client_73cda7b4e4f265ea content_65f0084145088393                  138.0   57.909214   922.0  -864.090786      864.090786
client_73cda7b4e4f265ea content_75a700ed65ccf13f                  202.0   97.463092   885.0  -787.536908      787.536908
client_73cda7b4e4f265ea content_17494d099b0a537e                  272.0  184.430330   969.0  -784.569670      784.569670
client_73cda7b4e4f265ea content_e9856d7d976aa034                  166.0  208.528352   945.0  -736.471648      736.471648
client_73cda7b4e4f265ea content_57c3b90b328b406e                  276.0  126.965221   863.0  -736.034779      736.034779
client_73cda7b4e4f265ea content_9ee101f6c3e35cf1                  147.0  145.590363   783.0  -637.409637      637.409637
client_73cda7b4e4f265ea content_43c7cd15278a7938                    0.0    4.826188   610.0  -605.173812      605.173812
client_73cda7b4e4f265ea content_fe3fd3422852d721                  170.0   92.997662   638.0  -545.002338      545.002338
client_73cda7b4e4f265ea content_da4726a6aced1c83                  162.0  160.185930   679.0  -518.814070      518.814070
client_73cda7b4e4f265ea content_5267d90f451c6edc                  209.0  272.255942   779.0  -506.744058      506.744058
client_73cda7b4e4f265ea content_76f9b5358889447c                  151.0   55.488350   553.0  -497.511650      497.511650
client_73cda7b4e4f265ea content_ba56372097620614                  168.0  190.297533   655.0  -464.702467      464.702467
client_73cda7b4e4f265ea content_dbbde91a0db0f0e3                  167.0  159.892261   622.0  -462.107739      462.107739
client_73cda7b4e4f265ea content_987d251ee617d9c6                  329.0  346.536274   793.0  -446.463726      446.463726
client_73cda7b4e4f265ea content_18effdf03138153d                   94.0  148.577855   585.0  -436.422145      436.422145
client_73cda7b4e4f265ea content_85703b835ab9e744                  345.0  366.253630   800.0  -433.746370      433.746370
client_73cda7b4e4f265ea content_b556f0bd87d6fcca                  208.0   92.517624   491.0  -398.482376      398.482376
client_73cda7b4e4f265ea content_b98fd317f3fa7210                   22.0   42.415842   431.0  -388.584158      388.584158

[6/7] Checking high-value target capture...

Actual >= 25:
Rows: 2734
Mean actual: 78.490
Mean prediction: 27.557
MAE: 53.792

Actual >= 50:
Rows: 1274
Mean actual: 128.911
Mean prediction: 39.547
MAE: 91.295

Actual >= 100:
Rows: 536
Mean actual: 211.582
Mean prediction: 59.727
MAE: 153.271

Actual >= 250:
Rows: 109
Mean actual: 437.147
Mean prediction: 115.036
MAE: 322.110

Actual >= 500:
Rows: 22
Mean actual: 801.818
Mean prediction: 167.988
MAE: 633.830

[7/7] Saving validation error analysis...
Saved: /content/FlyRank-ML-Internship-GIT/work/outputs/rf_validation_error_analysis.csv
Saved: /content/FlyRank-ML-Internship-GIT/work/outputs/rf_validation_error_buckets.csv

======================================================================
=== VALIDATION ERROR ANALYSIS COMPLETE ===
======================================================================
Retraining: NO
Test data used: NO
Test evaluation changed: NO
Status: COMPLETE

In [ ]:
# ================================================================
# RANDOM FOREST — CORRECTED VALIDATION NDCG AUDIT
# ================================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("=== RANDOM FOREST — CORRECTED VALIDATION NDCG AUDIT ===")
print("=" * 70)

# ------------------------------------------------
# 0. Validate input
# ------------------------------------------------
print("\n[0/5] Checking validation data...")

if "validation_exact" not in globals():
    raise RuntimeError("validation_exact not found.")

ranking_df = validation_exact.copy()

required = [
    "client_hash_id",
    "content_hash_id",
    "organic_sessions_hist",
    "rf_prediction",
    "future_organic_sessions",
]

missing = [
    c for c in required
    if c not in ranking_df.columns
]

if missing:
    raise RuntimeError(
        f"Missing required columns: {missing}"
    )

print("Rows:", len(ranking_df))
print("Required columns: PASS")

# ------------------------------------------------
# 1. Define stable DCG / NDCG
# ------------------------------------------------
print("\n[1/5] Defining stable NDCG calculation...")

def dcg_log_gain(values, k):
    """
    DCG using raw target gain with logarithmic discount.

    Unlike 2^relevance - 1, this cannot overflow for
    large traffic targets.
    """

    values = np.asarray(values, dtype=float)

    values = values[:k]

    if len(values) == 0:
        return 0.0

    discounts = np.log2(
        np.arange(2, len(values) + 2)
    )

    return np.sum(
        values / discounts
    )


def ndcg_log_gain(predictions, actuals, k):

    predictions = np.asarray(
        predictions,
        dtype=float
    )

    actuals = np.asarray(
        actuals,
        dtype=float
    )

    # Ranking produced by model
    order = np.argsort(
        -predictions,
        kind="mergesort"
    )

    ranked_actuals = actuals[order]

    dcg = dcg_log_gain(
        ranked_actuals,
        k
    )

    # Ideal ranking
    ideal_actuals = np.sort(
        actuals
    )[::-1]

    ideal_dcg = dcg_log_gain(
        ideal_actuals,
        k
    )

    if ideal_dcg == 0:
        return 0.0

    return dcg / ideal_dcg


print("Stable NDCG implementation: PASS")

# ------------------------------------------------
# 2. Calculate RF vs baseline NDCG
# ------------------------------------------------
print("\n[2/5] Computing NDCG@K...")

actual = ranking_df[
    "future_organic_sessions"
].to_numpy()

rf_predictions = ranking_df[
    "rf_prediction"
].to_numpy()

baseline_predictions = ranking_df[
    "organic_sessions_hist"
].fillna(0).to_numpy()

ks = [
    20,
    50,
    100,
    500,
    1000
]

ndcg_results = []

for k in ks:

    rf_ndcg = ndcg_log_gain(
        rf_predictions,
        actual,
        k
    )

    baseline_ndcg = ndcg_log_gain(
        baseline_predictions,
        actual,
        k
    )

    ndcg_results.append({
        "k": k,
        "rf_ndcg": rf_ndcg,
        "baseline_ndcg": baseline_ndcg,
        "rf_minus_baseline":
            rf_ndcg - baseline_ndcg
    })

    print(f"\nK = {k}")

    print(
        f"RF NDCG@{k}: "
        f"{rf_ndcg:.4f}"
    )

    print(
        f"Baseline NDCG@{k}: "
        f"{baseline_ndcg:.4f}"
    )

    print(
        f"RF improvement: "
        f"{(rf_ndcg - baseline_ndcg):+.4f}"
    )

# ------------------------------------------------
# 3. Summary
# ------------------------------------------------
print("\n[3/5] Ranking-quality summary...")

ndcg_results_df = pd.DataFrame(
    ndcg_results
)

print(
    ndcg_results_df.to_string(
        index=False
    )
)

rf_better_count = (
    ndcg_results_df[
        "rf_minus_baseline"
    ] > 0
).sum()

print(
    "\nRF better than baseline at:",
    f"{rf_better_count}/{len(ks)} K values"
)

# ------------------------------------------------
# 4. Sanity checks
# ------------------------------------------------
print("\n[4/5] Running sanity checks...")

if ndcg_results_df[
    ["rf_ndcg", "baseline_ndcg"]
].isna().any().any():

    raise RuntimeError(
        "NDCG still contains NaN."
    )

if (
    ndcg_results_df[
        ["rf_ndcg", "baseline_ndcg"]
    ] < 0
).any().any():

    raise RuntimeError(
        "NDCG contains negative values."
    )

if (
    ndcg_results_df[
        ["rf_ndcg", "baseline_ndcg"]
    ] > 1.000001
).any().any():

    raise RuntimeError(
        "NDCG exceeds expected maximum of 1."
    )

print("No NaN: PASS")
print("No negative NDCG: PASS")
print("NDCG <= 1: PASS")

# ------------------------------------------------
# 5. Save
# ------------------------------------------------
print("\n[5/5] Saving corrected NDCG audit...")

output_path = (
    "/content/FlyRank-ML-Internship-GIT/"
    "work/outputs/rf_validation_ndcg_audit.csv"
)

ndcg_results_df.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

print("\n" + "=" * 70)
print("=== CORRECTED NDCG AUDIT COMPLETE ===")
print("=" * 70)

print("Retraining: NO")
print("Validation tuning: NO")
print("Test data used: NO")
print("Test evaluation changed: NO")
print("Status: COMPLETE")

======================================================================
=== RANDOM FOREST — CORRECTED VALIDATION NDCG AUDIT ===
======================================================================

[0/5] Checking validation data...
Rows: 59860
Required columns: PASS

[1/5] Defining stable NDCG calculation...
Stable NDCG implementation: PASS

[2/5] Computing NDCG@K...

K = 20
RF NDCG@20: 0.6457
Baseline NDCG@20: 0.5522
RF improvement: +0.0935

K = 50
RF NDCG@50: 0.6951
Baseline NDCG@50: 0.5306
RF improvement: +0.1645

K = 100
RF NDCG@100: 0.7188
Baseline NDCG@100: 0.5815
RF improvement: +0.1372

K = 500
RF NDCG@500: 0.7267
Baseline NDCG@500: 0.6615
RF improvement: +0.0652

K = 1000
RF NDCG@1000: 0.7524
Baseline NDCG@1000: 0.7040
RF improvement: +0.0484

[3/5] Ranking-quality summary...
   k  rf_ndcg  baseline_ndcg  rf_minus_baseline
  20 0.645698       0.552180           0.093518
  50 0.695077       0.530556           0.164520
 100 0.718758       0.581532           0.137226
 500 0.726716       0.661541           0.065175
1000 0.752402       0.703975           0.048428

RF better than baseline at: 5/5 K values

[4/5] Running sanity checks...
No NaN: PASS
No negative NDCG: PASS
NDCG <= 1: PASS

[5/5] Saving corrected NDCG audit...
Saved: /content/FlyRank-ML-Internship-GIT/work/outputs/rf_validation_ndcg_audit.csv

======================================================================
=== CORRECTED NDCG AUDIT COMPLETE ===
======================================================================
Retraining: NO
Validation tuning: NO
Test data used: NO
Test evaluation changed: NO
Status: COMPLETE

In [ ]:
# ================================================================
# RANDOM FOREST — VALIDATION CLIENT ROBUSTNESS AUDIT
# ================================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("=== RANDOM FOREST — VALIDATION CLIENT ROBUSTNESS AUDIT ===")
print("=" * 70)

# ------------------------------------------------
# 0. Validate validation objects
# ------------------------------------------------
print("\n[0/6] Checking validation data...")

if "validation_exact" not in globals():
    raise RuntimeError("validation_exact not found.")

robust_df = validation_exact.copy()

required = [
    "client_hash_id",
    "content_hash_id",
    "rf_prediction",
    "future_organic_sessions",
]

missing = [
    c for c in required
    if c not in robust_df.columns
]

if missing:
    raise RuntimeError(
        f"Missing required columns: {missing}"
    )

print("Rows:", len(robust_df))
print("Required columns: PASS")

# ------------------------------------------------
# 1. Calculate row-level errors
# ------------------------------------------------
print("\n[1/6] Computing client-level prediction errors...")

robust_df["error"] = (
    robust_df["future_organic_sessions"]
    - robust_df["rf_prediction"]
)

robust_df["absolute_error"] = (
    robust_df["error"].abs()
)

robust_df["squared_error"] = (
    robust_df["error"] ** 2
)

print("Residual calculations: PASS")

# ------------------------------------------------
# 2. Client-level regression metrics
# ------------------------------------------------
print("\n[2/6] Computing client-level metrics...")

client_metrics = (
    robust_df
    .groupby("client_hash_id")
    .agg(
        rows=(
            "content_hash_id",
            "count"
        ),
        actual_mean=(
            "future_organic_sessions",
            "mean"
        ),
        prediction_mean=(
            "rf_prediction",
            "mean"
        ),
        mae=(
            "absolute_error",
            "mean"
        ),
        rmse=(
            "squared_error",
            lambda x: np.sqrt(x.mean())
        ),
        positive_actuals=(
            "future_organic_sessions",
            lambda x: (x > 0).sum()
        ),
    )
    .reset_index()
)

client_metrics["positive_rate"] = (
    client_metrics["positive_actuals"]
    / client_metrics["rows"]
)

print(
    "Validation clients:",
    len(client_metrics)
)

print(
    "Client metric table: PASS"
)

# ------------------------------------------------
# 3. Distribution of client MAE
# ------------------------------------------------
print("\n[3/6] Client MAE distribution...")

print(
    client_metrics["mae"]
    .describe()
    .to_string()
)

print("\nClient RMSE distribution:")

print(
    client_metrics["rmse"]
    .describe()
    .to_string()
)

print("\nClient positive-rate distribution:")

print(
    client_metrics["positive_rate"]
    .describe()
    .to_string()
)

# ------------------------------------------------
# 4. Worst and best clients
# ------------------------------------------------
print("\n[4/6] Identifying client-level extremes...")

print("\nWorst 10 clients by MAE:")

print(
    client_metrics
    .sort_values(
        "mae",
        ascending=False
    )
    .head(10)
    .to_string(index=False)
)

print("\nBest 10 clients by MAE:")

print(
    client_metrics
    .sort_values(
        "mae",
        ascending=True
    )
    .head(10)
    .to_string(index=False)
)

# ------------------------------------------------
# 5. Weighted vs unweighted performance
# ------------------------------------------------
print("\n[5/6] Comparing weighted and unweighted performance...")

overall_mae = robust_df[
    "absolute_error"
].mean()

overall_rmse = np.sqrt(
    robust_df[
        "squared_error"
    ].mean()
)

macro_mae = client_metrics[
    "mae"
].mean()

macro_rmse = client_metrics[
    "rmse"
].mean()

print(
    f"Micro/row-weighted MAE:  {overall_mae:.4f}"
)

print(
    f"Macro/client-weighted MAE: {macro_mae:.4f}"
)

print(
    f"Micro/row-weighted RMSE: {overall_rmse:.4f}"
)

print(
    f"Macro/client-weighted RMSE: {macro_rmse:.4f}"
)

# ------------------------------------------------
# 6. Save audit
# ------------------------------------------------
print("\n[6/6] Saving client robustness audit...")

output_path = (
    "/content/FlyRank-ML-Internship-GIT/"
    "work/outputs/rf_validation_client_robustness.csv"
)

client_metrics.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

print("\n" + "=" * 70)
print("=== CLIENT ROBUSTNESS AUDIT COMPLETE ===")
print("=" * 70)

print("Retraining: NO")
print("Test data used: NO")
print("Test evaluation changed: NO")
print("Validation tuning: NO")
print("Status: COMPLETE")

======================================================================
=== RANDOM FOREST — VALIDATION CLIENT ROBUSTNESS AUDIT ===
======================================================================

[0/6] Checking validation data...
Rows: 59860
Required columns: PASS

[1/6] Computing client-level prediction errors...
Residual calculations: PASS

[2/6] Computing client-level metrics...
Validation clients: 8
Client metric table: PASS

[3/6] Client MAE distribution...
count    8.000000
mean     1.646679
std      2.293054
min      0.000435
25%      0.067126
50%      0.652774
75%      2.155152
max      6.252828

Client RMSE distribution:
count     8.000000
mean      6.353811
std      10.013994
min       0.002880
25%       0.124702
50%       1.457369
75%       8.905215
max      29.074010

Client positive-rate distribution:
count    8.000000
mean     0.119368
std      0.172523
min      0.000000
25%      0.000000
50%      0.033938
75%      0.166757
max      0.457593

[4/6] Identifying client-level extremes...

Worst 10 clients by MAE:
         client_hash_id  rows  actual_mean  prediction_mean      mae      rmse  positive_actuals  positive_rate
client_73cda7b4e4f265ea 29323     8.740477         3.266632 6.252828 29.074010             13418       0.457593
client_fef1a8f436438636 11210     3.575112         5.914613 3.944905 10.130724              3483       0.310705
client_b77d0d5f08f05e64  1044     1.071839         1.634416 1.558567  8.496712               124       0.118774
client_810019792c9b8efc   203     0.236453         1.062111 1.177342  1.972671                 7       0.034483
client_65de48885f4ef01b 13356     0.136942         0.090518 0.128206  0.942067               446       0.033393
client_0797ff3a1fc9a6a5   260     0.000000         0.078676 0.078676  0.143692                 0       0.000000
client_4a18d1793d92fb84  4264     0.000000         0.032473 0.032473  0.067734                 0       0.000000
client_770e8e5faa9cddfe   200     0.000000         0.000435 0.000435  0.002880                 0       0.000000

Best 10 clients by MAE:
         client_hash_id  rows  actual_mean  prediction_mean      mae      rmse  positive_actuals  positive_rate
client_770e8e5faa9cddfe   200     0.000000         0.000435 0.000435  0.002880                 0       0.000000
client_4a18d1793d92fb84  4264     0.000000         0.032473 0.032473  0.067734                 0       0.000000
client_0797ff3a1fc9a6a5   260     0.000000         0.078676 0.078676  0.143692                 0       0.000000
client_65de48885f4ef01b 13356     0.136942         0.090518 0.128206  0.942067               446       0.033393
client_810019792c9b8efc   203     0.236453         1.062111 1.177342  1.972671                 7       0.034483
client_b77d0d5f08f05e64  1044     1.071839         1.634416 1.558567  8.496712               124       0.118774
client_fef1a8f436438636 11210     3.575112         5.914613 3.944905 10.130724              3483       0.310705
client_73cda7b4e4f265ea 29323     8.740477         3.266632 6.252828 29.074010             13418       0.457593

[5/6] Comparing weighted and unweighted performance...
Micro/row-weighted MAE:  3.8642
Macro/client-weighted MAE: 1.6467
Micro/row-weighted RMSE: 20.8511
Macro/client-weighted RMSE: 6.3538

[6/6] Saving client robustness audit...
Saved: /content/FlyRank-ML-Internship-GIT/work/outputs/rf_validation_client_robustness.csv

======================================================================
=== CLIENT ROBUSTNESS AUDIT COMPLETE ===
======================================================================
Retraining: NO
Test data used: NO
Test evaluation changed: NO
Validation tuning: NO
Status: COMPLETE

In [ ]:
import numpy as np
import pandas as pd

print("=" * 70)
print("=== RANDOM FOREST — FINAL TEST NDCG AUDIT ===")
print("=" * 70)

# ------------------------------------------------
# 0. Verify exact objects
# ------------------------------------------------
print("\n[0/6] Verifying exact test objects...")

if "rf" not in globals():
    raise RuntimeError("RF model not found.")

if "X_test_processed" not in globals():
    raise RuntimeError("X_test_processed not found.")

if "y_test" not in globals():
    raise RuntimeError("y_test not found.")

if "test_df" not in globals():
    raise RuntimeError("test_df not found.")

print("RF:", type(rf).__name__)
print("RF expected features:", rf.n_features_in_)
print("X_test_processed:", X_test_processed.shape)
print("y_test:", y_test.shape)
print("test_df:", test_df.shape)

if X_test_processed.shape[1] != rf.n_features_in_:
    raise RuntimeError(
        "Processed test feature count does not match RF."
    )

if len(X_test_processed) != len(y_test):
    raise RuntimeError(
        "Processed test rows do not match y_test."
    )

print("Object checks: PASS")

# ------------------------------------------------
# 1. Generate predictions
# ------------------------------------------------
print("\n[1/6] Generating final test predictions...")

rf_test_predictions = np.asarray(
    rf.predict(X_test_processed)
)

print(
    "Predictions generated:",
    len(rf_test_predictions)
)

# ------------------------------------------------
# 2. Build exact test comparison table
# ------------------------------------------------
print("\n[2/6] Building exact test comparison table...")

test_ndcg = test_df[
    [
        "client_hash_id",
        "content_hash_id",
        "organic_sessions_hist",
    ]
].copy().reset_index(drop=True)

test_ndcg["rf_prediction"] = rf_test_predictions
test_ndcg["future_organic_sessions"] = np.asarray(y_test)

test_ndcg["baseline_prediction"] = (
    test_ndcg["organic_sessions_hist"]
    .fillna(0)
)

if len(test_ndcg) != 18743:
    raise RuntimeError(
        "Unexpected test row count."
    )

print(
    "Test comparison rows:",
    len(test_ndcg)
)

print("Target attachment: PASS")
print("Baseline attachment: PASS")

# ------------------------------------------------
# 3. Stable NDCG implementation
# ------------------------------------------------
print("\n[3/6] Computing stable NDCG...")

def stable_ndcg_at_k(actual, predicted, k):

    actual = np.asarray(
        actual,
        dtype=float
    )

    predicted = np.asarray(
        predicted,
        dtype=float
    )

    k = min(k, len(actual))

    # Predicted ranking
    pred_order = np.argsort(
        -predicted,
        kind="mergesort"
    )[:k]

    ranked_actual = actual[pred_order]

    # Stable logarithmic gain
    gains = np.log2(
        1.0 + ranked_actual
    )

    discounts = np.log2(
        np.arange(2, k + 2)
    )

    dcg = np.sum(
        gains / discounts
    )

    # Ideal ranking
    ideal_actual = np.sort(
        actual
    )[::-1][:k]

    ideal_gains = np.log2(
        1.0 + ideal_actual
    )

    ideal_dcg = np.sum(
        ideal_gains / discounts
    )

    if ideal_dcg == 0:
        return 0.0

    return dcg / ideal_dcg


# ------------------------------------------------
# 4. Compute final test NDCG@K
# ------------------------------------------------
print("\n[4/6] Computing TEST NDCG@K...")

ks = [
    20,
    50,
    100,
    500,
    1000,
]

results = []

actual = test_ndcg[
    "future_organic_sessions"
]

rf_pred = test_ndcg[
    "rf_prediction"
]

baseline_pred = test_ndcg[
    "baseline_prediction"
]

for k in ks:

    rf_ndcg = stable_ndcg_at_k(
        actual,
        rf_pred,
        k
    )

    baseline_ndcg = stable_ndcg_at_k(
        actual,
        baseline_pred,
        k
    )

    improvement = (
        rf_ndcg
        - baseline_ndcg
    )

    results.append({
        "k": k,
        "rf_ndcg": rf_ndcg,
        "baseline_ndcg": baseline_ndcg,
        "rf_minus_baseline": improvement,
    })

    print(f"\nK = {k}")
    print(
        f"RF NDCG@{k}: "
        f"{rf_ndcg:.4f}"
    )
    print(
        f"Baseline NDCG@{k}: "
        f"{baseline_ndcg:.4f}"
    )
    print(
        f"RF improvement: "
        f"{improvement:+.4f}"
    )

# ------------------------------------------------
# 5. Sanity checks
# ------------------------------------------------
print("\n[5/6] Running sanity checks...")

ndcg_results = pd.DataFrame(results)

if ndcg_results.isna().any().any():
    raise RuntimeError(
        "NaN detected in final NDCG results."
    )

if (
    (ndcg_results["rf_ndcg"] < 0).any()
    or
    (ndcg_results["baseline_ndcg"] < 0).any()
):
    raise RuntimeError(
        "Negative NDCG detected."
    )

if (
    (ndcg_results["rf_ndcg"] > 1).any()
    or
    (ndcg_results["baseline_ndcg"] > 1).any()
):
    raise RuntimeError(
        "NDCG > 1 detected."
    )

print("No NaN: PASS")
print("No negative NDCG: PASS")
print("NDCG <= 1: PASS")

print("\nFinal test NDCG summary:")
print(
    ndcg_results.to_string(
        index=False
    )
)

# ------------------------------------------------
# 6. Save
# ------------------------------------------------
print("\n[6/6] Saving final test NDCG audit...")

output_path = (
    "/content/FlyRank-ML-Internship-GIT/"
    "work/outputs/rf_test_ndcg_audit.csv"
)

ndcg_results.to_csv(
    output_path,
    index=False
)

print("Saved:", output_path)

print("\n" + "=" * 70)
print("=== FINAL TEST NDCG AUDIT COMPLETE ===")
print("=" * 70)

print("Processed matrix: X_test_processed")
print("Feature count:", X_test_processed.shape[1])
print("Test rows:", len(test_ndcg))
print("Retraining: NO")
print("Test-based tuning: NO")
print("Model selection after test: NO")
print("Status: COMPLETE")

======================================================================
=== RANDOM FOREST — FINAL TEST NDCG AUDIT ===
======================================================================

[0/6] Verifying exact test objects...
RF: RandomForestRegressor
RF expected features: 90
X_test_processed: (18743, 90)
y_test: (18743,)
test_df: (18743, 55)
Object checks: PASS

[1/6] Generating final test predictions...
Predictions generated: 18743

[2/6] Building exact test comparison table...
Test comparison rows: 18743
Target attachment: PASS
Baseline attachment: PASS

[3/6] Computing stable NDCG...

[4/6] Computing TEST NDCG@K...

K = 20
RF NDCG@20: 0.9248
Baseline NDCG@20: 0.8113
RF improvement: +0.1135

K = 50
RF NDCG@50: 0.9366
Baseline NDCG@50: 0.8099
RF improvement: +0.1267

K = 100
RF NDCG@100: 0.9369
Baseline NDCG@100: 0.7756
RF improvement: +0.1614

K = 500
RF NDCG@500: 0.8633
Baseline NDCG@500: 0.7244
RF improvement: +0.1389

K = 1000
RF NDCG@1000: 0.8197
Baseline NDCG@1000: 0.6971
RF improvement: +0.1226

[5/6] Running sanity checks...
No NaN: PASS
No negative NDCG: PASS
NDCG <= 1: PASS

Final test NDCG summary:
   k  rf_ndcg  baseline_ndcg  rf_minus_baseline
  20 0.924791       0.811258           0.113533
  50 0.936565       0.809858           0.126707
 100 0.936938       0.775566           0.161372
 500 0.863333       0.724411           0.138923
1000 0.819714       0.697139           0.122575

[6/6] Saving final test NDCG audit...
Saved: /content/FlyRank-ML-Internship-GIT/work/outputs/rf_test_ndcg_audit.csv

======================================================================
=== FINAL TEST NDCG AUDIT COMPLETE ===
======================================================================
Processed matrix: X_test_processed
Feature count: 90
Test rows: 18743
Retraining: NO
Test-based tuning: NO
Model selection after test: NO
Status: COMPLETE

In [ ]:
# ================================================================
# FLYRANK — FINAL REPOSITORY AUDIT
# ================================================================

from pathlib import Path
import os
import pandas as pd

REPO_ROOT = Path("/content/FlyRank-ML-Internship-GIT")

if not REPO_ROOT.exists():
    raise RuntimeError(f"Repository not found: {REPO_ROOT}")

print("=" * 70)
print("=== FLYRANK — FINAL REPOSITORY AUDIT ===")
print("=" * 70)

# ------------------------------------------------
# 1. Repository structure
# ------------------------------------------------

print("\n[1/6] Repository structure...")

for root, dirs, files in os.walk(REPO_ROOT):
    root_path = Path(root)

    # Skip .git internals
    dirs[:] = [d for d in dirs if d != ".git"]

    level = len(root_path.relative_to(REPO_ROOT).parts)

    if level > 3:
        continue

    indent = "  " * level

    if level == 0:
        print(f"\n{root_path.name}/")

    for file in sorted(files):
        file_path = root_path / file
        size_mb = file_path.stat().st_size / (1024 * 1024)

        print(f"{indent}  {file} ({size_mb:.2f} MB)")


# ------------------------------------------------
# 2. File inventory
# ------------------------------------------------

print("\n" + "=" * 70)
print("[2/6] Building complete file inventory...")
print("=" * 70)

all_files = []

for path in REPO_ROOT.rglob("*"):
    if path.is_file() and ".git" not in path.parts:
        size_mb = path.stat().st_size / (1024 * 1024)

        all_files.append({
            "relative_path": str(path.relative_to(REPO_ROOT)),
            "extension": path.suffix.lower(),
            "size_mb": round(size_mb, 4),
            "size_bytes": path.stat().st_size
        })

inventory_df = pd.DataFrame(all_files)

print(f"Total files: {len(inventory_df)}")

if len(inventory_df):
    print("\nFiles by extension:")
    print(
        inventory_df
        .groupby("extension")
        .agg(
            files=("relative_path", "count"),
            total_mb=("size_mb", "sum")
        )
        .sort_values("total_mb", ascending=False)
        .to_string()
    )


# ------------------------------------------------
# 3. Large files
# ------------------------------------------------

print("\n" + "=" * 70)
print("[3/6] Checking large files...")
print("=" * 70)

large_files = inventory_df[
    inventory_df["size_mb"] >= 10
].sort_values("size_mb", ascending=False)

if len(large_files):
    print("\nFiles >= 10 MB:")
    print(
        large_files[
            ["relative_path", "extension", "size_mb"]
        ].to_string(index=False)
    )
else:
    print("No files >= 10 MB.")


# ------------------------------------------------
# 4. Important technical artifacts
# ------------------------------------------------

print("\n" + "=" * 70)
print("[4/6] Checking expected technical artifacts...")
print("=" * 70)

expected_patterns = {
    "notebooks": [
        "*.ipynb"
    ],
    "python_scripts": [
        "*.py"
    ],
    "csv_outputs": [
        "*.csv"
    ],
    "pdf_outputs": [
        "*.pdf"
    ],
    "model_files": [
        "*.pkl",
        "*.joblib",
        "*.pt",
        "*.pth"
    ],
    "documentation": [
        "*.md",
        "*.docx"
    ]
}

for category, patterns in expected_patterns.items():

    matches = []

    for pattern in patterns:
        matches.extend(REPO_ROOT.rglob(pattern))

    matches = [
        p for p in matches
        if ".git" not in p.parts
    ]

    print(f"\n{category.upper()}: {len(matches)}")

    for p in sorted(matches):
        size_mb = p.stat().st_size / (1024 * 1024)
        print(f"  {p.relative_to(REPO_ROOT)} ({size_mb:.2f} MB)")


# ------------------------------------------------
# 5. Final ML outputs
# ------------------------------------------------

print("\n" + "=" * 70)
print("[5/6] Checking final ML output directory...")
print("=" * 70)

OUTPUT_DIR = REPO_ROOT / "work" / "outputs"

if OUTPUT_DIR.exists():

    output_files = []

    for p in OUTPUT_DIR.rglob("*"):
        if p.is_file():
            output_files.append({
                "file": str(p.relative_to(OUTPUT_DIR)),
                "size_mb": round(
                    p.stat().st_size / (1024 * 1024), 4
                )
            })

    output_df = pd.DataFrame(output_files)

    print(f"Output files: {len(output_df)}")

    if len(output_df):
        print("\nCurrent outputs:")
        print(output_df.to_string(index=False))

else:
    print("WARNING: work/outputs directory not found.")


# ------------------------------------------------
# 6. Git status
# ------------------------------------------------

print("\n" + "=" * 70)
print("[6/6] Git status...")
print("=" * 70)

import subprocess

result = subprocess.run(
    ["git", "-C", str(REPO_ROOT), "status", "--short"],
    capture_output=True,
    text=True
)

print(result.stdout if result.stdout.strip() else "Working tree clean.")

print("\n" + "=" * 70)
print("=== FINAL REPOSITORY AUDIT COMPLETE ===")
print("=" * 70)

print("""
IMPORTANT:
- No model retraining performed.
- No validation tuning performed.
- No test evaluation performed.
- No files deleted.
- No files moved.
- No model artifacts modified.

Next step after reviewing this output:
FINAL ARTIFACT ORGANIZATION.
""")

======================================================================
=== FLYRANK — FINAL REPOSITORY AUDIT ===
======================================================================

[1/6] Repository structure...

FlyRank-ML-Internship-GIT/
  .gitignore (0.00 MB)
  AGENTS.md (0.00 MB)
  CLAUDE.md (0.00 MB)
  DATA_USE.md (0.00 MB)
  GUIDE.md (0.01 MB)
  LICENSE (0.00 MB)
  README.md (0.01 MB)
  SETUP.md (0.00 MB)
  requirements.txt (0.00 MB)
      content_refresh_anonymized.csv (6.42 MB)
    README.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
        SKILL.md (0.00 MB)
        SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
      SKILL.md (0.00 MB)
    data-dictionary.md (0.01 MB)
    flyrank-seo-research-march-2026.pdf (0.19 MB)
    index.html (0.02 MB)
    intern-free-tooling-guide.md (0.01 MB)
    ml-core-foundation-framework.md (0.03 MB)
    ml-intern-dataset-and-lane-guide.md (0.04 MB)
    model_report.md (0.00 MB)
    refresh_queue_sample.csv (0.07 MB)
      action_mix.svg (0.00 MB)
      confidence_mix.svg (0.00 MB)
      top_feature_importance.svg (0.00 MB)
      top_reason_codes.svg (0.00 MB)
      trend_distribution.svg (0.00 MB)
    01_first_look_and_discovery.ipynb (0.06 MB)
    02_your_first_readable_model.ipynb (0.03 MB)
    03_working_with_the_full_release.ipynb (0.01 MB)
      data-path-smoke.yml (0.00 MB)
      smoke-test.yml (0.00 MB)
    README.md (0.00 MB)
    capstone_report_template.md (0.00 MB)
      .gitkeep (0.00 MB)
      current_population_baseline.csv (108.41 MB)
      refresh_queue_sample.csv (0.07 MB)
      rf_feature_importance.csv (0.00 MB)
      rf_test_ndcg_audit.csv (0.00 MB)
      rf_validation_client_robustness.csv (0.00 MB)
      rf_validation_error_analysis.csv (9.35 MB)
      rf_validation_error_buckets.csv (0.00 MB)
      rf_validation_ndcg_audit.csv (0.00 MB)
      rf_validation_ranking_audit.csv (5.73 MB)
      rf_validation_residual_buckets.csv (0.00 MB)
      rf_validation_residual_diagnostics.csv (8.02 MB)
      week7_ranked_action_queue.csv (2.33 MB)
      capstone.ipynb (0.74 MB)
      w01_research_question.ipynb (0.01 MB)
      w02_ml_task_framing.ipynb (0.02 MB)
      w03_data_contract.ipynb (0.13 MB)
      w03_feature_leakage_check.ipynb (0.00 MB)
      w04_baseline_score.ipynb (0.04 MB)
      w04_signal_audit.ipynb (0.00 MB)
      w05_model.ipynb (0.04 MB)
      w06_validation_audit.ipynb (0.04 MB)
      w07_action_playbook.ipynb (0.03 MB)
    README.md (0.00 MB)
    paper_url.txt (0.00 MB)
    01_prepare_features.py (0.00 MB)
    02_baseline_score.py (0.00 MB)
    03_train_model.py (0.01 MB)
    04_evaluate_and_export.py (0.01 MB)
    05_build_pdf_report.py (0.02 MB)
    ml_utils.py (0.01 MB)
    run_all.py (0.00 MB)

======================================================================
[2/6] Building complete file inventory...
======================================================================
Total files: 76

Files by extension:
           files  total_mb
extension
.csv          14  140.4051
.ipynb        13    1.1386
.pdf           1    0.1907
.md           28    0.1544
.py            7    0.0618
.html          1    0.0228
.svg           5    0.0109
.yml           2    0.0039
               3    0.0021
.txt           2    0.0002

======================================================================
[3/6] Checking large files...
======================================================================

Files >= 10 MB:
                               relative_path extension  size_mb
work/outputs/current_population_baseline.csv      .csv 108.4118

======================================================================
[4/6] Checking expected technical artifacts...
======================================================================

NOTEBOOKS: 13
  notebooks/01_first_look_and_discovery.ipynb (0.06 MB)
  notebooks/02_your_first_readable_model.ipynb (0.03 MB)
  notebooks/03_working_with_the_full_release.ipynb (0.01 MB)
  work/notebooks/capstone.ipynb (0.74 MB)
  work/notebooks/w01_research_question.ipynb (0.01 MB)
  work/notebooks/w02_ml_task_framing.ipynb (0.02 MB)
  work/notebooks/w03_data_contract.ipynb (0.13 MB)
  work/notebooks/w03_feature_leakage_check.ipynb (0.00 MB)
  work/notebooks/w04_baseline_score.ipynb (0.04 MB)
  work/notebooks/w04_signal_audit.ipynb (0.00 MB)
  work/notebooks/w05_model.ipynb (0.04 MB)
  work/notebooks/w06_validation_audit.ipynb (0.04 MB)
  work/notebooks/w07_action_playbook.ipynb (0.03 MB)

PYTHON_SCRIPTS: 7
  scripts/01_prepare_features.py (0.00 MB)
  scripts/02_baseline_score.py (0.00 MB)
  scripts/03_train_model.py (0.01 MB)
  scripts/04_evaluate_and_export.py (0.01 MB)
  scripts/05_build_pdf_report.py (0.02 MB)
  scripts/ml_utils.py (0.01 MB)
  scripts/run_all.py (0.00 MB)

CSV_OUTPUTS: 14
  data/raw/content_refresh_anonymized.csv (6.42 MB)
  outputs/refresh_queue_sample.csv (0.07 MB)
  work/outputs/current_population_baseline.csv (108.41 MB)
  work/outputs/refresh_queue_sample.csv (0.07 MB)
  work/outputs/rf_feature_importance.csv (0.00 MB)
  work/outputs/rf_test_ndcg_audit.csv (0.00 MB)
  work/outputs/rf_validation_client_robustness.csv (0.00 MB)
  work/outputs/rf_validation_error_analysis.csv (9.35 MB)
  work/outputs/rf_validation_error_buckets.csv (0.00 MB)
  work/outputs/rf_validation_ndcg_audit.csv (0.00 MB)
  work/outputs/rf_validation_ranking_audit.csv (5.73 MB)
  work/outputs/rf_validation_residual_buckets.csv (0.00 MB)
  work/outputs/rf_validation_residual_diagnostics.csv (8.02 MB)
  work/outputs/week7_ranked_action_queue.csv (2.33 MB)

PDF_OUTPUTS: 1
  docs/flyrank-seo-research-march-2026.pdf (0.19 MB)

MODEL_FILES: 0

DOCUMENTATION: 28
  AGENTS.md (0.00 MB)
  CLAUDE.md (0.00 MB)
  DATA_USE.md (0.00 MB)
  GUIDE.md (0.01 MB)
  README.md (0.01 MB)
  SETUP.md (0.00 MB)
  docs/data-dictionary.md (0.01 MB)
  docs/intern-free-tooling-guide.md (0.01 MB)
  docs/ml-core-foundation-framework.md (0.03 MB)
  docs/ml-intern-dataset-and-lane-guide.md (0.04 MB)
  outputs/model_report.md (0.00 MB)
  skills/README.md (0.00 MB)
  skills/auditing-signals/SKILL.md (0.00 MB)
  skills/building-baselines/SKILL.md (0.00 MB)
  skills/deploying-static-pages/SKILL.md (0.00 MB)
  skills/directing-your-ai-assistant/SKILL.md (0.00 MB)
  skills/flyrank/flyrank-context/SKILL.md (0.00 MB)
  skills/flyrank/flyrank-data/SKILL.md (0.00 MB)
  skills/framing-ml-problems/SKILL.md (0.00 MB)
  skills/hunting-leakage-and-validating/SKILL.md (0.00 MB)
  skills/querying-big-datasets/SKILL.md (0.00 MB)
  skills/training-honest-models/SKILL.md (0.00 MB)
  skills/writing-data-contracts/SKILL.md (0.00 MB)
  skills/writing-honest-claims/SKILL.md (0.00 MB)
  skills/writing-research-papers/SKILL.md (0.00 MB)
  submission/README.md (0.00 MB)
  work/README.md (0.00 MB)
  work/capstone_report_template.md (0.00 MB)

======================================================================
[5/6] Checking final ML output directory...
======================================================================
Output files: 13

Current outputs:
                                  file  size_mb
       current_population_baseline.csv 108.4118
       rf_validation_ranking_audit.csv   5.7325
              refresh_queue_sample.csv   0.0708
                rf_test_ndcg_audit.csv   0.0003
          rf_validation_ndcg_audit.csv   0.0003
    rf_validation_residual_buckets.csv   0.0010
       rf_validation_error_buckets.csv   0.0008
             rf_feature_importance.csv   0.0048
         week7_ranked_action_queue.csv   2.3287
   rf_validation_client_robustness.csv   0.0010
                              .gitkeep   0.0000
      rf_validation_error_analysis.csv   9.3493
rf_validation_residual_diagnostics.csv   8.0170

======================================================================
[6/6] Git status...
======================================================================
Working tree clean.

======================================================================
=== FINAL REPOSITORY AUDIT COMPLETE ===
======================================================================

IMPORTANT:
- No model retraining performed.
- No validation tuning performed.
- No test evaluation performed.
- No files deleted.
- No files moved.
- No model artifacts modified.

Next step after reviewing this output:
FINAL ARTIFACT ORGANIZATION.

In [ ]:
from pathlib import Path
import shutil

REPO = Path("/content/FlyRank-ML-Internship-GIT")
OUTPUTS = REPO / "work" / "outputs"
FINAL = REPO / "submission" / "technical_outputs"
LOCAL = REPO / "work" / "local_only"

print("=" * 70)
print("=== FLYRANK — FINAL ARTIFACT ORGANIZATION ===")
print("=" * 70)

# ------------------------------------------------------------
# 1. Create final directories
# ------------------------------------------------------------

print("\n[1/4] Creating final artifact directories...")

FINAL.mkdir(parents=True, exist_ok=True)
LOCAL.mkdir(parents=True, exist_ok=True)

print("Created:")
print(" - submission/technical_outputs/")
print(" - work/local_only/")


# ------------------------------------------------------------
# 2. Move final technical evidence
# ------------------------------------------------------------

print("\n[2/4] Organizing technical evidence...")

technical_files = [
    "rf_feature_importance.csv",
    "rf_test_ndcg_audit.csv",
    "rf_validation_client_robustness.csv",
    "rf_validation_error_analysis.csv",
    "rf_validation_error_buckets.csv",
    "rf_validation_ndcg_audit.csv",
    "rf_validation_ranking_audit.csv",
    "rf_validation_residual_buckets.csv",
    "rf_validation_residual_diagnostics.csv",
    "week7_ranked_action_queue.csv",
]

for filename in technical_files:
    source = OUTPUTS / filename
    destination = FINAL / filename

    if source.exists():
        shutil.copy2(source, destination)
        print(f"  COPIED: {filename}")
    else:
        print(f"  MISSING: {filename}")


# ------------------------------------------------------------
# 3. Move oversized local-only baseline
# ------------------------------------------------------------

print("\n[3/4] Handling oversized baseline artifact...")

large_baseline = OUTPUTS / "current_population_baseline.csv"
local_baseline = LOCAL / "current_population_baseline.csv"

if large_baseline.exists():
    shutil.copy2(large_baseline, local_baseline)

    size_mb = local_baseline.stat().st_size / (1024 * 1024)

    print(
        f"  LOCAL ONLY: current_population_baseline.csv "
        f"({size_mb:.2f} MB)"
    )
else:
    print("  Baseline file not found.")


# ------------------------------------------------------------
# 4. Verify organization
# ------------------------------------------------------------

print("\n[4/4] Verifying final organization...")

print("\nSubmission technical outputs:")

for p in sorted(FINAL.iterdir()):
    if p.is_file():
        size_mb = p.stat().st_size / (1024 * 1024)
        print(
            f"  {p.name:<45} "
            f"{size_mb:>8.2f} MB"
        )

print("\nLocal-only artifacts:")

for p in sorted(LOCAL.iterdir()):
    if p.is_file():
        size_mb = p.stat().st_size / (1024 * 1024)
        print(
            f"  {p.name:<45} "
            f"{size_mb:>8.2f} MB"
        )

print("\n" + "=" * 70)
print("=== ARTIFACT ORGANIZATION COMPLETE ===")
print("=" * 70)

print("""
No model retraining.
No evaluation changes.
No diagnostic results modified.
No original files deleted.
No test data changed.

Next:
STEP 2 — CAPSTONE NOTEBOOK FINAL CLEANUP.
""")

======================================================================
=== FLYRANK — FINAL ARTIFACT ORGANIZATION ===
======================================================================

[1/4] Creating final artifact directories...
Created:
 - submission/technical_outputs/
 - work/local_only/

[2/4] Organizing technical evidence...
  COPIED: rf_feature_importance.csv
  COPIED: rf_test_ndcg_audit.csv
  COPIED: rf_validation_client_robustness.csv
  COPIED: rf_validation_error_analysis.csv
  COPIED: rf_validation_error_buckets.csv
  COPIED: rf_validation_ndcg_audit.csv
  COPIED: rf_validation_ranking_audit.csv
  COPIED: rf_validation_residual_buckets.csv
  COPIED: rf_validation_residual_diagnostics.csv
  COPIED: week7_ranked_action_queue.csv

[3/4] Handling oversized baseline artifact...
  LOCAL ONLY: current_population_baseline.csv (108.41 MB)

[4/4] Verifying final organization...

Submission technical outputs:
  rf_feature_importance.csv                         0.00 MB
  rf_test_ndcg_audit.csv                            0.00 MB
  rf_validation_client_robustness.csv               0.00 MB
  rf_validation_error_analysis.csv                  9.35 MB
  rf_validation_error_buckets.csv                   0.00 MB
  rf_validation_ndcg_audit.csv                      0.00 MB
  rf_validation_ranking_audit.csv                   5.73 MB
  rf_validation_residual_buckets.csv                0.00 MB
  rf_validation_residual_diagnostics.csv            8.02 MB
  week7_ranked_action_queue.csv                     2.33 MB

Local-only artifacts:
  current_population_baseline.csv                 108.41 MB

======================================================================
=== ARTIFACT ORGANIZATION COMPLETE ===
======================================================================

No model retraining.
No evaluation changes.
No diagnostic results modified.
No original files deleted.
No test data changed.

Next:
STEP 2 — CAPSTONE NOTEBOOK FINAL CLEANUP.

In [ ]:
# ================================================================
# FLYRANK — CAPSTONE NOTEBOOK FINAL CLEANUP
# ================================================================

from pathlib import Path
import json
import shutil

REPO = Path("/content/FlyRank-ML-Internship-GIT")
CAPSTONE = REPO / "work" / "notebooks" / "capstone.ipynb"
BACKUP = CAPSTONE.with_name("capstone_pre_final_cleanup.ipynb")

print("=" * 70)
print("=== FLYRANK — CAPSTONE NOTEBOOK FINAL CLEANUP ===")
print("=" * 70)

# ------------------------------------------------------------
# 0. Load + backup
# ------------------------------------------------------------

with open(CAPSTONE, "r", encoding="utf-8") as f:
    nb = json.load(f)

shutil.copy2(CAPSTONE, BACKUP)

print("\n[0/5] Backup created...")
print(f"Backup: {BACKUP.name}")


# ------------------------------------------------------------
# 1. Remove duplicate consecutive markdown headings
# ------------------------------------------------------------

print("\n[1/5] Cleaning duplicate section headings...")

cells = nb["cells"]
cleaned = []

previous_heading = None

for cell in cells:

    if cell.get("cell_type") == "markdown":

        text = "".join(cell.get("source", [])).strip()

        # Normalize heading for comparison
        if text.startswith("#"):
            normalized = text.lower().replace(" ", "").strip()

            if normalized == previous_heading:
                print("  Removed duplicate heading:")
                print("   ", text.splitlines()[0])
                continue

            previous_heading = normalized
        else:
            previous_heading = None

    else:
        previous_heading = None

    cleaned.append(cell)

nb["cells"] = cleaned

print(f"Cells before: {len(cells)}")
print(f"Cells after : {len(cleaned)}")


# ------------------------------------------------------------
# 2. Add final technical-results section
# ------------------------------------------------------------

print("\n[2/5] Adding final technical-results summary...")

final_results = r"""
# Final ML Evaluation — Technical Evidence

This section records the final Random Forest evaluation after the validation and test audits were completed.

## Final test regression metrics

- **MAE:** 1.2682
- **RMSE:** 10.8692

## Final test ranking performance

| K | Random Forest NDCG@K | Historical-organic baseline | Improvement |
|---:|---:|---:|---:|
| 20 | 0.9248 | 0.8113 | +0.1135 |
| 50 | 0.9366 | 0.8099 | +0.1267 |
| 100 | 0.9369 | 0.7756 | +0.1614 |
| 500 | 0.8633 | 0.7244 | +0.1389 |
| 1000 | 0.8197 | 0.6971 | +0.1226 |

The Random Forest outperformed the historical-organic baseline at every evaluated test-set cutoff.

## Top-K precision

| K | Random Forest | Baseline |
|---:|---:|---:|
| 20 | 1.000 | 0.950 |
| 50 | 1.000 | 0.960 |
| 100 | 1.000 | 0.930 |

## Validation ranking evidence

The corrected validation NDCG audit also showed Random Forest outperforming the baseline at every evaluated cutoff:

- NDCG@20: 0.6457 vs 0.5522
- NDCG@50: 0.6951 vs 0.5306
- NDCG@100: 0.7188 vs 0.5815
- NDCG@500: 0.7267 vs 0.6615
- NDCG@1000: 0.7524 vs 0.7040

## Feature importance

The strongest Random Forest feature was:

**organic_sessions_hist — importance 0.1597**

The top five features accounted for approximately **53.2%** of total feature importance, while the top twenty accounted for approximately **83.7%**.

## Error-analysis finding

The model performs substantially better on the majority of low-volume observations than on extreme future-growth cases. Validation error increases sharply as the actual future organic-session count increases.

For example:

- Actual ≥ 100: MAE ≈ 153.27
- Actual ≥ 250: MAE ≈ 322.11
- Actual ≥ 500: MAE ≈ 633.83

This indicates that the model is effective for **ranking promising content**, but point predictions for extreme traffic-growth cases remain difficult.

## Client robustness

Validation performance varies considerably across clients. The largest client has both the highest error and the highest positive-target rate, indicating that client-specific traffic distributions are an important limitation.

## Evaluation integrity

- No test-based model tuning was performed.
- No test-based model selection was performed.
- The final test set was evaluated after model development.
- Validation and test predictions were aligned to their original dataframe row order.
- The authoritative future target was used for final evaluation.
- The Random Forest was not retrained during the diagnostic phase.
"""

nb["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": final_results.strip().splitlines(True)
})


# ------------------------------------------------------------
# 3. Add final artifact references
# ------------------------------------------------------------

print("\n[3/5] Adding final artifact references...")

artifact_text = r"""
## Final Technical Artifacts

The final technical evidence is stored under:

`submission/technical_outputs/`

Key artifacts include:

- `rf_test_ndcg_audit.csv`
- `rf_validation_ndcg_audit.csv`
- `rf_feature_importance.csv`
- `rf_validation_error_analysis.csv`
- `rf_validation_error_buckets.csv`
- `rf_validation_residual_diagnostics.csv`
- `rf_validation_residual_buckets.csv`
- `rf_validation_client_robustness.csv`
- `rf_validation_ranking_audit.csv`
- `week7_ranked_action_queue.csv`

The large `current_population_baseline.csv` artifact is retained under:

`work/local_only/`

because it is approximately 108 MB.
"""

nb["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": artifact_text.strip().splitlines(True)
})


# ------------------------------------------------------------
# 4. Save
# ------------------------------------------------------------

print("\n[4/5] Saving cleaned notebook...")

with open(CAPSTONE, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Saved: {CAPSTONE}")


# ------------------------------------------------------------
# 5. Verify
# ------------------------------------------------------------

print("\n[5/5] Verifying final notebook...")

with open(CAPSTONE, "r", encoding="utf-8") as f:
    verify_nb = json.load(f)

print("Final cell count:", len(verify_nb["cells"]))

# Count duplicate consecutive markdown headings again
duplicates = 0
previous_heading = None

for cell in verify_nb["cells"]:

    if cell.get("cell_type") == "markdown":
        text = "".join(cell.get("source", [])).strip()

        if text.startswith("#"):
            normalized = text.lower().replace(" ", "").strip()

            if normalized == previous_heading:
                duplicates += 1

            previous_heading = normalized
        else:
            previous_heading = None
    else:
        previous_heading = None

print("Duplicate consecutive headings:", duplicates)

print("\n" + "=" * 70)
print("=== CAPSTONE NOTEBOOK CLEANUP COMPLETE ===")
print("=" * 70)

print("""
Backup preserved:
capstone_pre_final_cleanup.ipynb

Notebook modified:
capstone.ipynb

Changes:
- Removed duplicate consecutive headings
- Added final ML evaluation evidence
- Added final technical artifact references
- Preserved existing notebook content
- No model retraining
- No test rerun
- No data modification
""")

======================================================================
=== FLYRANK — CAPSTONE NOTEBOOK FINAL CLEANUP ===
======================================================================

[0/5] Backup created...
Backup: capstone_pre_final_cleanup.ipynb

[1/5] Cleaning duplicate section headings...
Cells before: 50
Cells after : 50

[2/5] Adding final technical-results summary...

[3/5] Adding final artifact references...

[4/5] Saving cleaned notebook...
Saved: /content/FlyRank-ML-Internship-GIT/work/notebooks/capstone.ipynb

[5/5] Verifying final notebook...
Final cell count: 52
Duplicate consecutive headings: 0

======================================================================
=== CAPSTONE NOTEBOOK CLEANUP COMPLETE ===
======================================================================

Backup preserved:
capstone_pre_final_cleanup.ipynb

Notebook modified:
capstone.ipynb

Changes:
- Removed duplicate consecutive headings
- Added final ML evaluation evidence
- Added final technical artifact references
- Preserved existing notebook content
- No model retraining
- No test rerun
- No data modification

In [ ]:
# ================================================================
# FLYRANK — WAREHOUSE FINAL PAPER RESULTS EXTRACTION
# ================================================================

print("=" * 70)
print("FLYRANK — WAREHOUSE FINAL PAPER RESULTS EXTRACTION")
print("=" * 70)

# ------------------------------------------------
# 1. FIND IMPORTANT DATAFRAME OBJECTS
# ------------------------------------------------

print("\n[1] DATAFRAME INVENTORY")

snapshot = list(globals().items())

for name, obj in snapshot:
    try:
        if hasattr(obj, "shape") and hasattr(obj, "columns"):
            print(f"{name}: {obj.shape}")
    except Exception:
        pass


# ------------------------------------------------
# 2. IDENTIFY LIKELY WAREHOUSE DATAFRAME
# ------------------------------------------------

print("\n[2] LARGE DATAFRAMES")

for name, obj in snapshot:
    try:
        if hasattr(obj, "shape") and hasattr(obj, "columns"):
            rows, cols = obj.shape
            if rows > 100000:
                print(f"{name}: {obj.shape}")
                print("Columns:", list(obj.columns)[:30])
    except Exception:
        pass


# ------------------------------------------------
# 3. DATASET / COLUMN INFORMATION
# ------------------------------------------------

print("\n[3] CANDIDATE DATAFRAME DETAILS")

candidate_names = [
    "df",
    "data",
    "warehouse",
    "warehouse_df",
    "march_df",
    "march_2026",
    "march_data",
    "train_df",
    "test_df",
    "model_df"
]

for name in candidate_names:
    if name in globals():
        obj = globals()[name]
        try:
            print(f"\n{name}: {obj.shape}")
            print("Columns:")
            print(list(obj.columns))
        except Exception:
            pass


# ------------------------------------------------
# 4. TARGET / TREND DISTRIBUTION
# ------------------------------------------------

print("\n[4] TARGET / TREND DISTRIBUTION")

for name, obj in snapshot:
    try:
        if hasattr(obj, "columns"):
            cols = set(obj.columns)

            if "trend_direction" in cols:
                print(f"\n{name} trend_direction:")
                print(obj["trend_direction"].value_counts(dropna=False))

            if "is_declining_label" in cols:
                print(f"\n{name} is_declining_label:")
                print(obj["is_declining_label"].value_counts(dropna=False))

    except Exception:
        pass


# ------------------------------------------------
# 5. CLIENT COVERAGE
# ------------------------------------------------

print("\n[5] CLIENT COVERAGE")

for name, obj in snapshot:
    try:
        if hasattr(obj, "columns") and "client_id" in obj.columns:
            print(
                f"{name}: "
                f"{obj['client_id'].nunique()} unique clients"
            )
    except Exception:
        pass


# ------------------------------------------------
# 6. DATE COVERAGE
# ------------------------------------------------

print("\n[6] DATE COVERAGE")

for name, obj in snapshot:
    try:
        if hasattr(obj, "columns"):
            date_cols = [
                c for c in obj.columns
                if any(x in c.lower() for x in
                       ["date", "month", "week", "timestamp"])
            ]

            if date_cols:
                print(f"\n{name}:")
                for c in date_cols[:10]:
                    try:
                        print(
                            c,
                            "min =", obj[c].min(),
                            "max =", obj[c].max(),
                            "unique =", obj[c].nunique()
                        )
                    except Exception:
                        pass
    except Exception:
        pass


# ------------------------------------------------
# 7. MODEL / METRIC OBJECTS
# ------------------------------------------------

print("\n[7] MODEL / METRIC OBJECTS")

for name, obj in snapshot:
    lname = name.lower()

    if any(x in lname for x in [
        "model",
        "rf",
        "baseline",
        "metric",
        "score",
        "ndcg",
        "precision",
        "evaluation",
        "audit"
    ]):
        try:
            print(
                f"{name}: "
                f"{type(obj).__name__}",
                getattr(obj, "shape", "")
            )
        except Exception:
            print(f"{name}: {type(obj).__name__}")


# ------------------------------------------------
# 8. SEARCH FOR RESULT VARIABLES
# ------------------------------------------------

print("\n[8] NUMERIC RESULT VARIABLES")

for name, obj in snapshot:
    lname = name.lower()

    if any(x in lname for x in [
        "precision",
        "recall",
        "accuracy",
        "mae",
        "rmse",
        "ndcg",
        "auc",
        "f1"
    ]):
        try:
            if isinstance(obj, (int, float)):
                print(name, "=", obj)
            elif hasattr(obj, "shape"):
                print(name, "=", obj.shape)
        except Exception:
            pass


# ------------------------------------------------
# 9. CSV OUTPUTS — READ EXISTING FINAL ARTIFACTS
# ------------------------------------------------

print("\n[9] EXISTING OUTPUT ARTIFACTS")

import os
import pandas as pd

output_dir = "/content/FlyRank-ML-Internship-GIT/work/outputs"

if os.path.exists(output_dir):

    for filename in sorted(os.listdir(output_dir)):

        if filename.endswith(".csv"):

            path = os.path.join(output_dir, filename)

            try:
                temp = pd.read_csv(path)

                print(f"\n--- {filename} ---")
                print("Shape:", temp.shape)
                print("Columns:", list(temp.columns))

                # Show small result files completely
                if len(temp) <= 20:
                    print(temp.to_string(index=False))

                # Otherwise show first few rows
                else:
                    print(temp.head(3).to_string(index=False))

            except Exception as e:
                print(filename, "READ ERROR:", e)


# ------------------------------------------------
# 10. FINAL SUMMARY
# ------------------------------------------------

print("\n" + "=" * 70)
print("WAREHOUSE PAPER EXTRACTION COMPLETE")
print("=" * 70)

print("""
Please send me the COMPLETE OUTPUT of this cell.

I will use it to rebuild the research paper around the
WAREHOUSE DATASET rather than the 30,000-row development dataset.
""")

## 1. Question

*The research question and the decision it supports.*



### Research Question

Can historical content, keyword, SEO, and web-analytics signals be used to estimate future organic performance and rank content pages according to their expected future performance?

More specifically, the study investigates whether historical signals—including organic traffic, search visibility, engagement, content characteristics, keyword characteristics, and related SEO features—can be used to estimate future organic sessions and produce a useful ranking of content pages for prioritization. The study evaluates whether a Random Forest model can produce a more effective ranking than a transparent rule-based baseline.

### Decision Supported

The resulting model is intended to support the prioritization of limited SEO and content-review capacity. Rather than requiring teams to manually inspect a large content inventory without a consistent prioritization mechanism, the system produces a ranked queue of pages based on their predicted future organic performance.

This ranking can help SEO and content teams decide which pages deserve earlier investigation, closer monitoring, or optimization review. A high-ranked page is not automatically considered a problem; instead, its position in the queue indicates that it should receive greater attention relative to lower-ranked pages.

The ranking is therefore designed to assist human decision-makers in determining the appropriate next action for each page, such as investigating its performance, reviewing the content for optimization opportunities, monitoring it over time, or leaving it unchanged.

Importantly, the system is designed as a **decision-support mechanism rather than an automated content-recommendation system**. The Random Forest model estimates future organic performance and ranks pages accordingly; it does not independently determine that content should be changed or prescribe a specific optimization action. Final decisions remain with SEO and content specialists.

## 2. Data

*Which release, which tables, date windows, what you excluded and why. Public-safe.*


This study was conducted using data from the FlyRank analytics warehouse and a derived, anonymized content-performance modeling population. The warehouse provided the underlying environment from which historical content, search, SEO, and web-analytics signals were identified. A controlled extraction and preprocessing workflow was then used to construct the final modeling population, generate the future-performance target, prevent leakage, and create the training, validation, and held-out test populations.

### 2.1 Warehouse Data and Research Context

The FlyRank warehouse contains historical records associated with content pages, keywords, search performance, website traffic, content characteristics, and related SEO signals. During the development of the final workflow, warehouse data were examined to establish the available data grain, historical coverage, feature availability, temporal relationships, and potential sources of target leakage.

The warehouse was treated as the underlying source rather than directly using every warehouse record as a modeling observation. Records relevant to the research objective were extracted and subjected to eligibility, temporal, and quality constraints before entering the final modeling population.

This distinction is important because the underlying warehouse is substantially larger than the final supervised-learning population. The reported model results therefore refer specifically to the controlled warehouse-derived population used for training and evaluation.

### 2.2 Final Modeling Population

The modeling extraction initially identified **418,047 candidate records**. After applying the study's eligibility criteria, **324,998 records** remained eligible. Following target construction and final quality controls, **323,926 observations** formed the final modeling population.

Each observation represents a content-page and client context identified through pseudonymized identifiers. The final population contains historical information describing content characteristics, keyword characteristics, search demand, competition, historical search performance, and historical web-analytics behavior.

The principal source signals included:

* keyword character and token counts;
* URL character count;
* content creation and update dates;
* content type;
* search volume;
* competition and competition level;
* CPC;
* search intent;
* backlinks;
* category count;
* keyword creation date;
* provider and model metadata;
* character and word counts;
* publication and deletion status;
* historical Google Search Console signals;
* historical GA4 signals;
* historical organic sessions;
* direct, referral, social, paid, and AI traffic signals.

The final modeling population covered **53 pseudonymized clients**.

### 2.3 Temporal Coverage

The source extraction contained content creation dates ranging from **2024-11-22 through 2026-07-06**. After eligibility and temporal constraints were applied, the final modeling population used content creation dates extending from **2024-11-22 through 2026-04-01**.

Historical content-update dates extended through the available observation period, while keyword creation dates extended through **2026-03-31**. These temporal fields were used to establish historical context and derive features without using the future target outcome as a predictor.

The temporal construction was designed around the distinction between **historical information available to the model** and **future organic performance used as the target**. Records that did not satisfy the required temporal conditions were excluded from the final population. In total, **1,072 records** were excluded after the eligible population was identified.

### 2.4 Feature Construction

The final modeling workflow contained **51 predictor features before preprocessing**.

These features represented several categories of information:

1. **Keyword and search-demand signals**, including search volume, keyword length, competition, CPC, and search intent.

2. **Content characteristics**, including content type, word count, character count, and category-related information.

3. **Historical search-performance signals**, including impressions, clicks, and average search position.

4. **Historical traffic signals**, including organic sessions, GA4 sessions, pageviews, and other available traffic channels.

5. **Engagement and derived performance signals**, including historical CTR, organic-session share, AI-session share, direct-session share, and pageviews per session.

6. **Availability and missingness indicators**, including indicators describing the availability of GSC and GA4 information and selected missing source values.

7. **Temporal features**, including content age and keyword age.

Date variables were converted into model-compatible representations where appropriate. Derived temporal variables captured the age of content and keywords, while calendar-related components were generated during preprocessing where applicable.

The preprocessing workflow expanded the representation to **90 model-input features** for the final Random Forest evaluation matrix. Categorical variables were encoded and numerical variables were processed consistently across the training, validation, and test populations.

Highly skewed traffic variables were represented using logarithmic transformations where appropriate. Missing numerical information was handled through the preprocessing pipeline, with explicit missingness indicators retained for selected variables where the availability of the underlying signal could itself be informative.

### 2.5 Target Definition

The final supervised-learning target was **future organic sessions**.

For each eligible content observation, information available from the historical period was used to construct the predictor variables, while organic sessions observed during the subsequent target window were retained separately as the outcome.

The modeling task can therefore be represented as:

$$
\hat{y}_i = f(X_i)
$$

where \(X_i\) represents the historical content, keyword, SEO, search-performance, traffic, engagement, and temporal signals available for observation \(i\), and \(y_i\) represents its subsequent future organic-session outcome.

This formulation makes the task a **future-performance prediction and ranking problem**, rather than a direct classification of whether a page is currently declining.

The final modeling population contained **17,478 observations with positive target values**, while many observations had zero future organic sessions. The resulting target distribution was explicitly considered during model evaluation and error analysis.

### 2.6 Data Splitting and Evaluation Populations

The final modeling population was divided into training, validation, and held-out test populations.

| Population    | Observations |
| ------------- | -----------: |
| Training      |  **245,323** |
| Validation    |   **59,860** |
| Held-out test |   **18,743** |
| **Total**     |  **323,926** |

The validation population was used for model comparison, ranking diagnostics, residual and error analysis, and client-level robustness analysis.

The held-out test population was reserved for the final evaluation of the selected modeling workflow. The final test audit confirmed **18,743 observations**, with the corresponding processed feature matrix containing **90 features**.

The split strategy preserved client-level separation so that the evaluation could measure performance on client contexts not used to train the model. Client identifiers were therefore retained for grouping and diagnostic purposes rather than treated as ordinary predictive variables.

### 2.7 Leakage Prevention

Leakage prevention was a central requirement because the objective is to predict future organic performance using information that would have been available before the outcome period.

Future organic sessions were therefore kept outside the predictor matrix. Target information and variables representing future outcomes were not used to generate model features.

Content and client identifiers were treated as keys rather than predictive signals. In particular, `content_hash_id` and `client_hash_id` were retained for identifying observations and performing grouped analysis but were excluded from the final predictive representation.

Historical performance variables were included only in their historical form. The workflow therefore distinguished between information available before the target period and the future organic-session outcome used for evaluation.

Leakage checks were also performed during the development workflow to identify and remove features that could inadvertently expose outcome information.

### 2.8 Baseline

A transparent rule-based baseline was constructed to provide a non-machine-learning reference point.

The baseline generated a ranking using predefined historical SEO and performance signals rather than learned model parameters. Its purpose was not to represent an optimal heuristic, but to establish a reproducible benchmark against which the Random Forest ranking could be evaluated.

Both the baseline and Random Forest were evaluated against the same future organic-session outcomes and at the same ranking depths. This ensured that observed differences in NDCG reflected differences in ranking quality rather than differences in evaluation procedure.

### 2.9 Model and Ranking Objective

The primary machine-learning model in the final workflow was a **Random Forest Regressor**.

The model was trained to estimate future organic sessions from the engineered historical feature representation. Its continuous predictions were then used to rank content pages from higher to lower predicted future performance.

Because the operational objective is prioritization rather than only point prediction, ranking quality was a central component of evaluation. **Normalized Discounted Cumulative Gain (NDCG)** was calculated at multiple ranking depths, including:

* NDCG@20;
* NDCG@50;
* NDCG@100;
* NDCG@500;
* NDCG@1000.

The use of multiple ranking depths reflects different levels of review capacity. A team able to investigate only a small number of pages can focus on the highest-ranked portion of the queue, while larger review capacity can be evaluated using deeper ranking cutoffs.

Regression metrics such as **MAE** and **RMSE** were also retained to characterize the model's point-prediction error. These metrics complement rather than replace the ranking evaluation because the operational output is a prioritized page ranking.

### 2.10 Client-Level Robustness

Aggregate metrics can conceal differences in model behavior across client populations. Client-level diagnostics were therefore conducted on the validation population.

The robustness analysis examined observations per client, actual and predicted future-session distributions, MAE, RMSE, positive-target counts, and positive-target rates for pseudonymized clients.

The validation robustness audit covered **8 clients**, providing an additional view of how performance varied across client populations with different traffic distributions and future-session characteristics.

These diagnostics were treated as robustness evidence rather than as a claim that the model performs identically across all clients.

### 2.11 Public-Safe Data Handling

All identifiers used in the research outputs are pseudonymized. Public-facing artifacts use hashed client and content identifiers rather than client names, URLs, credentials, or other directly identifying information.

Reported artifacts consist of aggregate model metrics, feature-importance summaries, ranking diagnostics, error analyses, residual diagnostics, client-level robustness summaries, and pseudonymized examples.

The public research artifact does not require exposing private client names, private URLs, credentials, or other directly identifying information.

### 2.12 Relationship to the Development Dataset

An earlier stage of the project used a **30,000-row anonymized development dataset** to establish the initial analytical workflow, investigate candidate signals, construct an early baseline, and test initial modeling approaches.

That development dataset was an intermediate stage of the project rather than the final experimental population.

The final study extends the workflow to the larger **323,926-observation warehouse-derived modeling population**. Consequently, the performance results reported in this paper are based on the final warehouse-derived workflow and its corresponding validation and held-out test populations.

The final evaluation therefore reports results from **59,860 validation observations** and **18,743 held-out test observations**, with the **Random Forest Regressor** evaluated against the rule-based baseline using ranking-oriented and regression-oriented diagnostics.

## 3. Methodology

*Assumptions, features, label definition, baseline, validation design, leakage checks.*


The methodology was designed to answer a practical question: can historical content, search, SEO, and web-analytics signals be used to estimate future organic performance and rank content pages according to their potential priority for human review?

The final workflow followed four main stages:

1. data and signal validation;
2. transparent baseline construction;
3. supervised Random Forest modeling; and
4. ranking-based evaluation and action generation.

The final study extends the earlier development work to a larger warehouse-derived modeling population. The reported results therefore reflect the final warehouse-based dataset rather than the original 30,000-row development sample.

### 3.1 Assumptions

The analysis assumes that historical content, keyword, SEO, search-performance, traffic, and engagement signals contain useful information for estimating subsequent organic performance.

The objective is **prioritization rather than automatic decision-making**. A high model score indicates that a page is ranked as a stronger candidate for attention based on its predicted future organic performance; it does not mean that the page should automatically be refreshed or optimized.

The analysis also assumes that historical information can be separated from the future target period. Predictor variables are therefore constructed from information available before the target outcome, while future organic sessions are retained as the supervised-learning target.

Client-level differences may affect traffic patterns, search behavior, content strategy, and performance distributions. The evaluation therefore preserves client-level separation when constructing the modeling populations and includes client-level robustness diagnostics.

Finally, the model identifies statistical relationships in the available historical data. It does not establish that any individual feature causes future organic performance to increase or decrease.

### 3.2 Target definition

The final supervised-learning target was **future organic sessions**.

For each eligible content observation, historical information available before the target period was used to construct the predictor variables. Organic sessions observed during the subsequent target window were retained separately as the outcome.

The modeling task can therefore be represented as:

$$
\hat{y}_i = f(X_i)
$$

where \(X_i\) represents the historical content, keyword, SEO, search-performance, traffic, engagement, and temporal signals associated with observation \(i\), and \(y_i\) represents the corresponding future organic sessions.

This formulation changes the final modeling objective from reproducing an existing decline label to estimating future organic performance directly.

The final modeling population contained **323,926 observations**, including **17,478 observations with positive future-organic-session target values**. The substantial number of observations with zero target values was retained and explicitly considered during model evaluation.

The target was kept outside the predictor matrix throughout the modeling workflow.

### 3.3 Feature construction and preprocessing

The warehouse-derived extraction initially produced a broad set of historical content, keyword, SEO, search-performance, traffic, and temporal variables.

After eligibility filtering and feature construction, the final modeling representation contained **51 features before preprocessing**.

The feature set covered several major signal groups:

* keyword and search-demand characteristics;
* content characteristics;
* historical search-performance signals;
* historical web-analytics and traffic signals;
* engagement and derived performance measures;
* data-availability and missingness indicators; and
* temporal characteristics.

Keyword and search-demand signals included variables such as search volume, keyword length, competition, competition level, CPC, and search intent.

Content signals included content type, word count, character count, category-related information, publication status, and related content attributes.

Historical search-performance signals included impressions, clicks, CTR, and average search position where historical observations were available.

Historical traffic signals included organic sessions, GA4 sessions, pageviews, direct traffic, referral traffic, social traffic, paid traffic, and AI-related traffic measures.

Derived features included measures such as organic-session share, AI-session share, direct-session share, pageviews per session, content age, and keyword age.

Missingness and availability indicators were retained for selected variables where the availability of GSC or GA4 information could itself provide useful information.

Date variables were transformed into model-compatible temporal representations. Calendar components and age-related variables were generated during preprocessing where appropriate.

Traffic variables with highly skewed distributions were represented using logarithmic transformations where appropriate. Numerical and categorical preprocessing was applied consistently across the training, validation, and test populations.

After preprocessing and categorical encoding, the final model-input representation contained **90 processed features**.

The final test matrix therefore contained:

* **18,743 observations**; and
* **90 processed features**.

The same preprocessing logic was applied to all modeling populations without using information from the held-out test outcomes.

### 3.4 Baseline

Before evaluating the learned model, a transparent rule-based baseline was constructed.

The baseline provided a non-machine-learning reference ranking using historical SEO and performance signals available within the modeling workflow.

Its purpose was not to represent an optimal heuristic. Instead, it established a practical benchmark against which the additional value of the Random Forest could be measured.

The baseline and Random Forest were evaluated on the same held-out test observations using the same ranking framework.

This ensures that differences in measured ranking quality reflect the ordering produced by the two approaches rather than differences in the evaluation population.

### 3.5 Modeling populations and validation design

The final eligible modeling population contained **323,926 observations across 53 pseudonymized clients**.

The modeling workflow divided the final population into separate training, validation, and held-out test populations:

* **245,323 observations for training**;
* **59,860 observations for validation**; and
* **18,743 observations for final held-out testing**.

The validation population was used for model comparison, ranking diagnostics, error analysis, residual analysis, and client-level robustness analysis.

The final test population was reserved for the final ranking audit.

Client identifiers were retained for grouping and diagnostic purposes but were excluded from the predictive feature representation.

The split design was intended to prevent the model from receiving inappropriate predictive information from client identifiers and to provide a more realistic assessment of performance across client populations.

### 3.6 Model

The final supervised model was a **Random Forest Regressor**.

The model was trained to estimate future organic sessions from the processed historical feature representation.

Although the model produces a continuous estimate of future organic sessions, the operational output is a ranking. Pages are therefore ordered according to their predicted future organic performance.

This ranking allows an SEO or content team to identify pages that should receive earlier review based on the model's estimate.

The final model configuration produced:

* **Random Forest Regressor** as the selected model;
* **90 processed input features**;
* **18,743 held-out test observations**; and
* **18,743 successfully generated test predictions**.

The model was evaluated after the training and validation workflow had been completed. The final test results were not used to retrain the model or change the model selection process.

### 3.7 Ranking evaluation

Because the operational objective is to prioritize pages rather than simply minimize point-prediction error, the primary evaluation focused on **Normalized Discounted Cumulative Gain (NDCG)**.

NDCG evaluates the quality of a ranked list while assigning greater importance to observations appearing near the top of the ranking.

The final test audit evaluated ranking quality at five depths:

* **NDCG@20**;
* **NDCG@50**;
* **NDCG@100**;
* **NDCG@500**; and
* **NDCG@1000**.

The Random Forest was compared directly with the rule-based baseline on the same held-out test population.

|    K | Random Forest NDCG | Baseline NDCG | Improvement |
| ---: | -----------------: | ------------: | ----------: |
|   20 |         **0.9248** |        0.8113 | **+0.1135** |
|   50 |         **0.9366** |        0.8099 | **+0.1267** |
|  100 |         **0.9369** |        0.7756 | **+0.1614** |
|  500 |         **0.8633** |        0.7244 | **+0.1389** |
| 1000 |         **0.8197** |        0.6971 | **+0.1226** |

The strongest observed ranking result occurred at **NDCG@100**, where the Random Forest achieved **0.9369**, compared with **0.7756** for the baseline.

The Random Forest therefore produced a substantially stronger ranking than the transparent baseline across every evaluated ranking depth.

The improvement was largest at \(k=100\), where the observed NDCG difference was **+0.1614**.

### 3.8 Additional regression and ranking diagnostics

NDCG was treated as the primary operational ranking metric, but additional diagnostics were used to understand model behavior.

The validation workflow included error and residual analyses examining the relationship between predicted and observed future organic sessions.

These diagnostics included:

* validation error analysis;
* error buckets;
* residual buckets;
* residual diagnostics;
* ranking audits;
* NDCG audits; and
* client-level robustness analysis.

These analyses were used to determine whether aggregate ranking performance concealed systematic errors or differences across portions of the modeling population.

The resulting diagnostics were retained as technical evidence rather than being treated as alternative headline performance measures.

### 3.9 Client-level robustness

Aggregate performance can hide differences in model behavior across clients.

Therefore, the validation population was also examined at the client level using pseudonymized client identifiers.

The client robustness analysis examined measures including:

* observation counts;
* actual future-session means;
* predicted future-session means;
* MAE;
* RMSE;
* positive-target counts; and
* positive-target rates.

The validation robustness audit covered **8 clients**.

This analysis provides additional evidence about whether the model behaves consistently across different client populations rather than relying solely on aggregate performance.

Client-level results are interpreted as robustness diagnostics rather than as evidence that the model will perform identically for every future client.

### 3.10 Leakage prevention

Leakage prevention was treated as a central requirement because the objective is to estimate future organic performance from information available before that future outcome occurs.

Future organic sessions were therefore excluded from the predictor matrix and retained only as the supervised-learning target.

The identifiers `content_hash_id` and `client_hash_id` were treated as keys rather than predictive signals. They were retained where necessary for observation identification, grouping, and diagnostics but were excluded from the final predictive representation.

Historical performance variables were included only in their historical form. The workflow therefore distinguished between information available before the target period and the future organic-session outcome used for evaluation.

Eligibility and temporal filtering were also applied before the final modeling population was constructed. The modeling extraction initially identified **418,047 candidate records**, after which **324,998 records** remained eligible. Following final target construction and quality controls, **323,926 observations** formed the final modeling population.

A total of **1,072 records** were excluded after the eligible population was identified.

This filtering process was designed to ensure that observations entering the final modeling population satisfied the required temporal and data-quality conditions.

### 3.11 Test integrity

The final held-out test evaluation was performed only after the modeling and validation workflow had been completed.

The final test audit verified:

* **18,743 test observations**;
* **90 processed features**;
* successful generation of **18,743 predictions**;
* correct attachment of target and baseline rankings;
* absence of NaN values in the evaluated outputs; and
* NDCG values within the valid \([0,1]\) range.

The final audit also confirmed:

* **no model retraining**;
* **no test-based tuning**;
* **no model selection after observing final test results**; and
* **no modification of test data**.

The test set was therefore used as a final reporting population rather than as an additional source of modeling decisions.

### 3.12 Ranked action generation

After the Random Forest generated future-organic-session predictions, observations were ordered according to their predicted performance.

The resulting ranked queue provides a practical worklist for SEO and content teams.

The ranking can be supplemented with observable review signals such as:

* predicted future organic performance;
* content staleness;
* CTR;
* search position;
* content age;
* engagement signals; and
* other relevant historical SEO indicators.

These signals help reviewers investigate why a page may deserve attention, but they should not be interpreted as causal explanations of the Random Forest prediction.

The operational workflow is therefore:

**Rank → Review → Diagnose → Decide → Act → Monitor**

The model determines **review priority**, while the human reviewer determines whether a page should actually be refreshed, investigated further, monitored, left unchanged, or addressed through another intervention.

The purpose of the system is consequently not to automate content decisions, but to make a large content inventory more manageable by directing limited human review capacity toward pages with stronger predicted future-performance signals.

## 4. Results (vs baseline)

*Model vs baseline on the same split. The honest table.*


The central evaluation question was whether the learned Random Forest model could produce a stronger ranking of content pages than the transparent rule-based baseline.

Both approaches were evaluated on the same **18,743 held-out test observations**. The baseline generated a ranking using its hand-written prioritization rule, while the Random Forest generated a ranking using predicted future organic sessions.

Because the final modeling objective is to estimate future organic performance and prioritize pages for review, ranking quality was evaluated using **Normalized Discounted Cumulative Gain (NDCG)** at multiple ranking depths.

### 4.1 Main comparison

|    K | Random Forest NDCG | Baseline NDCG | Improvement |
| ---: | -----------------: | ------------: | ----------: |
|   20 |         **0.9248** |        0.8113 | **+0.1135** |
|   50 |         **0.9366** |        0.8099 | **+0.1267** |
|  100 |         **0.9369** |        0.7756 | **+0.1614** |
|  500 |         **0.8633** |        0.7244 | **+0.1389** |
| 1000 |         **0.8197** |        0.6971 | **+0.1226** |

The Random Forest produced a substantially stronger ranking than the rule-based baseline at every evaluated ranking depth.

The strongest observed result occurred at **NDCG@100**, where the Random Forest achieved **0.9369**, compared with **0.7756** for the baseline, an improvement of **0.1614**.

The model also achieved **0.9366 NDCG@50**, compared with **0.8099** for the baseline, demonstrating that the learned ranking remained particularly strong near the top of the review queue.

### 4.2 Ranking performance across review depths

The results show that the Random Forest consistently outperformed the baseline across both narrow and broader review queues.

At the smallest evaluated depth, **NDCG@20 was 0.9248** for the Random Forest compared with **0.8113** for the baseline. At **NDCG@50**, the model achieved **0.9366**, while the baseline achieved **0.8099**.

The largest observed gap occurred at **NDCG@100**. The Random Forest achieved **0.9369**, compared with **0.7756** for the baseline, representing a **0.1614 absolute improvement**.

Performance remained stronger at larger ranking depths. At **NDCG@500**, the Random Forest achieved **0.8633** compared with **0.7244**, while at **NDCG@1000** it achieved **0.8197** compared with **0.6971**.

This consistency indicates that the learned model was not only effective at the very top of the ranking but also maintained an advantage as the review population expanded.

### 4.3 Interpretation

The results support the use of the Random Forest as a ranking-based prioritization mechanism under the tested evaluation setup.

The key finding is not simply that the model produces predictions, but that its ranking of pages provides substantially better ordering quality than the transparent baseline.

For an SEO or content team with limited review capacity, this is important because pages near the top of the queue receive greater attention. The high NDCG values indicate that observations with stronger future organic-performance relevance were concentrated near the top of the model-generated ranking.

The strongest performance at **NDCG@100 = 0.9369** suggests that the model was particularly effective when prioritizing approximately the first 100 pages for review.

However, this result should be interpreted as an evaluation of ranking quality, not as proof that every highly ranked page requires intervention or that acting on those pages will necessarily improve future organic performance.

### 4.4 Model evaluation context

The final Random Forest was evaluated on **18,743 held-out test observations** using **90 processed model-input features**.

The model was trained to estimate future organic sessions rather than directly reproduce a pre-existing decline label. Its continuous predictions were subsequently used to rank observations for prioritization.

The evaluation therefore measures whether the learned model can produce a useful ordering of pages relative to the baseline under the final warehouse-derived modeling framework.

The final test audit confirmed that all **18,743 test observations** received predictions and that the ranking evaluation was completed without NaN values or invalid NDCG scores.

### 4.5 What the result does not prove

The results do not prove that the Random Forest will achieve the same ranking performance on future data, new clients, or changing search environments.

They also do not prove that a high-ranked page should automatically be refreshed or optimized. A strong ranking score indicates that the observation deserves greater review priority under the model; it does not establish a causal reason for its performance or prescribe a specific action.

Similarly, the comparison does not establish that the Random Forest is universally optimal. Other models, additional features, alternative temporal validation strategies, or future data may produce different results.

The appropriate conclusion is therefore limited to the tested setup:

**Within the final warehouse-derived modeling population and held-out test evaluation, the Random Forest produced substantially stronger ranking quality than the rule-based baseline across all evaluated NDCG depths.**

## 5. Limitations

*What this work cannot claim.*


The results demonstrate that the Random Forest produced stronger ranking performance than the hand-written baseline under the tested evaluation setup. However, these findings should not be interpreted as proof that the model will achieve the same performance in production, that the identified signals cause future organic performance, or that a high-ranked page automatically requires optimization.

### 5.1 Dataset scope

The reported modeling results were produced from the **323,926-observation final modeling population** derived from the FlyRank analytics warehouse.

Although the underlying warehouse provides a broader historical data environment, only observations satisfying the study's eligibility, temporal, target-construction, and quality-control requirements were included in the final modeling population.

The results should therefore not be generalized automatically to every record in the FlyRank warehouse or to future populations with substantially different characteristics.

### 5.2 Target limitation

The final modeling target was **future organic sessions** rather than a directly observed business outcome such as revenue, conversion, or successful content optimization.

The model therefore estimates future organic-performance behavior from the historical signals available in the modeling population.

A high predicted value does not independently establish that a page will achieve a particular business outcome or that optimization of the page will necessarily improve its performance.

### 5.3 Association is not causation

The Random Forest identifies patterns between historical features and future organic-session outcomes. It does not establish causal relationships.

For example, an association between content age, historical search visibility, or engagement and future organic sessions should not be interpreted as proof that changing that feature will directly improve future performance.

The model is therefore useful for prioritization and prediction, but not for causal diagnosis.

### 5.4 Validation scope

The final modeling workflow used separate training, validation, and held-out test populations, with **245,323 training observations, 59,860 validation observations, and 18,743 held-out test observations**.

The test population was reserved for final evaluation, while validation data were used for model comparison, ranking diagnostics, error analysis, and robustness analysis.

Although this separation provides protection against evaluating the model on the same observations used for model development, the reported results still represent one specific evaluation setup rather than a guarantee of future performance.

### 5.5 Client-level generalization

The modeling population covered **53 pseudonymized clients**, while the validation robustness audit examined **8 clients**.

Client populations may differ substantially in content strategy, traffic volume, search demand, publishing behavior, and performance distributions.

Consequently, aggregate ranking metrics may not represent how the model will behave equally well for every current or future client.

### 5.6 Model and feature limitations

The final supervised model used a **Random Forest Regressor** operating on **90 processed model-input features**.

The feature representation was constructed from historical keyword, content, search-performance, traffic, engagement, temporal, and availability signals.

Other model families, feature-engineering strategies, temporal validation designs, hyperparameter configurations, or additional data sources could produce different results.

The study therefore demonstrates the performance of the tested modeling approach rather than establishing that Random Forest is universally optimal for future versions of the problem.

### 5.7 Ranking limitations

The primary evaluation focused on **NDCG@20, NDCG@50, NDCG@100, NDCG@500, and NDCG@1000**.

NDCG measures the quality of the ordering of observations, particularly rewarding relevant observations appearing near the top of the ranking. It does not directly measure the business value generated by acting on a highly ranked page.

A page can therefore receive a strong ranking position without necessarily being the most strategically valuable page to optimize.

Business importance, editorial priorities, seasonality, technical problems, competitive changes, and planned content initiatives may all influence the final decision without being fully represented in the model.

### 5.8 Baseline limitations

The rule-based baseline provides a transparent benchmark against which the Random Forest can be evaluated.

However, the baseline itself is only one manually specified prioritization strategy. Its performance does not represent the theoretical maximum achievable without machine learning.

The observed improvement therefore demonstrates that the tested Random Forest ranking outperformed the tested baseline under the same evaluation framework; it does not prove that machine learning will outperform every possible rule-based or expert-designed approach.

### 5.9 Error and distribution limitations

The final modeling population contains a highly uneven future-organic-session distribution, including a large number of observations with zero target values and **17,478 observations with positive target values**.

This distribution can make aggregate prediction and ranking behavior sensitive to the composition of the evaluation population.

Changes in traffic distributions, search behavior, client composition, content types, or data availability may therefore affect model performance when the system is applied to future observations.

### 5.10 Temporal limitations

The modeling population was constructed from historical observations covering multiple dates and time periods. Search behavior, content inventories, traffic patterns, and SEO environments can change over time.

A model trained on historical relationships may therefore become less reliable when the underlying data-generating process changes materially.

For this reason, future deployment should include monitoring of prediction quality, feature distributions, target distributions, and client-level performance.

### 5.11 Reason-code limitations

The human-readable reason codes included in the ranked action queue are intended to help reviewers interpret observable characteristics of high-priority pages.

They should not be treated as causal explanations of the Random Forest prediction.

The model ranking and the review reason codes serve different purposes: the model determines relative priority, while the reason codes provide additional context for human investigation.

### 5.12 Operational limitation

The system is designed as **decision support**.

A high-ranked page should receive greater attention, but it should not automatically be refreshed, rewritten, redirected, or otherwise changed solely because of its model score.

Final action should consider the page's search intent, strategic importance, current performance, content quality, technical context, and other information unavailable to the model.

### Honest conclusion

Within the **323,926-observation warehouse-derived modeling population** and the held-out evaluation setup, the Random Forest produced substantially stronger ranking quality than the rule-based baseline across all evaluated NDCG depths.

The evidence supports using the model as a **prioritization aid for SEO and content review**, but it does not justify claims of guaranteed future performance, causal explanations, or fully automated optimization decisions.

## 6. Ranked recommendations

*The action playbook output — the paper's recommendations section.*

## 6. Ranked Recommendations

The model's primary operational output is a **ranked content-review queue**. Pages are ordered according to their predicted future organic performance, allowing an SEO or content team to focus limited review capacity on pages where the model identifies greater potential for optimization, investigation, or monitoring.

The ranking is intended to support prioritization rather than automate the final content decision.

### 6.1 Recommended review order

**1. Review the highest-ranked pages first**

Pages appearing near the top of the Random Forest ranking should receive earlier review because the model assigns them stronger predicted future organic-performance values.

The purpose of the ranking is to concentrate review attention on the observations that the model considers most relevant under the learned historical relationships.

**2. Prioritize pages using both model ranking and business context**

A high model ranking should be treated as a signal to investigate the page, not as an automatic instruction to optimize it.

Reviewers should consider whether the page has strategic importance, sufficient search demand, an appropriate search intent, and a realistic opportunity for improvement before deciding on an action.

**3. Investigate historical search-performance signals**

For highly ranked pages, reviewers should examine historical impressions, clicks, average search position, CTR, and related search-performance indicators.

These signals can help determine whether the model's ranking corresponds to a meaningful SEO opportunity or whether other factors explain the observed pattern.

**4. Investigate content freshness and engagement**

Content age, update history, engagement, and traffic behavior should be considered alongside the model ranking.

A highly ranked page that is also old, recently changed, weakly engaged, or showing unusual historical performance may warrant deeper investigation.

These signals are review inputs rather than causal explanations of the model's prediction.

**5. Use lower-ranked pages as secondary work**

Pages lower in the model ranking can remain in the review queue but should generally receive attention after the highest-ranked observations, subject to available capacity and business priorities.

The ranking therefore provides a way to allocate limited review resources progressively rather than requiring every page to receive the same level of investigation.

### 6.2 Human review before action

The model ranking should determine **review priority**, not the final action.

Before optimizing a page, a reviewer should consider:

* whether the page still satisfies its intended search intent;
* whether the topic remains strategically important;
* whether historical performance reflects a persistent pattern or a temporary change;
* whether the page has recently been created or updated;
* whether technical, competitive, seasonal, or external factors may affect performance;
* whether optimization is likely to produce meaningful business value;
* whether another page or initiative should receive priority instead.

A page should therefore move from:

**model ranking → human review → diagnosis → final action**

rather than directly from:

**model ranking → automated optimization**.

### 6.3 Recommended action categories

The ranked output can be translated into three broad review categories:

| Ranking / review condition                               | Recommended action                       |
| -------------------------------------------------------- | ---------------------------------------- |
| Very high model ranking + clear optimization opportunity | **Review for optimization**              |
| High model ranking but unclear opportunity               | **High-priority investigation**          |
| Lower model ranking                                      | **Monitor or review if capacity allows** |

These categories are intentionally broader than an automated recommendation. The model establishes priority, while the reviewer determines whether optimization, monitoring, or no action is appropriate.

### 6.4 How the queue should be used

The ranked queue should be treated as a **worklist**, not as a definitive diagnosis.

A page near the top of the queue has been identified by the model as having a relatively strong predicted future organic-performance value. The reviewer should then examine the page's historical SEO, content, traffic, and business context to determine whether the ranking represents a genuine opportunity.

This distinction is important because a strong prediction does not necessarily mean that changing the page will improve its future performance.

The queue combines the consistency and scale of machine-learning ranking with human judgment about factors that are not represented in the model.

### 6.5 Recommended operating workflow

The proposed operating workflow is:

**Rank → Review → Diagnose → Decide → Act → Monitor**

1. **Rank** pages using the Random Forest's predicted future organic-performance values.

2. **Review** the highest-ranked pages first.

3. **Diagnose** the likely source of the opportunity using historical SEO, content, search-performance, traffic, and business evidence.

4. **Decide** whether optimization, monitoring, investigation, or no action is appropriate.

5. **Act** only after human review and approval.

6. **Monitor** subsequent performance and evaluate whether the model and prioritization process remain useful over time.

The purpose of this workflow is to use machine learning to make a large content inventory more manageable while preserving human judgment over the final SEO and content decisions.

## 7. Artifacts the paper embeds

*Generate/collect the charts and tables your deployed page will show.*

## 7. Artifacts the Paper Embeds

The deployed research page will embed a focused set of artifacts selected to communicate the main findings, demonstrate the practical workflow, and support reproducibility without exposing private client information.

### 7.1 Model vs baseline ranking comparison

A line or grouped comparison chart will present the **Random Forest NDCG** against the **rule-based baseline NDCG** across the evaluated ranking depths.

|    K | Random Forest NDCG | Baseline NDCG | Improvement |
| ---: | -----------------: | ------------: | ----------: |
|   20 |         **0.9248** |        0.8113 | **+0.1135** |
|   50 |         **0.9366** |        0.8099 | **+0.1267** |
|  100 |         **0.9369** |        0.7756 | **+0.1614** |
|  500 |         **0.8633** |        0.7244 | **+0.1389** |
| 1000 |         **0.8197** |        0.6971 | **+0.1226** |

**Purpose:** Show the main result of the study: the Random Forest produced stronger ranking quality than the transparent baseline at every evaluated review depth.

The chart should make the strongest observed result particularly clear: **NDCG@100 = 0.9369 for the Random Forest versus 0.7756 for the baseline.**

### 7.2 Evaluation summary

The paper will include a concise evaluation summary showing the final modeling and test-evaluation context.

| Metric / Property                       |                      Result |
| --------------------------------------- | --------------------------: |
| Final modeling population               |    **323,926 observations** |
| Training observations                   |                 **245,323** |
| Validation observations                 |                  **59,860** |
| Held-out test observations              |                  **18,743** |
| Processed model features                |                      **90** |
| Model                                   | **Random Forest Regressor** |
| Positive future-organic-session targets |                  **17,478** |
| Validation clients audited              |                       **8** |

The primary ranking results will be reported separately through the NDCG comparison.

**Purpose:** Give readers the necessary context for interpreting the ranking results and make clear that the final study is based on the warehouse-derived modeling population rather than the earlier 30,000-row development dataset.

### 7.3 Ranked action queue

The paper will include a representative view of the final ranked action queue generated from the Random Forest workflow.

The queue can contain:

* pseudonymized content identifier;
* pseudonymized client identifier;
* model/ranking score;
* predicted future organic sessions;
* ranking position;
* priority classification;
* recommended review action;
* human-readable review signals;
* relevant historical SEO and performance attributes.

The complete queue is retained as a project artifact rather than displaying every observation on the public research page.

**Purpose:** Demonstrate how model predictions are converted into a practical content-review worklist.

The queue should be presented as a prioritization mechanism rather than as an automated list of pages that must be changed.

### 7.4 Feature-importance evidence

The paper may include a compact feature-importance visualization or table derived from the final Random Forest model.

The artifact will show which processed features contributed most strongly to the model's learned prediction structure.

Feature importance should be presented as evidence of **model behavior**, not as evidence that individual features causally determine future organic performance.

**Purpose:** Help readers understand the types of historical signals the model used while maintaining the distinction between predictive association and causation.

### 7.5 Error and validation diagnostics

Selected validation and test diagnostics may be included to demonstrate that the model was evaluated beyond a single headline metric.

Relevant artifacts include:

* validation error analysis;
* residual diagnostics;
* residual buckets;
* ranking audits;
* NDCG audits;
* client-level robustness analysis.

Only the most informative views should be embedded directly in the research page. Detailed CSV outputs remain available as supporting technical artifacts.

**Purpose:** Demonstrate that model quality was examined across ranking behavior, prediction error, and client-level variation rather than relying only on one aggregate score.

### 7.6 Reproducibility artifacts

The paper will link to the notebooks and generated technical artifacts used throughout the final workflow, including the data investigation, feature construction, model evaluation, ranking analysis, diagnostics, and action-queue generation.

The final project organization separates the technical evidence from oversized local-only artifacts. The **108.41 MB `current_population_baseline.csv`** is retained locally rather than included in the submission technical-output directory because of its size.

The submission technical-output directory contains the relevant compact evaluation, diagnostic, feature-importance, ranking, and action-queue artifacts.

**Purpose:** Provide sufficient evidence for technical inspection and reproducibility while keeping the public submission focused and manageable.

### Artifact selection principle

Only artifacts that directly support a finding, demonstrate the modeling workflow, or support a reproducibility claim should be embedded in the paper.

The primary public visual should communicate the **Random Forest versus baseline ranking comparison**. Supporting artifacts should provide enough evidence to understand the dataset scale, model behavior, validation process, and practical ranking output without overwhelming the reader.

All public-facing artifacts should use pseudonymized identifiers and derived results. Private client names, private URLs, raw search queries, credentials, and other non-public information should not be exposed.

The artifacts should reinforce the central conclusion of the study:

**The Random Forest provides a stronger ranking of future organic-performance outcomes than the tested rule-based baseline under the final held-out evaluation setup, while human reviewers remain responsible for deciding what action, if any, should be taken.**

## 8. 5-Minute Demo Outline

### 1. Question — ~45 seconds

**Question:** Can historical content, keyword, SEO, and web-analytics signals be used to estimate future organic performance and rank content pages according to their potential for earlier review or optimization?

The practical problem is that SEO and content teams may have a large inventory of pages but limited capacity to investigate every page equally.

The goal is therefore to use historical signals to create a ranked queue that helps the team determine **which pages deserve attention first**.

The system is designed as decision support: the model provides the ranking, while human reviewers decide what action, if any, should be taken.

### 2. Method — ~1 minute

The final study used a warehouse-derived modeling population of **323,926 observations across 53 pseudonymized clients**.

Historical content, keyword, SEO, search-performance, traffic, and engagement signals were transformed into a model-ready feature representation.

The final Random Forest model used **90 processed features** and was trained to predict **future organic sessions**.

The data was separated into training, validation, and held-out test populations:

* **245,323 training observations**
* **59,860 validation observations**
* **18,743 held-out test observations**

Client-level separation was maintained during the evaluation process to reduce the risk of information from the same client appearing across inappropriate evaluation boundaries.

The primary evaluation metric was **NDCG**, because the practical objective is not simply to predict an exact number of future sessions but to **rank pages effectively**, especially near the top of the review queue.

### 3. One Chart — ~45 seconds

Show the **Random Forest vs Rule-Based Baseline NDCG** comparison across ranking depths.

|    K | Random Forest | Baseline | Improvement |
| ---: | ------------: | -------: | ----------: |
|   20 |    **0.9248** |   0.8113 | **+0.1135** |
|   50 |    **0.9366** |   0.8099 | **+0.1267** |
|  100 |    **0.9369** |   0.7756 | **+0.1614** |
|  500 |    **0.8633** |   0.7244 | **+0.1389** |
| 1000 |    **0.8197** |   0.6971 | **+0.1226** |

The strongest observed result was at **NDCG@100**, where the Random Forest achieved **0.9369**, compared with **0.7756** for the baseline.

The important point is that the Random Forest outperformed the transparent rule-based baseline at **every evaluated ranking depth**.

### 4. One Honest Result — ~1 minute

The final held-out evaluation shows that the Random Forest produced a substantially stronger ranking than the rule-based baseline.

At **NDCG@100**, the model achieved **0.9369**, compared with **0.7756** for the baseline, an improvement of **0.1614**.

The model also maintained stronger ranking performance at the other evaluated depths, from the first 20 pages through the first 1,000 pages.

This demonstrates that the learned model was better able to concentrate higher-value future organic-performance observations toward the top of the ranking under the tested evaluation setup.

However, this is an **observed ranking result**, not a guarantee of future production performance.

It also does not prove that optimizing a highly ranked page will cause its organic traffic to increase. The model identifies predictive patterns in historical data; it does not establish causation.

### 5. One Recommendation — ~1 minute

Use the Random Forest as a **prioritization aid for human review**.

The recommended workflow is:

**Rank → Review → Diagnose → Decide → Act → Monitor**

Pages near the top of the ranking should be reviewed first.

The reviewer should then examine the page's historical search visibility, traffic, engagement, content characteristics, keyword context, freshness, and business importance before deciding what to do.

Possible outcomes include:

* review for optimization;
* investigate further;
* monitor performance;
* leave unchanged;
* prioritize another page instead.

The model should therefore determine **where the team looks first**, rather than automatically determining **what the team should change**.

### Closing — ~30 seconds

The main takeaway is simple:

**The model does not decide what to change; it helps decide which pages deserve attention first.**

The final capstone demonstrates how a large warehouse dataset can be transformed into a practical machine-learning ranking workflow—from historical data and feature engineering to validation, ranking evaluation, and human-guided action.

The Random Forest produced a stronger ranking than the rule-based baseline across all tested NDCG depths, while the final content and SEO decisions remain with human reviewers.

## 9. Shareable Cuts

### A. Short Social Post

I built a machine-learning content-prioritization workflow during the FlyRank ML Internship to help SEO and content teams identify which pages deserve attention first.

The final study used a warehouse-derived population of **323,926 content observations across 53 pseudonymized clients**. I engineered historical content, keyword, SEO, search-performance, traffic, and engagement signals and trained a **Random Forest Regressor** to estimate future organic sessions.

The model was evaluated against a transparent rule-based baseline using ranking-focused NDCG metrics on a held-out test population of **18,743 observations**.

The Random Forest outperformed the baseline at every evaluated ranking depth, achieving **0.9369 NDCG@100 compared with 0.7756 for the baseline**.

The key lesson was that the value of the system is not in automatically deciding what content to change. It is in creating a better-ranked starting point for human review.

**Rank → Review → Diagnose → Decide → Act → Monitor**

### B. Employer-Facing Summary

I built a machine-learning content-prioritization workflow using a warehouse-derived modeling population of **323,926 observations across 53 pseudonymized clients**. The workflow transformed historical content, keyword, SEO, search-performance, traffic, and engagement signals into a processed feature representation and trained a **Random Forest Regressor** to estimate future organic sessions.

The model was evaluated against a transparent rule-based baseline using a held-out test population of **18,743 observations** and ranking-focused NDCG metrics at multiple review depths.

The Random Forest outperformed the baseline across all evaluated depths, with **NDCG@100 of 0.9369 versus 0.7756 for the baseline**, representing an improvement of **0.1614**.

The project demonstrates an end-to-end decision-support workflow for content prioritization: historical warehouse data is transformed into predictive signals, model outputs are converted into a ranked review queue, and human reviewers retain responsibility for diagnosing pages and deciding whether any intervention is appropriate.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.